---
permalink: audit/idel-ilm-initiated-delete.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, IDEL, ILM Initiated Delete 
summary: ILM 开始删除对象时会生成此消息。 
---
= idel ： ILM 已启动删除
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ILM 开始删除对象时会生成此消息。

在以下任一情况下都会生成 idel 消息：

* * 对于合规 S3 存储分段中的对象 * ：当 ILM 开始自动删除对象的过程时，系统会生成此消息，因为该对象的保留期限已过期（假设已启用自动删除设置且已关闭合法保留）。
* *适用于不合规S3存储分段中的对象*。当ILM开始删除对象时、会生成此消息、因为活动ILM策略中当前没有应用于对象的放置指令。


[cols="1a,1a,4a"]
|===
| 代码 | 字段 | 说明 


 a| 
CBID
 a| 
内容块标识符
 a| 
对象的 CBID 。



 a| 
CMPA
 a| 
合规性：自动删除
 a| 
仅适用于合规 S3 存储分段中的对象。0 （ false ）或 1 （ true ），指示合规对象在保留期限结束时是否应自动删除，除非分段处于合法保留状态。



 a| 
Cmpl
 a| 
合规性：法律保留
 a| 
仅适用于合规 S3 存储分段中的对象。0 （ false ）或 1 （ true ），指示存储分段当前是否处于合法保留状态。



 a| 
CMPR
 a| 
合规性：保留期限
 a| 
仅适用于合规 S3 存储分段中的对象。对象保留期限的长度，以分钟为单位。



 a| 
CTME
 a| 
合规性：载入时间
 a| 
仅适用于合规 S3 存储分段中的对象。对象的载入时间。您可以将保留期限（以分钟为单位）添加到此值，以确定何时可以从存储分段中删除对象。



 a| 
DMRK
 a| 
删除标记版本 ID
 a| 
从版本控制的存储分段中删除对象时创建的删除标记的版本 ID 。存储分段上的操作不包括此字段。



 a| 
CSIZ
 a| 
内容大小
 a| 
对象的大小（以字节为单位）。



 a| 
LOC
 a| 
位置
 a| 
对象数据在 StorageGRID 系统中的存储位置。如果对象没有位置（例如，已删除），则此对象的值为 "" 。

CEC：对于纠删编码对象、应用于对象数据的纠删编码配置文件ID和纠删编码组ID。

CLDI ：对于复制的对象， LDR 节点 ID 和对象位置的卷 ID 。

CLNL ：归档对象数据时对象位置的弧节点 ID 。



 a| 
路径
 a| 
S3存储分段/密钥
 a| 
S3存储分段名称和S3密钥名称。



 a| 
RSLT
 a| 
结果
 a| 
ILM 操作的结果。

SUC ： ILM 操作成功。



 a| 
规则
 a| 
规则标签
 a| 
* 如果合规 S3 存储分段中的某个对象因其保留期限已过期而被自动删除，则此字段为空。
* 如果由于当前没有其他应用于对象的放置指令而删除对象，则此字段将显示应用于对象的最后一个 ILM 规则的可读标签。




 a| 
SGRP
 a| 
站点（组）
 a| 
如果存在此对象，则会在指定的站点上删除此对象，而不是在其中载入此对象的站点。



 a| 
UUID
 a| 
通用唯一标识符
 a| 
StorageGRID 系统中对象的标识符。



 a| 
VSID
 a| 
版本ID
 a| 
已删除对象的特定版本的版本 ID 。对未受版本管理的分段中的分段和对象执行的操作不包括此字段。

|===