---
permalink: audit/shea-s3-head.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, SHEA, S3 HEAD 
summary: 当 S3 客户端发出 HEAD 事务时，系统会请求检查是否存在对象或存储分段，并检索有关对象的元数据。如果事务成功，服务器将发出此消息。 
---
= Shea ： S3 机头
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
当 S3 客户端发出 HEAD 事务时，系统会请求检查是否存在对象或存储分段，并检索有关对象的元数据。如果事务成功，服务器将发出此消息。

[cols="1a,1a,4a"]
|===
| 代码 | 字段 | 说明 


 a| 
CBID
 a| 
内容块标识符
 a| 
请求的内容块的唯一标识符。如果 CBID 未知，则此字段将设置为 0 。存储分段上的操作不包括此字段。



 a| 
CNID
 a| 
连接标识符
 a| 
TCP/IP 连接的唯一系统标识符。



 a| 
CSIZ
 a| 
内容大小
 a| 
检查对象的大小（以字节为单位）。存储分段上的操作不包括此字段。



 a| 
HTRH
 a| 
HTTP 请求标头
 a| 
列出配置期间选择的已记录 HTTP 请求标头名称和值。

 `X-Forwarded-For`如果请求中存在此地址、并且此值与请求发送者IP地址不同(SAIP审核字段)、则会自动包含此 `X-Forwarded-For`地址。



 a| 
RSLT
 a| 
结果代码
 a| 
GET 事务的结果。结果始终为：

SUC ：成功



 a| 
S3AI
 a| 
S3 租户帐户 ID （请求发件人）
 a| 
发送请求的用户的租户帐户 ID 。空值表示匿名访问。



 a| 
S3AK
 a| 
S3 访问密钥 ID （请求发件人）
 a| 
发送请求的用户的哈希 S3 访问密钥 ID 。空值表示匿名访问。



 a| 
S3BK
 a| 
S3 存储分段
 a| 
S3 存储分段名称。



 a| 
S3KY
 a| 
S3 密钥
 a| 
S3 密钥名称，不包括存储分段名称。存储分段上的操作不包括此字段。



 a| 
SACC
 a| 
S3 租户帐户名称（请求发件人）
 a| 
发送请求的用户的租户帐户名称。匿名请求为空。



 a| 
SAIP
 a| 
IP 地址（请求发件人）
 a| 
发出请求的客户端应用程序的 IP 地址。



 a| 
SBAC
 a| 
S3 租户帐户名称（存储分段所有者）
 a| 
存储分段所有者的租户帐户名称。用于标识跨帐户或匿名访问。



 a| 
SBAI
 a| 
S3 租户帐户 ID （存储分段所有者）
 a| 
目标存储分段所有者的租户帐户 ID 。用于标识跨帐户或匿名访问。



 a| 
SUSR
 a| 
S3 用户 URN （请求发件人）
 a| 
发出请求的用户的租户帐户 ID 和用户名。用户可以是本地用户，也可以是 LDAP 用户。例如： `urn:sgws:identity::03393893651506583485:root`

匿名请求为空。



 a| 
时间
 a| 
时间
 a| 
请求的总处理时间，以微秒为单位。



 a| 
TLSIP
 a| 
可信负载平衡器 IP 地址
 a| 
如果请求是由受信任的第 7 层负载平衡器路由的，则为负载平衡器的 IP 地址。



 a| 
UUID
 a| 
通用唯一标识符
 a| 
StorageGRID 系统中对象的标识符。



 a| 
VSID
 a| 
版本ID
 a| 
所请求对象的特定版本的版本 ID 。对未受版本管理的分段中的分段和对象执行的操作不包括此字段。

|===