---
permalink: audit/sput-s3-put.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, SPUT, S3 PUT 
summary: 当 S3 客户端发出 PUT 事务时，系统会请求创建新对象或存储分段。如果事务成功，服务器将发出此消息。 
---
= SPUT ： S3 PUT
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
当S3客户端发出Put事务时、系统会请求创建新对象或存储分段、或者删除存储分段/对象子资源。如果事务成功，服务器将发出此消息。

[cols="1a,1a,4a"]
|===
| 代码 | 字段 | 说明 


 a| 
CBID
 a| 
内容块标识符
 a| 
请求的内容块的唯一标识符。如果 CBID 未知，则此字段将设置为 0 。存储分段上的操作不包括此字段。



 a| 
CMPS
 a| 
合规性设置
 a| 
创建存储分段时使用的合规性设置(如果请求中存在)(截断为前1024个字符)。



 a| 
CNCH
 a| 
一致性控制标题
 a| 
如果请求中存在一致性控制 HTTP 请求标头的值。



 a| 
CNID
 a| 
连接标识符
 a| 
TCP/IP 连接的唯一系统标识符。



 a| 
CSIZ
 a| 
内容大小
 a| 
检索到的对象的大小（以字节为单位）。存储分段上的操作不包括此字段。



 a| 
GFID
 a| 
网格联合连接ID
 a| 
与跨网格复制放置请求关联的网格联合连接的连接ID。仅包含在目标网格的审核日志中。



 a| 
GFSA
 a| 
网格联合源帐户ID
 a| 
源网格上用于跨网格复制放置请求的租户帐户ID。仅包含在目标网格的审核日志中。



 a| 
HTRH
 a| 
HTTP 请求标头
 a| 
列出配置期间选择的已记录 HTTP 请求标头名称和值。

 `X-Forwarded-For`如果请求中存在此地址、并且此值与请求发送者IP地址不同(SAIP审核字段)、则会自动包含此 `X-Forwarded-For`地址。

`x-amz-bypass-governance-retention`如果请求中存在、则会自动包含。



 a| 
LKEN
 a| 
对象锁定已启用
 a| 
请求标头的值 `x-amz-bucket-object-lock-enabled`(如果在请求中存在)。



 a| 
LKLH
 a| 
对象锁定合法保留
 a| 
请求标头的值 `x-amz-object-lock-legal-hold`(如果在PutObject请求中存在)。



 a| 
LKMD
 a| 
对象锁定保留模式
 a| 
请求标头的值 `x-amz-object-lock-mode`(如果在PutObject请求中存在)。



 a| 
LKRU
 a| 
对象锁定保留至日期
 a| 
请求标头的值 `x-amz-object-lock-retain-until-date`(如果在PutObject请求中存在)。值限制为自对象被纳入之日起100年内。



 a| 
MTME
 a| 
上次修改时间
 a| 
Unix 时间戳，以微秒为单位，用于指示上次修改对象的时间。



 a| 
RSLT
 a| 
结果代码
 a| 
PUT 事务的结果。结果始终为：

SUC ：成功



 a| 
S3AI
 a| 
S3 租户帐户 ID （请求发件人）
 a| 
发送请求的用户的租户帐户 ID 。空值表示匿名访问。



 a| 
S3AK
 a| 
S3 访问密钥 ID （请求发件人）
 a| 
发送请求的用户的哈希 S3 访问密钥 ID 。空值表示匿名访问。



 a| 
S3BK
 a| 
S3 存储分段
 a| 
S3 存储分段名称。



 a| 
S3KY
 a| 
S3 密钥
 a| 
S3 密钥名称，不包括存储分段名称。存储分段上的操作不包括此字段。



 a| 
S3SR
 a| 
S3 子资源
 a| 
要在其上操作的分段或对象子资源（如果适用）。



 a| 
SACC
 a| 
S3 租户帐户名称（请求发件人）
 a| 
发送请求的用户的租户帐户名称。匿名请求为空。



 a| 
SAIP
 a| 
IP 地址（请求发件人）
 a| 
发出请求的客户端应用程序的 IP 地址。



 a| 
SBAC
 a| 
S3 租户帐户名称（存储分段所有者）
 a| 
存储分段所有者的租户帐户名称。用于标识跨帐户或匿名访问。



 a| 
SBAI
 a| 
S3 租户帐户 ID （存储分段所有者）
 a| 
目标存储分段所有者的租户帐户 ID 。用于标识跨帐户或匿名访问。



 a| 
SRCF
 a| 
子资源配置
 a| 
新的子资源配置（截断为前 1024 个字符）。



 a| 
SUSR
 a| 
S3 用户 URN （请求发件人）
 a| 
发出请求的用户的租户帐户 ID 和用户名。用户可以是本地用户，也可以是 LDAP 用户。例如： `urn:sgws:identity::03393893651506583485:root`

匿名请求为空。



 a| 
时间
 a| 
时间
 a| 
请求的总处理时间，以微秒为单位。



 a| 
TLSIP
 a| 
可信负载平衡器 IP 地址
 a| 
如果请求是由受信任的第 7 层负载平衡器路由的，则为负载平衡器的 IP 地址。



 a| 
ULID
 a| 
上传 ID
 a| 
仅包含在CompleteMultipartUpload操作的SPUT消息中。表示所有部件均已上传和组装。



 a| 
UUID
 a| 
通用唯一标识符
 a| 
StorageGRID 系统中对象的标识符。



 a| 
VSID
 a| 
版本ID
 a| 
在受版本控制的存储分段中创建的新对象的版本 ID 。对未受版本管理的分段中的分段和对象执行的操作不包括此字段。



 a| 
VSST
 a| 
版本控制状态
 a| 
存储分段的新版本控制状态。使用两种状态："已启用"或"已暂停"。对象操作不包括此字段。

|===