---
permalink: audit/whea-swift-head.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, WHEA, Swift HEAD 
summary: 当 Swift 客户端发出 HEAD 事务时，系统会请求检查是否存在帐户，容器或对象，并检索任何相关元数据。如果事务成功，服务器将发出此消息。 
---
= WHEA ： Swift head
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
当 Swift 客户端发出 HEAD 事务时，系统会请求检查是否存在帐户，容器或对象，并检索任何相关元数据。如果事务成功，服务器将发出此消息。

[cols="1a,1a,4a"]
|===
| 代码 | 字段 | 说明 


 a| 
CBID
 a| 
内容块标识符
 a| 
请求的内容块的唯一标识符。如果 CBID 未知，则此字段将设置为 0 。对帐户和容器执行的操作不包括此字段。



 a| 
CSIZ
 a| 
内容大小
 a| 
检索到的对象的大小（以字节为单位）。对帐户和容器执行的操作不包括此字段。



 a| 
HTRH
 a| 
HTTP 请求标头
 a| 
列出配置期间选择的已记录 HTTP 请求标头名称和值。

 `X-Forwarded-For`如果请求中存在此地址、并且此值与请求发送者IP地址不同(SAIP审核字段)、则会自动包含此 `X-Forwarded-For`地址。



 a| 
RSLT
 a| 
结果代码
 a| 
HEAD 事务的结果。结果始终为：

SUC ：成功



 a| 
SAIP
 a| 
请求客户端的 IP 地址
 a| 
发出请求的客户端应用程序的 IP 地址。



 a| 
时间
 a| 
时间
 a| 
请求的总处理时间，以微秒为单位。



 a| 
TLSIP
 a| 
可信负载平衡器 IP 地址
 a| 
如果请求是由受信任的第 7 层负载平衡器路由的，则为负载平衡器的 IP 地址。



 a| 
UUID
 a| 
通用唯一标识符
 a| 
StorageGRID 系统中对象的标识符。



 a| 
WAcc
 a| 
Swift 帐户 ID
 a| 
StorageGRID 系统指定的唯一帐户 ID 。



 a| 
WCON
 a| 
Swift 容器
 a| 
Swift 容器名称。帐户操作不包括此字段。



 a| 
WOBJ
 a| 
Swift 对象
 a| 
Swift 对象标识符。对帐户和容器执行的操作不包括此字段。



 a| 
WUSR
 a| 
Swift 帐户用户
 a| 
用于唯一标识执行事务的客户端的 Swift 帐户用户名。

|===