---
permalink: swnodes/installing-storagegrid-webscale-host-services.html 
sidebar: sidebar 
keywords: how to install StorageGRID host services 
summary: 您可以使用适合您的操作系统类型的StorageGRID包来安装StorageGRID主机服务。 
---
= 安装StorageGRID主机服务 (Linux)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用适合您的操作系统类型的StorageGRID包来安装StorageGRID主机服务。


NOTE: “Linux”指的是 RHEL、Ubuntu 或 Debian 部署。有关受支持版本的列表，请参阅 https://imt.netapp.com/matrix/#welcome["NetApp 互操作性表工具（ IMT ）"^]。

[role="tabbed-block"]
====
.RHEL
--
您可以使用 StorageGRID RPM 软件包安装 StorageGRID 主机服务。

.关于此任务
以下说明介绍如何从 RPM 软件包安装主机服务。或者、您也可以使用安装归档文件中包含的DNF存储库元数据远程安装RPM包。请参见适用于 Linux 操作系统的 DNF 存储库说明。

.步骤
. 将 StorageGRID RPM 软件包复制到每个主机，或使其在共享存储上可用。
+
例如、将其放置在目录中 `/tmp`、以便在下一步中使用示例命令。

. 以 root 身份或使用具有 sudo 权限的帐户登录到每个主机，然后按指定顺序运行以下命令：
+
[listing]
----
sudo dnf --nogpgcheck localinstall /tmp/StorageGRID-Webscale-Images-version-SHA.rpm
----
+
[listing]
----
sudo dnf --nogpgcheck localinstall /tmp/StorageGRID-Webscale-Service-version-SHA.rpm
----
+

CAUTION: 您必须先安装映像软件包，然后再安装服务软件包。

+

NOTE: 如果您将软件包放置在以外的目录中 `/tmp`，请修改命令以反映您使用的路径。



--
.Ubuntu 或 Debian
--
您可以使用StorageGRID DEB 包为 Ubuntu 或 Debian 安装StorageGRID主机服务。

.关于此任务
以下说明介绍如何从 Deb 软件包安装主机服务。或者，您也可以使用安装归档中包含的 APT 存储库元数据远程安装 Deb 软件包。请参见适用于 Linux 操作系统的 APT 存储库说明。

.步骤
. 将 StorageGRID Deb 软件包复制到每个主机，或使其在共享存储上可用。
+
例如、将其放置在目录中 `/tmp`、以便在下一步中使用示例命令。

. 以 root 身份或使用具有 sudo 权限的帐户登录到每个主机，然后运行以下命令。
+
您必须先安装软件包、然后 `service`再安装 `images`软件包。如果您将软件包放置在以外的目录中 `/tmp`，请修改命令以反映您使用的路径。

+
[listing]
----
sudo dpkg --install /tmp/storagegrid-webscale-images-version-SHA.deb
----
+
[listing]
----
sudo dpkg --install /tmp/storagegrid-webscale-service-version-SHA.deb
----
+

NOTE: 在安装StorageGRID包之前，必须先安装 Python 3。这 `sudo dpkg --install /tmp/storagegrid-webscale-images-version-SHA.deb`直到您完成此操作后，命令才会失败。



--
====