---
permalink: upgrade/changes-to-grid-management-api.html 
sidebar: sidebar 
keywords: grid management api, api, api version, swagger, rest api, usageCacheDuration 
summary: StorageGRID 12.0 使用网格管理 API 的第 4 版。版本 4 弃用了版本 3；但是，版本 1、2 和 3 仍然受支持。 
---
= 对网格管理 API 进行的更改
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 12.0 使用网格管理 API 的第 4 版。版本 4 弃用了版本 3；但是，版本 1、2 和 3 仍然受支持。


NOTE: 您可以继续使用StorageGRID 12.0 中已弃用的管理 API 版本；但是， StorageGRID的未来版本将不再支持这些版本的 API。升级到StorageGRID 12.0 后，您可以使用 `PUT /grid/config/management`API。

要了解更多信息，请访问link:../admin/using-grid-management-api.html["使用网格管理 API"]。



== 分支存储桶的新端点

已添加以下端点，以便您link:../tenant/what-is-branch-bucket.html["管理分支存储桶"]：

`GET /org/containers/{branchBucketName}/branch`

`PUT /org/containers/{branchBucketName}/branch`



== Move ADC 的新专用终结点

已添加以下私有端点，以便您link:../maintain/move-adc-service.html["移动 ADC 服务"]从一个存储节点到同一站点上的另一个存储节点：

`/private/move-adc`

`/private/move-adc/start`

`/private/move-adc/retry`



== 转换为仅数据节点的新私有端点

已添加以下私有端点，以便您link:../maintain/convert-to-data-only-node.html["转换一个或多个组合存储节点"]不包含 ADC 服务到仅数据节点。

`/private/convert-to-data-only-node`

`/private/convert-to-data-only-node/start`

`/private/convert-to-data-only-node/retry`
