---
permalink: upgrade/estimating-time-to-complete-upgrade.html 
sidebar: sidebar 
keywords: upgrade, time estimate, duration, cassandra upgrade 
summary: 根据升级可能需要的时间、考虑何时升级。了解在升级的每个阶段可以执行和不能执行的操作。 
---
= 估计完成升级所需的时间
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
根据升级可能需要的时间、考虑何时升级。了解在升级的每个阶段可以执行和不能执行的操作。

.关于此任务
完成 StorageGRID 升级所需的时间取决于多种因素，例如客户端负载和硬件性能。

下表汇总了主要升级任务，并列出了每个任务所需的大致时间。下表后面的步骤提供了一些说明，您可以使用这些说明来估计系统的升级时间。

[cols="1a,2a,2a,4a"]
|===
| 升级任务 | 说明 | 所需大致时间 | 执行此任务期间 


 a| 
运行预检并升级主管理节点
 a| 
此时将运行升级预检、并停止、升级和重新启动主管理节点。
 a| 
30分钟到1小时、服务设备节点所需时间最多。

未解决的预检错误将增加此时间。
 a| 
您无法访问主管理节点。可能会报告连接错误、您可以忽略这些错误。

通过在开始升级之前运行升级预检、您可以在计划的升级维护窗口之前解决任何错误。



 a| 
启动升级服务
 a| 
此时将分发软件文件、并启动升级服务。
 a| 
每个网格节点3分钟
 a| 



 a| 
升级其他网格节点
 a| 
所有其他网格节点上的软件将按节点的批准顺序进行升级。一个管理节点或网关节点与一个存储节点同时升级。
 a| 
每个节点 15 分钟到 1 小时，设备节点所需时间最多

*注意*：对于设备节点，StorageGRID 设备安装程序会自动更新到最新版本。
 a| 
* 请勿更改网格配置。
* 请勿更改审核级别配置。
* 请勿更新ILM配置。
* 系统会阻止您执行其他维护过程，例如修补程序，停用或扩展。


*注*：如果需要执行恢复，请与技术支持联系。



 a| 
启用功能
 a| 
新版本的新功能已启用。
 a| 
不到 5 分钟
 a| 
* 请勿更改网格配置。
* 请勿更改审核级别配置。
* 请勿更新ILM配置。
* 您无法执行另一个维护操作步骤。




 a| 
升级数据库
 a| 
升级过程会检查每个节点，以验证不需要更新 Cassandra 数据库。
 a| 
每个节点 10 秒或整个网格几分钟
 a| 
从StorageGRID 11.8升级到11.9不需要升级cassanda数据库；但是、cassanda服务将在每个存储节点上停止并重新启动。

对于未来的 StorageGRID 功能版本， Cassandra 数据库更新步骤可能需要几天时间才能完成。



 a| 
最终升级步骤
 a| 
此时将删除临时文件，并完成到新版本的升级。
 a| 
5 分钟
 a| 
完成*最终升级步骤*任务后，您可以执行所有维护过程。

|===
.步骤
. 估计升级所有网格节点所需的时间。
+
.. 将 StorageGRID 系统中的节点数乘以每个节点 1 小时。
+
一般来说，设备节点的升级时间比基于软件的节点要长。

.. 在此时间之外增加1小时、以说明下载文件、运行预检验证以及完成最终升级步骤所需的时间 `.upgrade`。


. 如果您使用的是 Linux 节点，请为每个节点添加 15 分钟的时间，以考虑下载和安装 RPM 或 Deb 软件包所需的时间。
. 通过添加步骤 1 和步骤 2 的结果来计算升级的总估计时间。




== 示例：升级到StorageGRID 11.9.

假设您的系统有 14 个网格节点，其中 8 个是 Linux 节点。

. 将 14 乘以每个节点 1 小时。
. 另外，还需要 1 小时的时间来说明下载，预检和最终步骤。
+
升级所有节点的估计时间为15小时。

. 将每个节点的 8 乘以 15 分钟，以说明在 Linux 节点上安装 RPM 或 Deb 软件包的时间。
+
此步骤的估计时间为 2 小时。

. 将这些值相加。
+
您应在最长17小时内完成将系统升级到StorageGRID 11.4.0的过程。




NOTE: 根据需要、您可以通过批准要在多个会话中升级的网格节点子集来将维护窗口拆分为较小的窗口。例如、您可能希望在一个会话中升级站点A的节点、然后在以后的会话中升级站点B的节点。如果您选择在多个会话中执行升级、请注意、只有在升级完所有节点后、才能开始使用新功能。
