---
permalink: upgrade/how-your-system-is-affected-during-upgrade.html 
sidebar: sidebar 
keywords: upgrade, firmware, appliance, alert 
summary: 了解StorageGRID系统在升级期间会受到什么影响。 
---
= 升级期间对系统的影响
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
了解StorageGRID系统在升级期间会受到什么影响。



== 升级完成前允许外部 SSH 访问

升级期间允许外部 SSH 访问。升级完成后，外部 SSH 访问默认被阻止。升级后，您可以使用“网格管理器”>“安全设置”页面上的“阻止 SSH”选项卡来link:../admin/manage-external-ssh-access.html["管理外部 SSH 访问"]。网格节点之间的 SSH 访问不受影响。



== StorageGRID 升级不会造成系统中断

StorageGRID 系统可以在整个升级过程中从客户端应用程序载入和检索数据。如果您批准所有类型相同的节点(例如存储节点)进行升级、则这些节点会一次关闭一个、因此、所有网格节点或特定类型的所有网格节点都不可用。

为了保证持续可用性、请确保ILM策略包含指定存储每个对象的多个副本的规则。此外、还必须确保所有外部S3客户端均配置为向以下项之一发送请求：

* 高可用性(HA)组虚拟IP地址
* 高可用性第三方负载平衡器
* 每个客户端具有多个网关节点
* 每个客户端具有多个存储节点




== 客户端应用程序可能会发生短期中断

StorageGRID系统可以在整个升级过程中从客户端应用程序中读取数据、但是、如果升级需要重新启动这些节点上的服务、则客户端与各个网关节点或存储节点的连接可能会暂时中断。升级过程完成后、连接将恢复、服务将在各个节点上恢复。

如果无法接受短时间断开连接、则可能需要计划停机时间才能应用升级。您可以使用选择性批准来计划某些节点的更新时间。


NOTE: 您可以使用多个网关和高可用性(HA)组在升级过程中提供自动故障转移。请参阅的说明link:../admin/configure-high-availability-group.html["配置高可用性组"]。



== 后台修复无法在具有混合版本节点的网格上运行

当网格包含混合版本节点时，升级期间不会运行后台修复。站点中断期间出现的任何不一致问题在升级完成之前都不会得到修复。



== 设备固件已升级

在StorageGRID 12.0 升级期间：

* 所有StorageGRID设备节点都会自动升级到StorageGRID Appliance Installer 固件版本 12.0。
* SG6060 和 SGF6024 设备自动升级到 BIOS 固件版本 3B08.EX 和BMC固件版本 4.01.07。
* SG100 和 SG1000 设备自动升级到 BIOS 固件版本 3B13.EC 和BMC固件版本 4.75.07。
* SGF6112、SG6160、SG110 和 SG1100 设备自动升级到 BIOS 固件版本 3A14.QD 和BMC固件版本 3.19.07。




== ILM策略的处理方式会根据其状态而有所不同

* 升级后、活动策略将保持不变。
* 升级时仅保留最新的10个历史策略。
* 如果有建议的策略、则会在升级期间将其删除。




== 可能会触发警报

服务启动和停止以及 StorageGRID 系统作为混合版本环境运行时（某些网格节点运行早期版本，而其他网格节点已升级到更高版本），可能会触发警报。升级完成后，可能会触发其他警报。

例如，当服务停止时，您可能会看到*无法与节点通信*警报，或者当某些节点已升级到StorageGRID 12.0 但其他节点仍在运行StorageGRID 11.9 时，您可能会看到*Cassandra 通信错误*警报。一般来说，升级完成后这些警报将会清除。

在升级到StorageGRID 12.0 期间存储节点停止时，可能会触发 *ILM 放置无法实现* 警报。升级完成后，此警报可能会持续 1 天。

升级完成后、您可以从Grid Manager信息板中选择*最近解决的警报*或*当前警报*来查看任何与升级相关的警报。



== 配置更改受限


NOTE: 此列表专门适用于从StorageGRID 11.9 升级到StorageGRID 12.0。如果您要升级到另一个StorageGRID版本，请参阅该版本升级说明中的受限更改列表。

直到 * 启用新功能 * 任务完成：

* 请勿更改任何网格配置。
* 不要启用或禁用任何新功能。
* 请勿更新ILM配置。否则，您可能会遇到不一致的意外 ILM 行为。
* 请勿应用修补程序或恢复网格节点。
+

NOTE: 如果您需要在升级期间恢复节点、请联系技术支持。

* 升级到StorageGRID 12.0 时，您不应管理 HA 组、VLAN 接口或负载均衡器端点。
* 在升级到StorageGRID 12.0 完成之前，请勿删除任何 HA 组。其他 HA 组中的虚拟 IP 地址可能变得无法访问。


完成 * 最终升级步骤 * 任务之前：

* 请勿执行扩展操作步骤。
* 请勿执行停用操作步骤。

