---
permalink: upgrade/performing-upgrade.html 
sidebar: sidebar 
keywords: upgrade, how to perform a software upgrade 
summary: 您可以升级到StorageGRID 12.0 并同时应用该版本的最新修补程序。  StorageGRID升级页面提供了推荐的升级路径并直接链接到正确的下载页面。 
---
= 执行升级
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以升级到StorageGRID 12.0 并同时应用该版本的最新修补程序。  StorageGRID升级页面提供了推荐的升级路径并直接链接到正确的下载页面。

.开始之前
您已查看所有注意事项并完成所有规划和准备步骤。


CAUTION: 如果您急需扩展存储以增加容量（如果您的存储几乎已满），请不要开始升级。及时完成升级程序。如果需要恢复，请联系技术支持。



== 访问StorageGRID 升级页面

首先、访问网格管理器中的StorageGRID 升级页面。

.步骤
. 使用登录到网格管理器link:../admin/web-browser-requirements.html["支持的 Web 浏览器"]。
. 选择*维护* > *系统* > *软件更新*。
. 从StorageGRID 升级磁贴中，选择*Upgrade*。




== 选择文件

StorageGRID升级页面上的更新路径指示必须安装哪些主要版本（例如，12.0.0）和修补程序（例如，12.0.0.1）才能获得最新的StorageGRID版本。您应该按照显示的顺序安装推荐的版本和修补程序。


TIP: 如果没有显示更新路径，您的浏览器可能无法访问NetApp支持站点，或者AutoSupport页面（*支持* > *工具* > *AutoSupport* > *设置*）上的 *检查软件更新*复选框可能被禁用。

.步骤
. 对于*Select files*步骤，查看更新路径。
. 从“下载文件”部分，选择每个*Download*链接，从NetApp 支持站点 下载所需的文件。
+
如果未显示更新路径、请转到 https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetApp 下载： StorageGRID"^]以确定是否有新版本或修补程序可用、并下载所需的文件。

+

NOTE: 如果您需要在所有Linux主机上下载并安装RPM或DEB软件包、则更新路径中可能已列出StorageGRID 升级文件和修补程序文件。

. 选择*浏览*将版本升级文件上传到StorageGRID： `NetApp_StorageGRID_12.0.0_Software_uniqueID.upgrade`
+
上传和代码签名验证完成后，文件名旁边会出现一个绿色复选标记。

. 如果您下载了一个修补程序文件，请选择*Browse*(浏览*)上传该文件。此修补程序将在版本升级过程中自动应用。
. 选择 * 继续 * 。




== 运行预检

通过运行预检、您可以在开始升级网格之前检测并解决任何升级问题。

.步骤
. 对于*运行预检*步骤，首先输入网格的配置密码短语。
. 选择 * 下载恢复包 * 。
+
在升级主管理节点之前，您应该下载恢复包文件的当前副本。如果发生故障，恢复包文件可让您恢复系统。

. 下载文件后、请确认您可以访问其中的内容、包括 `Passwords.txt`文件。
. 将下载的文件(`.zip`()复制到两个安全、独立的位置。
+

CAUTION: 恢复包文件必须是安全的，因为它包含可用于从StorageGRID系统获取数据的加密密钥和密码。

. 选择*运行预检*，并等待预检完成。
. 查看每个报告的预检的详细信息并解决任何报告的错误。查看 https://kb.netapp.com/hybrid/StorageGRID/Maintenance/StorageGRID_12.0_software_upgrade_resolution_guide["StorageGRID 软件升级解决方案指南"^]适用于StorageGRID 12.0 版本。
+
在升级系统之前、您必须解决所有预检_errors_。但是、您不需要在升级之前解决precheck _WARNIS_。

+

CAUTION: 如果您已打开任何自定义防火墙端口，则会在预检验证期间收到通知。在继续升级之前，您必须联系技术支持。

. 如果为解决报告的问题而对配置进行了任何更改，请再次选择*运行预检*以获取更新的结果。
+
如果所有错误均已解决、系统将提示您开始升级。





== 开始升级并升级主管理节点

开始升级时、系统将再次运行升级预检、并自动升级主管理节点。此部分升级可能需要长达30分钟的时间。


NOTE: 升级主管理节点时、您将无法访问任何其他Grid Manager页面。审核日志也将不可用。

.步骤
. 选择*开始升级*。
+
此时将显示一条警告、提醒您暂时无法访问网格管理器。

. 选择*OK*确认警告并开始升级。
. 等待执行升级预检并升级主管理节点。
+

NOTE: 如果报告了任何预检错误，请解决这些错误，然后再次选择*Start upgrade。

+
如果网格中的另一个管理节点联机且已准备就绪、则可以使用它来监控主管理节点的状态。升级主管理节点后、您可以批准其他网格节点。

. 根据需要选择*CONTINUD*以访问*升级其他节点*步骤。




== 升级其他节点

您必须升级所有网格节点、但可以执行多个升级会话并自定义升级顺序。例如、您可能希望在一个会话中升级站点A的节点、然后在以后的会话中升级站点B的节点。如果您选择在多个会话中执行升级、请注意、只有在升级完所有节点后、才能开始使用新功能。

如果节点升级顺序非常重要，请逐个批准节点或节点组，并等待每个节点完成升级，然后再批准下一个节点或节点组。


CAUTION: 在网格节点上开始升级时，该节点上的服务将停止。稍后，网格节点将重新启动。为避免与节点通信的客户端应用程序出现服务中断、请勿批准节点的升级、除非您确定节点已做好停止和重新启动的准备。根据需要计划维护时段或通知客户。

.步骤
. 对于*升级其他节点*步骤，请查看摘要，其中提供了整个升级的开始时间以及每个主要升级任务的状态。
+
** *启动升级服务*是第一个升级任务。在此任务期间、软件文件将分发到网格节点、并在每个节点上启动升级服务。
** 当*启动升级服务*任务完成后，*升级其他网格节点*任务启动，并提示您下载恢复包的新副本。


. 出现提示时，输入您的配置密码并下载恢复包的新副本。
+

CAUTION: 主管理节点升级后，您应该下载恢复包文件的新副本。如果发生故障，恢复包文件可让您恢复系统。

. 查看每种节点类型的状态表。其中包含非主管理节点、网关节点和存储节点的表。
+
当表首次出现时，网格节点可以处于以下阶段之一：

+
** 解包升级
** 正在下载
** 正在等待批准


. [[approval-step ]]当您准备好选择要升级的网格节点(或者如果您需要取消批准选定节点)时、请按照以下说明进行操作：
+

NOTE: 对于StorageGRID 12.0 升级，如果您想批准单个节点而不是所有节点，最佳做法是在转到下一个站点之前升级整个站点。

+
[cols="1a,1a"]
|===
| 任务 | 说明 


 a| 
搜索要批准的特定节点、例如特定站点上的所有节点
 a| 
在*Search*字段中输入搜索字符串



 a| 
选择要升级的所有节点
 a| 
选择*批准所有节点*



 a| 
选择要升级的相同类型的所有节点(例如、所有存储节点)
 a| 
选择节点类型的*Approve All*按钮

如果您批准多个相同类型的节点，则这些节点将一次升级一个。



 a| 
选择要升级的单个节点
 a| 
选择节点的*Approve*按钮



 a| 
延迟所有选定节点上的升级
 a| 
选择*取消批准所有节点*



 a| 
推迟对所有选定的相同类型节点执行升级
 a| 
选择节点类型的*Unapprove All*按钮



 a| 
延迟单个节点上的升级
 a| 
选择节点的*Unapprove*按钮

|===
. 等待已批准的节点继续完成以下升级阶段：
+
** 已批准且正在等待升级
** 正在停止服务
+

NOTE: 当节点的阶段达到*停止服务*时，无法删除该节点。取消批准*按钮被禁用。

** 正在停止容器
** 清理Docker映像
** 正在升级基本操作系统软件包
+

NOTE: 当设备节点达到此阶段时、设备上的StorageGRID 设备安装程序软件将会更新。此自动化过程可确保 StorageGRID 设备安装程序版本与 StorageGRID 软件版本保持同步。

** 正在重新启动
+

NOTE: 某些型号的设备可能会多次重新启动以升级固件和BIOS。

** 重新启动后执行步骤
** 正在启动服务
** 完成


. 根据需要重复<<approval-step,审批步骤>>多次、直到所有网格节点均已升级为止。




== 完成升级

当所有网格节点均已完成升级阶段后，*升级其他网格节点*任务将显示为已完成。其余升级任务将在后台自动执行。

.步骤
. 一旦完成*Enable Features (启用功能)*任务(此任务很快完成)，您就可以开始在升级后的StorageGRID版本中使用link:whats-new.html["新增功能"]。
. Cassandra 数据库升级开始。此升级将在后台进行一到三天，并且 Cassandra 服务将在每个存储节点上停止并重新启动。在此期间，涉及元数据流的某些维护程序（例如扩展）将被禁用。
. 完成*最终升级步骤*后，即完成升级。第一步*选择文件*将重新显示绿色成功横幅。
. 验证网格操作是否已恢复正常：
+
.. 检查这些服务是否正常运行，以及是否没有意外警报。
.. 确认客户端与 StorageGRID 系统的连接是否按预期运行。




.相关信息
link:how-your-system-is-affected-during-upgrade.html["升级期间对系统的影响"]
