---
permalink: upgrade/removed-or-deprecated-features.html 
sidebar: sidebar 
keywords:  
summary: 此版本删除或弃用了某些特性和功能。查看这些项目，了解在升级之前是需要更新客户端应用程序还是修改配置。 
---
= 删除或弃用的特性和功能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
此版本删除或弃用了某些特性和功能。查看这些项目，了解在升级之前是需要更新客户端应用程序还是修改配置。



== 定义

已弃用:: 在新的生产环境中*不应*使用该功能。现有生产环境可以继续使用此功能。
生命周期结束:: 支持此功能的上次发售版本。在某些情况下、此阶段可能会删除此功能的文档。
已删除:: 第一个*不*支持此功能的版本。




== StorageGRID停止功能支持

在N+2主要版本中将删除已弃用的功能。例如、如果某个功能在版本N中已弃用(例如6.3)、则该功能的最后一个版本为N+1 (例如6.4)。当产品中不存在此功能时、版本N+2 (例如6.5)是第一个版本。

有关更多信息、请参见 https://mysupport.netapp.com/site/info/version-support["软件版本支持页面"^]。


NOTE: 在某些情况下、NetApp可能会比指示的时间更早地终止对特定功能的支持。

[cols="2a,1a,1a,1a,3a"]
|===
| 功能 | 已弃用 | 生命周期结束 | 已删除 | 早期文档的链接 


 a| 
原有警报(_NOT警报_)
 a| 
11.7
 a| 
11.8
 a| 
11.9
 a| 
https://docs.netapp.com/us-en/storagegrid-118/monitor/alarms-reference.html["报警参考(StorageGRID 11.8)"^]



 a| 
归档节点支持
 a| 
11.7
 a| 
11.8
 a| 
11.9
 a| 
https://docs.netapp.com/us-en/storagegrid-118/maintain/considerations-for-decommissioning-admin-or-gateway-nodes.html["停用归档节点的注意事项(StorageGRID 11.8)"^]

*注意*：开始升级之前，您必须：

. 停用所有归档节点。请参阅。 https://docs.netapp.com/us-en/storagegrid-118/maintain/grid-node-decommissioning.html["网格节点停用(StorageGRID 11.8文档站点)"^]
. 从存储池和ILM策略中删除所有归档节点引用。请参阅。 https://kb.netapp.com/hybrid/StorageGRID/Maintenance/StorageGRID_11.9_software_upgrade_resolution_guide["NetApp知识库：《StorageGRID软件升级解决方案指南》"^]




 a| 
通过CIFS或Samba审核导出
 a| 
11.1
 a| 
11.6
 a| 
11.7
 a| 



 a| 
CLB服务
 a| 
11.4
 a| 
11.6
 a| 
11.7
 a| 



 a| 
Docker容器引擎
 a| 
11.8
 a| 
11.9
 a| 
待定
 a| 
不再支持将 Docker 作为纯软件部署的容器引擎。 Docker 将在未来的版本中被另一个容器引擎取代。请参阅link:../swnodes/software-requirements.html["基于软件的节点的软件要求"]了解当前支持的 Docker 版本列表。



 a| 
NFS审核导出
 a| 
11.8
 a| 
11.9
 a| 
12.0
 a| 
https://docs.netapp.com/us-en/storagegrid-118/admin/configuring-audit-client-access.html["为NFS配置审核客户端访问(StorageGRID 11.8)"^]



 a| 
端口重映射
 a| 
12.0
 a| 
12.1
 a| 
12.2
 a| 



 a| 
Swift API支持
 a| 
11.7
 a| 
11.9
 a| 
12.0
 a| 
https://docs.netapp.com/us-en/storagegrid-118/swift/index.html["使用Swift REST API (StorageGRID 11.8)"^]



 a| 
RHEL 8.8
 a| 
11.9
 a| 
11.9
 a| 
12.0
 a| 



 a| 
RHEL 9.0
 a| 
11.9
 a| 
11.9
 a| 
12.0
 a| 



 a| 
RHEL 9.2
 a| 
11.9
 a| 
11.9
 a| 
12.0
 a| 



 a| 
Ubuntu 18.04
 a| 
11.9
 a| 
11.9
 a| 
12.0
 a| 



 a| 
Ubuntu 20.04
 a| 
11.9
 a| 
11.9
 a| 
12.0
 a| 



 a| 
Debian 11
 a| 
11.9
 a| 
11.9
 a| 
12.0
 a| 

|===
另请参见：

* link:../upgrade/changes-to-grid-management-api.html["对网格管理 API 进行的更改"]
* link:../upgrade/changes-to-tenant-management-api.html["对租户管理 API 进行的更改"]

