---
permalink: upgrade/troubleshooting-upgrade-issues.html 
sidebar: sidebar 
keywords: upgrade, troubleshoot, troubleshooting, errors, upgrade precheck 
summary: 如果在执行升级时出现问题、您可以自行解决问题描述 问题。如果无法解决问题描述 、请尽可能多地收集信息、然后联系技术支持。 
---
= 对升级问题进行故障排除
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果在执行升级时出现问题、您可以自行解决问题描述 问题。如果无法解决问题描述 、请尽可能多地收集信息、然后联系技术支持。



== 升级未完成

以下各节介绍如何从升级部分失败的情况中恢复。



=== 升级预检错误

要检测并解决问题，您可以在开始实际升级之前手动运行升级预检。大多数预检错误都提供了有关如何解决问题描述 的信息。



=== 配置失败

如果自动配置过程失败，请联系技术支持。



=== 网格节点崩溃或无法启动

如果网格节点在升级过程中崩溃或升级完成后无法成功启动，请联系技术支持以调查并更正任何潜在问题。



=== 载入或数据检索中断

如果在不升级网格节点时意外中断数据加网或检索、请联系技术支持。



=== 数据库升级错误

如果数据库升级失败并显示错误，请重试此升级。如果故障再次出现，请联系技术支持。

.相关信息
link:checking-systems-condition-before-upgrading-software.html["升级软件前检查系统状况"]



== 用户界面问题

升级期间或之后、网格管理器或租户管理器可能会出现问题。



=== 网格管理器在升级期间显示多条错误消息

如果在升级主管理节点时刷新浏览器或导航到另一个网格管理器页面、您可能会看到多条"503：服务不可用"和"连接到服务器时出现问题"消息。您可以安全地忽略这些消息、它们将在节点升级后立即停止显示。

如果在您开始升级后这些消息显示超过一个小时、则可能是由于某些原因导致主管理节点无法升级。如果您无法自行解决问题描述 问题、请联系技术支持。



=== Web 界面未按预期响应

升级 StorageGRID 软件后，网格管理器或租户管理器可能无法按预期做出响应。

如果您在使用 Web 界面时遇到问题：

* 确保您使用的是link:../admin/web-browser-requirements.html["支持的 Web 浏览器"]。
+

NOTE: 每个 StorageGRID 版本的浏览器支持通常会发生变化。

* 清除 Web 浏览器缓存。
+
清除缓存将删除先前版本的 StorageGRID 软件所使用的过时资源，并允许用户界面再次正常运行。有关说明，请参见 Web 浏览器的文档。





== "Docker映像可用性检查"错误消息

尝试启动升级过程时、您可能会收到一条错误消息、指出"以下问题已由Docker映像可用性检查验证套件确定"。必须先解决所有问题、然后才能完成升级。

如果您不确定解决所发现问题所需的更改，请联系技术支持。

[cols="1a,1a,1a"]
|===
| 消息 | 发生原因 | 解决方案 


 a| 
无法确定升级版本。升级版本信息文件 `{file_path}`与预期格式不匹配。
 a| 
升级软件包已损坏。
 a| 
请重新上传升级包，然后重试。如果问题仍然存在，请联系技术支持。



 a| 
未找到升级版本信息文件 `{file_path}`。无法确定升级版本。
 a| 
升级软件包已损坏。
 a| 
请重新上传升级包，然后重试。如果问题仍然存在，请联系技术支持。



 a| 
无法确定上当前安装的版本 `{node_name}`。
 a| 
节点上的关键文件已损坏。
 a| 
请联系技术支持。



 a| 
尝试列出上的版本时出现连接错误 `{node_name}`
 a| 
节点脱机或连接中断。
 a| 
请检查以确保所有节点均联机并可从主管理节点访问，然后重试。



 a| 
节点的主机 `{node_name}`未加载StorageGRID `{upgrade_version}`映像。必须先在主机上安装映像和服务，然后才能继续升级。
 a| 
用于升级的 RPM 或 Deb 软件包未安装在运行节点的主机上，或者映像仍在导入过程中。

* 注： * 此错误仅适用于在 Linux 上作为容器运行的适用场景 节点。
 a| 
检查以确保 RPM 或 Deb 软件包已安装在运行节点的所有 Linux 主机上。确保服务和映像文件的版本正确。请稍等几分钟，然后重试。

请参阅。 link:../upgrade/linux-installing-rpm-or-deb-package-on-all-hosts.html["Linux ：在所有主机上安装 RPM 或 Deb 软件包"]



 a| 
检查节点时出错 `{node_name}`
 a| 
发生意外错误。
 a| 
请稍等几分钟，然后重试。



 a| 
运行预检时未捕获到错误。 `{error_string}`
 a| 
发生意外错误。
 a| 
请稍等几分钟，然后重试。

|===