---
permalink: upgrade/verifying-installed-version-of-storagegrid.html 
sidebar: sidebar 
keywords: storagegrid, version, current version, previous version 
summary: 在开始升级之前、请确认当前安装的是先前版本的StorageGRID、并应用了最新的可用修补程序。 
---
= 验证已安装的 StorageGRID 版本
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在开始升级之前、请确认当前安装的是先前版本的StorageGRID、并应用了最新的可用修补程序。

.关于此任务
在升级到StorageGRID 12.0 之前，您的网格必须安装StorageGRID 11.9.0.8 或更高版本。如果您当前正在使用以前版本的StorageGRID，则必须安装所有以前的升级文件及其最新的修补程序（强烈推荐），直到网格的当前版本至少为StorageGRID 11.9.0.8。

中显示了一个可能的升级路径<<example-upgrade-path,示例>>。


CAUTION: NetApp强烈建议您在升级到下一个版本之前为每个StorageGRID版本应用最新的修补程序，并且还为您安装的每个新版本应用最新的修补程序。在某些情况下，您必须应用修补程序以避免数据丢失的风险。参考 https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetApp 下载： StorageGRID"^]以及每个修补程序的发行说明以了解更多信息。



== 验证已安装的版本

.步骤
. 使用登录到网格管理器link:../admin/web-browser-requirements.html["支持的 Web 浏览器"]。
. 从网格管理器的顶部，选择 * 帮助 * > * 关于 * 。
. 验证*版本*是否为 11.9.0.8 或更高版本。
. 如果*版本*不是 11.9.0.8 或更高版本，请转到 https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetApp 下载： StorageGRID"^]下载您需要的升级和修补程序文件。
. link:../upgrade/index.html["按照升级说明进行操作"]对于您下载的每个版本。link:../maintain/storagegrid-hotfix-procedure.html["应用最新的修补程序"]对于每个版本（强烈推荐）。


参考以下升级示例。



== [[example-upgrade-path]]示例：从版本 11.8 升级到StorageGRID 12.0

以下示例显示了从StorageGRID版本 11.8 升级到版本 11.9 以准备升级到StorageGRID 12.0 的步骤。

按以下顺序下载并安装软件，以便为您的系统做好升级准备：

. 升级到StorageGRID 11.8.0主要版本。
. 应用最新的StorageGRID 11.8.0._y_修补程序。
. 升级到StorageGRID 11.9.0 主要版本。
. 应用StorageGRID 11.9.0.8 或更高版本的修补程序。

