= 节点配置文件的位置
:allow-uri-read: 




== 节点配置文件的位置

将每个StorageGRID节点的配置文件放在要运行该节点的主机上的目录中 `/etc/storagegrid/nodes`。例如、如果您计划在HostA上运行一个管理节点、一个网关节点和一个存储节点、则必须将三个节点配置文件放在HostA上的中 `/etc/storagegrid/nodes`。

您可以使用文本编辑器（例如 vim 或 nanan ）在每个主机上直接创建配置文件，也可以在其他位置创建配置文件并将其移动到每个主机。



== 节点配置文件的命名

配置文件的名称非常重要。格式为 `node-name.conf`，其中 `node-name`是您分配给节点的名称。此名称显示在 StorageGRID 安装程序中，用于节点维护操作，例如节点迁移。

节点名称必须遵循以下规则：

* 必须是唯一的
* 必须以字母开头
* 可以包含字符 A 到 Z 和 a 到 z
* 可以包含数字 0 到 9
* 可以包含一个或多个连字符（ - ）
* 不得超过32个字符、不包括 `.conf`扩展名


主机服务不会解析中未遵循这些命名约定的任何文件 `/etc/storagegrid/nodes`。

如果您为网格规划了多站点拓扑，则典型的节点命名方案可能是：

`site-nodetype-nodenumber.conf`

例如、您可以为Data Center 1中的第一个管理节点和 `dc2-sn3.conf`Data Center 2中的第三个存储节点使用 `dc1-adm1.conf`。但是，只要所有节点名称都遵循命名规则，您就可以使用所需的任何方案。



== 节点配置文件的内容

配置文件包含密钥/值对、每行一个密钥和一个值。对于每个键/值对、请遵循以下规则：

* 键和值必须用等号(`=`()和可选空格分隔。
* 密钥不能包含空格。
* 这些值可以包含嵌入的空格。
* 忽略任何前导或尾随空格。


下表定义了所有受支持密钥的值。每个键都具有以下名称之一：

* *必需*：每个节点或指定节点类型都需要此参数
* *最佳实践*：可选、但建议使用
* *可选*：对于所有节点均为可选




=== 管理网络密钥



==== admin_ip

[cols="4a,2a"]
|===
| 价值 | 名称 


 a| 
此节点所属网格的主管理节点的网格网络 IPv4 地址。使用为 node_type = VM_Admin_Node 且 admin_role = Primary 的网格节点的 grid_network_IP 指定的相同值。如果省略此参数，则节点将尝试使用 mDNS 发现主管理节点。

link:how-grid-nodes-discover-primary-admin-node.html["网格节点如何发现主管理节点"]

* 注 * ：此值在主管理节点上被忽略，并且可能被禁止。
 a| 
最佳实践

|===


==== admin_network_config

[cols="4a,2a"]
|===
| 价值 | 名称 


 a| 
DHCP ，静态或已禁用
 a| 
可选

|===


==== admin_network_esl

[cols="4a,2a"]
|===
| 价值 | 名称 


 a| 
此节点应使用管理网络网关与之通信的子网的逗号分隔列表、采用CIDR表示法。

示例： `172.16.0.0/21,172.17.0.0/21`
 a| 
可选

|===


==== admin_network_gateway

[cols="4a,2a"]
|===
| 价值 | 名称 


 a| 
此节点的本地管理网络网关的 IPv4 地址。必须位于 admin_network_ip 和 admin_network_mask 定义的子网上。对于配置了 DHCP 的网络，此值将被忽略。

示例

`1.1.1.1`

`10.224.4.81`
 a| 
如果指定为、则为必填项 `ADMIN_NETWORK_ESL`。否则为可选。

|===


==== admin_network_ip

[cols="4a,2a"]
|===
| 价值 | 名称 


 a| 
此节点在管理网络上的 IPv4 地址。只有在admin_network_config = static"时才需要此密钥；不要为其他值指定此密钥。

示例

`1.1.1.1`

`10.224.4.81`
 a| 
admin_network_config = static"时为必需项。

否则为可选。

|===


==== admin_network_MAC

[cols="4a,2a"]
|===
| 价值 | 名称 


 a| 
容器中管理网络接口的 MAC 地址。

此字段为可选字段。如果省略此参数，则会自动生成 MAC 地址。

必须为 6 对十六进制数字，以冒号分隔。

示例： `b2:9c:02:c2:27:10`
 a| 
可选

|===


==== admin_network_mask

[cols="4a,2a"]
|===
| 价值 | 名称 


 a| 
此节点的 IPv4 网络掩码，位于管理网络上。当admin_network_config = static"时指定此密钥；不要为其他值指定此密钥。

示例

`255.255.255.0`

`255.255.248.0`
 a| 
如果指定了admin_network_IP且admin_network_config = static"、则此字段为必需字段。

否则为可选。

|===


==== admin_network_mtu

[cols="4a,2a"]
|===
| 价值 | 名称 


 a| 
管理网络上此节点的最大传输单元（ MTU ）。如果admin_network_config = dhcp、请勿指定。如果指定，则此值必须介于 1280 和 9216 之间。如果省略，则使用 1500 。

如果要使用巨型帧，请将 MTU 设置为适合巨型帧的值，例如 9000 。否则，请保留默认值。

* 重要信息 * ：网络的 MTU 值必须与节点所连接的交换机端口上配置的值匹配。否则，可能会发生网络性能问题或数据包丢失。

示例

`1500`

`8192`
 a| 
可选

|===


==== admin_network_target

[cols="4a,2a"]
|===
| 价值 | 名称 


 a| 
StorageGRID 节点用于管理网络访问的主机设备的名称。仅支持网络接口名称。通常，您使用的接口名称与为 grid_network_target 或 client_network_target 指定的接口名称不同。

*注意*：不要使用绑定或网桥设备作为网络目标。可以在绑定设备上配置 VLAN （或其他虚拟接口），也可以使用网桥和虚拟以太网（ veth ）对。

* 最佳实践 * ：指定一个值，即使此节点最初不具有管理员网络 IP 地址也是如此。然后，您可以稍后添加管理员网络 IP 地址，而无需重新配置主机上的节点。

示例

`bond0.1002`

`ens256`
 a| 
最佳实践

|===


==== admin_network_target_type

[cols="4a,2a"]
|===
| 价值 | 名称 


 a| 
interface (这是唯一支持的值。)
 a| 
可选

|===


==== admin_network_target_type_interface_clone_MAC

[cols="4a,2a"]
|===
| 价值 | 名称 


 a| 
判断对错

将密钥设置为 "true" 以发生原因 StorageGRID 容器使用管理网络上主机主机目标接口的 MAC 地址。

* 最佳实践： * 在需要混杂模式的网络中，请改用 admin_network_target_type_interface_clone_MAC 密钥。

有关 MAC 克隆的详细信息，请参见：

* link:../rhel/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["MAC地址克隆的注意事项和建议(Red Hat Enterprise Linux)"]
* link:../ubuntu/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["MAC 地址克隆（ Ubuntu 或 Debian ）的注意事项和建议"]

 a| 
最佳实践

|===


==== 管理角色

[cols="4a,2a"]
|===
| 价值 | 名称 


 a| 
主要或非主要

只有当NODE_TYPE = VM_Admin_Node时、才需要此密钥；不要为其他节点类型指定此密钥。
 a| 
当NODE_TYPE = VM_Admin_Node时为必需项

否则为可选。

|===


=== 块设备密钥



==== block_device_audit_logs

[cols="4a,2a"]
|===
| 价值 | 名称 


 a| 
此节点将用于永久存储审核日志的块设备专用文件的路径和名称。

示例

`/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0`

`/dev/disk/by-id/wwn-0x600a09800059d6df000060d757b475fd`

`/dev/mapper/sgws-adm1-audit-logs`
 a| 
对于节点类型为VM_Admin_Node的节点为必需项。请勿为其他节点类型指定此名称。

|===


==== block_device_RANGEDB_nnn

[cols="4a,2a"]
|===
| 价值 | 名称 


 a| 
此节点将用于永久性对象存储的块设备专用文件的路径和名称。只有节点类型为VM_Storage_Node的节点才需要此密钥；请勿为其他节点类型指定此密钥。

仅需要 block_device_RANGEDB_000 ；其余为可选。为 block_device_RANGEDB_000 指定的块设备必须至少为 4 TB ；其他块设备可以更小。

不要留下空隙。如果指定 block_device_RANGEDB_005 ，则还必须指定 block_device_RANGEDB_004 。

* 注 * ：为了与现有部署兼容，升级后的节点支持两位数的密钥。

示例

`/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0`

`/dev/disk/by-id/wwn-0x600a09800059d6df000060d757b475fd`

`/dev/mapper/sgws-sn1-rangedb-000`
 a| 
必填：

BLOCK_DEVICE_RANGEDB_000

可选：

BLOCK_DEVICE_RANGEDB_001

BLOCK_DEVICE_RANGEDB_002

BLOCK_DEVICE_RANGEDB_003

BLOCK_DEVICE_RANGEDB_004

BLOCK_DEVICE_RANGEDB_005

BLOCK_DEVICE_RANGEDB_006

BLOCK_DEVICE_RANGEDB_007

BLOCK_DEVICE_RANGEDB_008

BLOCK_DEVICE_RANGEDB_009

BLOCK_DEVICE_RANGEDB_010

BLOCK_DEVICE_RANGEDB_011

BLOCK_DEVICE_RANGEDB_012

BLOCK_DEVICE_RANGEDB_013

BLOCK_DEVICE_RANGEDB_014

BLOCK_DEVICE_RANGEDB_015

|===


==== block_device_tables

[cols="4a,2a"]
|===
| 价值 | 名称 


 a| 
此节点将用于永久存储数据库表的块设备专用文件的路径和名称。只有节点类型为VM_Admin_Node的节点才需要此密钥；不要为其他节点类型指定此密钥。

示例

`/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0`

`/dev/disk/by-id/wwn-0x600a09800059d6df000060d757b475fd`

`/dev/mapper/sgws-adm1-tables`
 a| 
必填

|===


==== block_device_var_local

[cols="4a,2a"]
|===
| 价值 | 名称 


 a| 
此节点将用于其永久性存储的块设备专用文件的路径和名称 `/var/local`。

示例

`/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0`

`/dev/disk/by-id/wwn-0x600a09800059d6df000060d757b475fd`

`/dev/mapper/sgws-sn1-var-local`
 a| 
必填

|===


=== 客户端网络密钥



==== client_network_config

[cols="4a,2a"]
|===
| 价值 | 名称 


 a| 
DHCP ，静态或已禁用
 a| 
可选

|===


==== client_network_gateway

[cols="4a,2a"]
|===


 a| 
价值
 a| 
名称



 a| 
此节点的本地客户端网络网关的 IPv4 地址，该地址必须位于 client_network_ip 和 client_network_mask 定义的子网上。对于配置了 DHCP 的网络，此值将被忽略。

示例

`1.1.1.1`

`10.224.4.81`
 a| 
可选

|===


==== client_network_IP

[cols="4a,2a"]
|===
| 价值 | 名称 


 a| 
此节点在客户端网络上的 IPv4 地址。

只有当client_network_config = static"时才需要此密钥；不要为其他值指定此密钥。

示例

`1.1.1.1`

`10.224.4.81`
 a| 
当client_network_config = static"时为必需项

否则为可选。

|===


==== 客户端网络 MAC

[cols="4a,2a"]
|===
| 价值 | 名称 


 a| 
容器中客户端网络接口的 MAC 地址。

此字段为可选字段。如果省略此参数，则会自动生成 MAC 地址。

必须为 6 对十六进制数字，以冒号分隔。

示例： `b2:9c:02:c2:27:20`
 a| 
可选

|===


==== client_network_mask

[cols="4a,2a"]
|===
| 价值 | 名称 


 a| 
此节点在客户端网络上的 IPv4 网络掩码。

当client_network_config = static"时指定此密钥；不要为其他值指定此密钥。

示例

`255.255.255.0`

`255.255.248.0`
 a| 
如果指定了client_network_IP且client_network_config = static,则为必需项

否则为可选。

|===


==== client_network_mtu

[cols="4a,2a"]
|===
| 价值 | 名称 


 a| 
客户端网络上此节点的最大传输单元（ MTU ）。如果client_network_config = dhcp、请勿指定。如果指定，则此值必须介于 1280 和 9216 之间。如果省略，则使用 1500 。

如果要使用巨型帧，请将 MTU 设置为适合巨型帧的值，例如 9000 。否则，请保留默认值。

* 重要信息 * ：网络的 MTU 值必须与节点所连接的交换机端口上配置的值匹配。否则，可能会发生网络性能问题或数据包丢失。

示例

`1500`

`8192`
 a| 
可选

|===


==== client_network_target

[cols="4a,2a"]
|===
| 价值 | 名称 


 a| 
StorageGRID 节点用于客户端网络访问的主机设备的名称。仅支持网络接口名称。通常，您使用的接口名称与为 grid_network_target 或 admin_network_target 指定的接口名称不同。

*注意*：不要使用绑定或网桥设备作为网络目标。可以在绑定设备上配置 VLAN （或其他虚拟接口），也可以使用网桥和虚拟以太网（ veth ）对。

* 最佳实践： * 指定一个值，即使此节点最初不会具有客户端网络 IP 地址也是如此。然后，您可以稍后添加客户端网络 IP 地址，而无需重新配置主机上的节点。

示例

`bond0.1003`

`ens423`
 a| 
最佳实践

|===


==== client_network_target_type

[cols="4a,2a"]
|===
| 价值 | 名称 


 a| 
接口(仅支持此值。)
 a| 
可选

|===


==== client_network_target_type_interface_clone_MAC

[cols="4a,2a"]
|===
| 价值 | 名称 


 a| 
判断对错

将密钥设置为 "true" ，以便对 StorageGRID 容器进行发生原因 处理，以使用客户端网络上主机目标接口的 MAC 地址。

* 最佳实践： * 在需要混杂模式的网络中，请改用 client_network_target_type_interface_clone_MAC 密钥。

有关 MAC 克隆的详细信息，请参见：

* link:../rhel/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["MAC地址克隆的注意事项和建议(Red Hat Enterprise Linux)"]
* link:../ubuntu/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["MAC 地址克隆（ Ubuntu 或 Debian ）的注意事项和建议"]

 a| 
最佳实践

|===


=== 网格网络密钥



==== grid_network_config

[cols="4a,2a"]
|===
| 价值 | 名称 


 a| 
静态或 DHCP

如果未指定、则默认为static"。
 a| 
最佳实践

|===


==== grid_network_gateway

[cols="4a,2a"]
|===
| 价值 | 名称 


 a| 
此节点的本地网格网络网关的 IPv4 地址，该网关必须位于 grid_network_ip 和 grid_network_mask 定义的子网上。对于配置了 DHCP 的网络，此值将被忽略。

如果网格网络是没有网关的单个子网，请使用该子网的标准网关地址（ X.y.Z.1 ）或此节点的 GRID_NETWORK_IP 值；任一值都将简化未来可能进行的网格网络扩展。
 a| 
必填

|===


==== GRID_NETWORK_IP

[cols="4a,2a"]
|===
| 价值 | 名称 


 a| 
此节点在网格网络上的 IPv4 地址。只有当GRID_NETWORK_config = STATIC时、才需要此密钥；不要为其他值指定此密钥。

示例

`1.1.1.1`

`10.224.4.81`
 a| 
如果grid network config = static,则需要此参数

否则为可选。

|===


==== GRID_NETWORK_MAC

[cols="4a,2a"]
|===
| 价值 | 名称 


 a| 
容器中网格网络接口的 MAC 地址。

必须为 6 对十六进制数字，以冒号分隔。

示例： `b2:9c:02:c2:27:30`
 a| 
可选

如果省略此参数，则会自动生成 MAC 地址。

|===


==== grid_network_mask

[cols="4a,2a"]
|===
| 价值 | 名称 


 a| 
此节点在网格网络上的 IPv4 网络掩码。如果grid network_config = static"、请指定此密钥；不要为其他值指定此密钥。

示例

`255.255.255.0`

`255.255.248.0`
 a| 
如果指定了grid network_IP且grid network_config = static"、则此字段为必需字段。

否则为可选。

|===


==== grid_network_mtu

[cols="4a,2a"]
|===
| 价值 | 名称 


 a| 
网格网络上此节点的最大传输单元（ MTU ）。如果grid network_config = dhcp、请勿指定。如果指定，则此值必须介于 1280 和 9216 之间。如果省略，则使用 1500 。

如果要使用巨型帧，请将 MTU 设置为适合巨型帧的值，例如 9000 。否则，请保留默认值。

* 重要信息 * ：网络的 MTU 值必须与节点所连接的交换机端口上配置的值匹配。否则，可能会发生网络性能问题或数据包丢失。

* 重要信息 * ：为获得最佳网络性能，应在所有节点的网格网络接口上配置类似的 MTU 值。如果网格网络在各个节点上的 MTU 设置有明显差异，则会触发 * 网格网络 MTU 不匹配 * 警报。并非所有网络类型的MTU值都必须相同。

示例

`1500`

`8192`
 a| 
可选

|===


==== grid_network_target

[cols="4a,2a"]
|===
| 价值 | 名称 


 a| 
StorageGRID 节点要用于网格网络访问的主机设备的名称。仅支持网络接口名称。通常，您使用的接口名称与为 admin_network_target 或 client_network_target 指定的接口名称不同。

*注意*：不要使用绑定或网桥设备作为网络目标。可以在绑定设备上配置 VLAN （或其他虚拟接口），也可以使用网桥和虚拟以太网（ veth ）对。

示例

`bond0.1001`

`ens192`
 a| 
必填

|===


==== grid_network_target_type

[cols="4a,2a"]
|===
| 价值 | 名称 


 a| 
interface (这是唯一支持的值。)
 a| 
可选

|===


==== grid_network_target_type_interface_clone_MAC

[cols="4a,2a"]
|===
| 价值 | 名称 


 a| 
判断对错

将密钥值设置为 "true" ，以便对 StorageGRID 容器进行发生原因 处理，以使用网格网络上主机目标接口的 MAC 地址。

* 最佳实践： * 在需要混杂模式的网络中，请改用 grid_network_target_type_interface_clone_MAC 密钥。

有关 MAC 克隆的详细信息，请参见：

* link:../rhel/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["MAC地址克隆的注意事项和建议(Red Hat Enterprise Linux)"]
* link:../ubuntu/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["MAC 地址克隆（ Ubuntu 或 Debian ）的注意事项和建议"]

 a| 
最佳实践

|===


=== 安装密码密钥(临时)



==== Custom_Temporal_password_Hash

[cols="4a,2a"]
|===
| 价值 | 名称 


 a| 
对于主管理节点、请在安装期间为StorageGRID安装API设置默认临时密码。

*注意*：仅在主管理节点上设置安装密码。如果您尝试在其他节点类型上设置密码、则验证节点配置文件将失败。

安装完成后、设置此值不起作用。

如果省略此密钥、则默认情况下不会设置任何临时密码。或者、您也可以使用StorageGRID安装API设置临时密码。

必须为 `crypt()`SHA-512密码哈希、其格式至少为8个字符、并且 `$6$<salt>$<password hash>`不超过32个字符。

可以使用命令行界面工具(例如SHA-512模式下的命令)生成此哈希 `openssl passwd`。
 a| 
最佳实践

|===


=== 接口密钥



==== interface_target_nnnnnn

[cols="4a,2a"]
|===
| 价值 | 名称 


 a| 
要添加到此节点的额外接口的名称和可选问题描述 。您可以向每个节点添加多个额外接口。

对于_nnnn_、请为要添加的每个interface_target条目指定一个唯一编号。

对于此值，请指定裸机主机上物理接口的名称。然后，也可以添加一个逗号并提供接口的问题描述 ，该接口将显示在 "VLAN interfaces" 页面和 "HA Groups" 页面上。

示例： `INTERFACE_TARGET_0001=ens256, Trunk`

如果添加中继接口，则必须在 StorageGRID 中配置 VLAN 接口。如果添加访问接口、则可以将该接口直接添加到HA组；无需配置VLAN接口。
 a| 
可选

|===


=== 最大RAM密钥



==== 最大 RAM

[cols="4a,2a"]
|===
| 价值 | 名称 


 a| 
此节点允许使用的最大 RAM 量。如果省略此密钥，则节点不存在内存限制。在为生产级节点设置此字段时，请指定一个值，该值应至少比系统 RAM 总量少 24 GB ，并且要少 16 到 32 GB 。

* 注 * ： RAM 值会影响节点的实际元数据预留空间。请参见link:../admin/managing-object-metadata-storage.html["什么是元数据预留空间的问题描述"]。

此字段的格式为 `_numberunit_`，其中 `_unit_`可以是 `b`、、 `k` `m`或 `g`。

示例

`24g`

`38654705664b`

* 注 * ：如果要使用此选项，必须为内存 cgroups 启用内核支持。
 a| 
可选

|===


=== 节点类型密钥



==== node_type

[cols="4a,2a"]
|===
| 价值 | 名称 


 a| 
节点类型：

* VM_Admin_Node
* VM_Storage_Node
* VM_Archive_Node
* VM_API_Gateway

 a| 
必填

|===


==== storage_type

[cols="4a,2a"]
|===
| 价值 | 名称 


 a| 
定义存储节点包含的对象类型。有关详细信息，请参见 link:../primer/what-storage-node-is.html#types-of-storage-nodes["存储节点的类型"]。只有节点类型为VM_Storage_Node的节点才需要此密钥；请勿为其他节点类型指定此密钥。存储类型：

* 综合
* 数据
* 元数据


*注意*：如果未指定storage_type、则存储节点类型默认设置为组合(数据和元数据)。
 a| 
可选

|===


=== 端口重新映射密钥



==== port_remap

[cols="4a,2a"]
|===
| 价值 | 名称 


 a| 
重新映射节点用于内部网格节点通信或外部通信的任何端口。如果企业网络策略限制StorageGRID使用的一个或多个端口，则需要重新映射端口，如或中所述link:../network/internal-grid-node-communications.html["内部网格节点通信"]link:../network/external-communications.html["外部通信"]。

*重要*：不要重新映射计划用于配置负载平衡器端点的端口。

* 注意 * ：如果仅设置 port_remap ，则指定的映射将同时用于入站和出站通信。如果同时指定 port_remap_inbound ， port_remap 将仅应用于出站通信。

使用的格式为： `_network type_/_protocol_/_default port used by grid node_/_new port_`，其中 `_network type_`是网格、管理员或客户端， `_protocol_`是TCP或UDP。

示例： `PORT_REMAP = client/tcp/18082/443`

您还可以使用逗号分隔列表重新映射多个端口。

示例： `PORT_REMAP = client/tcp/18082/443, client/tcp/18083/80`
 a| 
可选

|===


==== port_remap_inbound

[cols="4a,2a"]
|===
| 价值 | 名称 


 a| 
将入站通信重新映射到指定端口。如果指定port_remap_inbound、但未指定port_remap值、则端口的出站通信将保持不变。

*重要*：不要重新映射计划用于配置负载平衡器端点的端口。

使用的格式为： `_network type_/_protocol_/_remapped port_/_default port used by grid node_`，其中 `_network type_`是网格、管理员或客户端， `_protocol_`是TCP或UDP。

示例： `PORT_REMAP_INBOUND = grid/tcp/3022/22`

您还可以使用逗号分隔列表重新映射多个入站端口。

示例： `PORT_REMAP_INBOUND = grid/tcp/3022/22, admin/tcp/3022/22`
 a| 
可选

|===