= 
:allow-uri-read: 


[role="tabbed-block"]
====
.复制的数据
--
* 要获取复制的修复的估计完成百分比、请将选项添加到re修复 `show-replicated-repair-status` 数据命令中。
+
`repair-data show-replicated-repair-status`

* 要确定修复是否已完成，请执行以下操作：
+
.. 选择 * 节点 * > * 正在修复的存储节点 _* > * ILM * 。
.. 查看 " 评估 " 部分中的属性。修复完成后， * 正在等待 - 全部 * 属性指示 0 个对象。


* 要更详细地监控修复，请执行以下操作：
+
.. 选择 * 节点 * 。
.. 选择 * 网格名称 _* > * ILM * 。
.. 将光标置于ILM队列图上方可查看*扫描速率(对象数/秒)*属性的值、即网格中对象为ILM进行扫描和排队的速率。
.. 在ILM Queue部分中、查看以下属性：
+
*** *扫描期限-估计*：完成对所有对象的完整ILM扫描的估计时间。
+
完全扫描并不能保证ILM已应用于所有对象。

*** *已尝试修复*：已尝试对复制数据执行的对象修复操作的总数。每当存储节点尝试修复高风险对象时，此计数都会递增。如果网格繁忙，高风险 ILM 修复会优先处理。
+
如果修复后复制失败，则同一对象修复可能会再次增加。+在监控存储节点卷恢复进度时、这些属性非常有用。如果尝试的维修次数停止增加、并且已完成完全扫描、则修复可能已完成。



.. 或者，提交和 `storagegrid_ilm_repairs_attempted`的Prometheus查询 `storagegrid_ilm_scan_period_estimated_minutes`。




--
.纠删编码(EC)数据
--
要监控纠删编码数据的修复情况，并重试任何可能失败的请求：

. 确定经过纠删编码的数据修复的状态：
+
** 选择 * 支持 * > * 工具 * > * 指标 * 以查看当前作业的估计完成时间和完成百分比。然后，在 Grafana 部分中选择 * EC Overview* 。查看 * 网格 EC 作业预计完成时间 * 和 * 网格 EC 作业已完成百分比 * 信息板。
** 使用此命令可查看特定操作的状态 `repair-data`：
+
`repair-data show-ec-repair-status --repair-id repair ID`

** 使用此命令可列出所有修复：
+
`repair-data show-ec-repair-status`

+
输出将列出所有先前和当前正在运行的修复的信息，包括 `repair ID`。



. 如果输出显示修复操作失败、请使用 `--repair-id`选项重试修复。
+
此命令使用修复ID 6949309319275667690重试失败的节点修复：

+
`repair-data start-ec-node-repair --repair-id 6949309319275667690`

+
此命令使用修复ID 6949309319275667690重试失败的卷修复：

+
`repair-data start-ec-volume-repair --repair-id 6949309319275667690`



--
====