= 启用了 S3 对象锁定的存储分段的要求
:allow-uri-read: 




== 启用了 S3 对象锁定的存储分段的要求

* 如果为 StorageGRID 系统启用了全局 S3 对象锁定设置，则可以使用租户管理器，租户管理 API 或 S3 REST API 创建启用了 S3 对象锁定的分段。
* 如果您计划使用 S3 对象锁定，则必须在创建存储分段时启用 S3 对象锁定。您不能为现有存储分段启用S3对象锁定。
* 为存储分段启用 S3 对象锁定后， StorageGRID 会自动为该存储分段启用版本控制。您不能禁用存储分段的S3对象锁定或暂停版本控制。
* 您也可以使用租户管理器、租户管理API或S3 REST API为每个存储分段指定默认保留模式和保留期限。存储分段的默认保留设置仅适用于添加到存储分段中但没有自己的保留设置的新对象。您可以通过在上传每个对象版本时为其指定保留模式和保留截止日期来覆盖这些默认设置。
* 启用了S3对象锁定的分段支持分段生命周期配置。
* 启用了 S3 对象锁定的存储分段不支持 CloudMirror 复制。




== 启用了 S3 对象锁定的分段中的对象的要求

* 要保护对象版本、您可以为存储分段指定默认保留设置、也可以为每个对象版本指定保留设置。可以使用S3客户端应用程序或S3 REST API指定对象级保留设置。
* 保留设置适用于各个对象版本。对象版本可以同时具有保留截止日期和合法保留设置，但不能具有其他设置，或者两者均不具有。为对象指定保留日期或合法保留设置仅保护请求中指定的版本。您可以创建新版本的对象，而先前版本的对象仍保持锁定状态。




== 启用了 S3 对象锁定的存储分段中的对象生命周期

在启用了S3对象锁定的情况下保存在存储分段中的每个对象都会经历以下阶段：

. * 对象载入 *
+
将对象版本添加到启用了S3对象锁定的存储分段时、将按如下所示应用保留设置：

+
** 如果为对象指定了保留设置、则会应用对象级别设置。系统将忽略任何默认存储分段设置。
** 如果没有为对象指定保留设置、则会应用默认存储分段设置(如果存在)。
** 如果没有为对象或存储分段指定保留设置、则对象不受S3对象锁定保护。


+
如果应用了保留设置、则对象和任何S3用户定义的元数据都会受到保护。

. *对象保留和删除*
+
StorageGRID 会在指定的保留期限内存储每个受保护对象的多个副本。对象副本的确切数量和类型以及存储位置由活动ILM策略中的合规规则决定。是否可以在达到保留截止日期之前删除受保护对象取决于其保留模式。

+
** 如果某个对象处于合法保留状态、则无论其保留模式如何、任何人都无法删除该对象。



