---
permalink: tenant/configuring-cross-origin-resource-sharing-for-buckets-and-objects.html 
sidebar: sidebar 
keywords: how to configure cross-origin resource sharing, cors 
summary: '如果您希望S3存储分段和该存储分段中的对象可供其他域中的Web应用程序访问、则可以为该存储分段配置跨源站资源共享(CORS\)。' 
---
= 为存储桶和对象配置StorageGRID CORS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您希望S3存储分段和该存储分段中的对象可供其他域中的Web应用程序访问、则可以为该存储分段配置跨源站资源共享(CORS)。

.开始之前
* 您已使用登录到租户管理器link:../admin/web-browser-requirements.html["支持的 Web 浏览器"]。
* 对于GET CORS配置请求，您属于具有的用户组link:tenant-management-permissions.html["管理所有存储分段或查看所有存储分段权限"]。这些权限将覆盖组或存储分段策略中的权限设置。
* 对于Put CORS配置请求，您属于具有的用户组link:tenant-management-permissions.html["管理所有存储分段权限"]。此权限将覆盖组或存储分段策略中的权限设置。
* 提供对所有CORS配置请求的link:tenant-management-permissions.html["root访问权限"]访问权限。


.关于此任务
跨源资源共享（ CORS ）是一种安全机制，允许一个域中的客户端 Web 应用程序访问不同域中的资源。例如、假设您使用名为的S3存储分段 `Images`来存储图形。通过为存储分段配置CORS `Images`，您可以允许该存储分段中的图像显示在网站上 `+http://www.example.com+`。



== 为存储分段启用CORS

.步骤
. 使用文本编辑器创建所需的XML。此示例显示了用于为 S3 存储分段启用 CORS 的 XML 。具体而言：
+
** 允许任何域向存储分段发送GET请求
** 仅允许 `+http://www.example.com+`域发送GET、POST和DELETE请求
** 允许所有请求标头
+
[listing]
----
<CORSConfiguration
    xmlns="http://s3.amazonaws.com/doc/2020-10-22/">
    <CORSRule>
        <AllowedOrigin>*</AllowedOrigin>
        <AllowedMethod>GET</AllowedMethod>
        <AllowedHeader>*</AllowedHeader>
    </CORSRule>
    <CORSRule>
        <AllowedOrigin>http://www.example.com</AllowedOrigin>
        <AllowedMethod>GET</AllowedMethod>
        <AllowedMethod>POST</AllowedMethod>
        <AllowedMethod>DELETE</AllowedMethod>
        <AllowedHeader>*</AllowedHeader>
    </CORSRule>
</CORSConfiguration>
----
+
有关CORS配置XML的详细信息，请参见 http://docs.aws.amazon.com/AmazonS3/latest/dev/Welcome.html["Amazon Web Services (AWS)文档：《Amazon Simple Storage Service用户指南》"^]。



. 从信息板中选择*查看存储分段*，或选择*存储(S3)*>*存储分段*。
. 从表中选择分段名称。
+
此时将显示存储分段详细信息页面。

. 从*存储分段访问*选项卡中，选择*跨源资源共享(CORS)*可接触式。
. 选中*启用CORS*复选框。
. 将CORS配置XML粘贴到文本框中。
. 选择 * 保存更改 * 。




== 修改CORS设置

.步骤
. 更新文本框中的CORS配置XML，或选择*Clear*重新开始。
. 选择 * 保存更改 * 。




== 禁用CORS设置

.步骤
. 清除*启用CORS*复选框。
. 选择 * 保存更改 * 。


.相关信息
link:../admin/enable-cross-origin-resource-sharing-for-management-interface.html["为管理接口配置StorageGRID CORS"]
