---
permalink: tenant/creating-another-users-s3-access-keys.html 
sidebar: sidebar 
keywords: how to create other user S3 access key 
summary: 如果您使用的是 S3 租户，并且您拥有相应的权限，则可以为其他用户创建 S3 访问密钥，例如需要访问存储分段和对象的应用程序。 
---
= 创建其他用户的 S3 访问密钥
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您使用的是 S3 租户，并且您拥有相应的权限，则可以为其他用户创建 S3 访问密钥，例如需要访问存储分段和对象的应用程序。

.开始之前
* 您已使用登录到租户管理器link:../admin/web-browser-requirements.html["支持的 Web 浏览器"]。
* 您属于具有的用户组link:tenant-management-permissions.html["root访问权限"]。


.关于此任务
您可以为其他用户创建一个或多个 S3 访问密钥，以便他们可以为其租户帐户创建和管理存储分段。创建新的访问密钥后，使用新的访问密钥 ID 和机密访问密钥更新应用程序。为了安全起见、请不要创建超出用户需要的密钥、并删除未使用的密钥。如果只有一个密钥，并且该密钥即将到期，请在旧密钥到期之前创建一个新密钥，然后删除旧密钥。

每个密钥可以有特定的到期时间，也可以无到期时间。请遵循以下到期时间准则：

* 设置密钥的到期时间，以将用户的访问限制为特定时间段。如果访问密钥 ID 和机密访问密钥意外暴露，则设置较短的到期时间有助于降低风险。过期密钥将自动删除。
* 如果环境中的安全风险较低、并且您不需要定期创建新密钥、则不必设置密钥的到期时间。如果您稍后决定创建新密钥，请手动删除旧密钥。



CAUTION: 可以使用租户管理器中为用户显示的访问密钥 ID 和机密访问密钥来访问属于用户的 S3 存储分段和对象。因此，请像使用密码一样保护访问密钥。定期轮换访问密钥，从帐户中删除任何未使用的密钥，并且切勿与其他用户共享这些密钥。

.步骤
. 选择 * 访问管理 * > * 用户 * 。
. 选择要管理其 S3 访问密钥的用户。
+
此时将显示用户详细信息页面。

. 选择 * 访问密钥 * ，然后选择 * 创建密钥 * 。
. 执行以下操作之一：
+
** 选择*不设置到期时间*以创建不到期的密钥。（默认）
** 选择 * 设置到期时间 * ，然后设置到期日期和时间。
+

NOTE: 到期日期最多可以是自当前日期起五年。到期时间至少可以是当前时间之后的一分钟。



. 选择 * 创建访问密钥 * 。
+
此时将显示 Download access key 对话框，其中列出了访问密钥 ID 和机密访问密钥。

. 将访问密钥 ID 和机密访问密钥复制到安全位置，或者选择 * 下载 .csv * 以保存包含访问密钥 ID 和机密访问密钥的电子表格文件。
+

CAUTION: 复制或下载此信息之前、请勿关闭此对话框。关闭对话框后、您无法复制或下载密钥。

. 选择 * 完成 * 。
+
新密钥将列在用户详细信息页面的访问密钥选项卡中。

. 如果您的租户帐户具有*使用网格联合连接*权限、也可以使用租户管理API手动将S3访问密钥从源网格上的租户克隆到目标网格上的租户。请参阅。 link:grid-federation-clone-keys-with-api.html["使用API克隆S3访问密钥"]

