---
permalink: tenant/creating-s3-bucket.html 
sidebar: sidebar 
keywords: how to create S3 bucket 
summary: 您可以使用租户管理器为对象数据创建 S3 分段。 
---
= 创建 S3 存储区。
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用租户管理器为对象数据创建 S3 分段。

.开始之前
* 您已使用登录到租户管理器link:../admin/web-browser-requirements.html["支持的 Web 浏览器"]。
* 您属于具有root访问权限或管理所有存储分段的用户组link:tenant-management-permissions.html["权限"]。这些权限将覆盖组或存储分段策略中的权限设置。
+

NOTE: 可以通过授予设置或修改分段或对象的S3对象锁定属性的权限link:../s3/bucket-and-group-access-policies.html["存储分段策略或组策略"]。

* 如果您计划为存储分段启用S3对象锁定、则网格管理员已为StorageGRID 系统启用全局S3对象锁定设置、并且您已查看S3对象锁定分段和对象的要求。
* 如果每个租户具有5、000个分段、则网格中的每个存储节点至少具有64 GB RAM。
+

NOTE: 每个网格最多可以包含100、000个分段。





== 访问向导

.步骤
. 从信息板中选择*查看存储分段*，或选择*存储(S3)*>*存储分段*。
. 选择 * 创建存储分段 * 。




== 输入详细信息

.步骤
. 输入存储分段的详细信息。
+
[cols="1a,3a"]
|===
| 字段 | 说明 


 a| 
Bucket Name
 a| 
符合以下规则的存储分段名称：

** 每个 StorageGRID 系统必须是唯一的（而不仅仅是租户帐户中的唯一）。
** 必须符合 DNS 要求。
** 必须包含至少3个且不超过63个字符。
** 每个标签必须以小写字母或数字开头和结尾，并且只能使用小写字母，数字和连字符。
** 在虚拟托管模式请求中不得包含句点。句点会在验证服务器通配符证书时出现发生原因 问题。


有关详细信息，请参见 https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html["有关存储分段命名规则的 Amazon Web Services （ AWS ）文档"^]。

*注意*:创建存储分段后不能更改存储分段名称。



 a| 
区域
 a| 
存储分段的区域。

StorageGRID 管理员负责管理可用的区域。存储分段的区域可能会影响应用于对象的数据保护策略。默认情况下、所有存储分段都会在区域中创建 `us-east-1`。

*注意*：创建存储分段后无法更改区域。

|===
. 选择 * 继续 * 。




== 管理设置

.步骤
. （可选）为存储分段启用对象版本控制。
+
如果要将每个对象的每个版本存储在此存储分段中，请启用对象版本控制。然后，您可以根据需要检索对象的先前版本。如果要使用分段进行跨网格复制、则必须启用对象版本控制。

. 如果启用了全局S3对象锁定设置、则可以选择为存储分段启用S3对象锁定、以便使用一次写入、多次读取(WORM)模型存储对象。
+
只有在需要将对象保留固定时间(例如为了满足特定法规要求)时、才为存储分段启用S3对象锁定。S3对象锁定是一种永久设置、可帮助您防止在固定时间内或无限期删除或覆盖对象。

+

CAUTION: 为存储分段启用S3对象锁定设置后、便无法将其禁用。具有正确权限的任何人都可以向此存储分段添加无法更改的对象。您可能无法删除这些对象或存储分段本身。

+
如果为存储分段启用 S3 对象锁定，则会自动启用存储分段版本控制。

. 如果选择了*启用S3对象锁定*，则可以选择为此存储分段启用*默认保留*。
+

NOTE: 网格管理员必须授予您访问的权限link:../tenant/using-s3-object-lock.html["使用S3对象锁定的特定功能"]。

+
启用*默认保留*后，添加到存储分段的新对象将自动受到保护，不会被删除或覆盖。*默认保留*设置不适用于具有自己保留期限的对象。

+
.. 如果启用了*默认保留*，请为存储分段指定*默认保留模式*。
+
[cols="1a,2a"]
|===
| 默认保留模式 | 说明 


 a| 
监管
 a| 
*** 具有权限的用户 `s3:BypassGovernanceRetention`可以使用 `x-amz-bypass-governance-retention: true`请求标头绕过保留设置。
*** 这些用户可以在达到保留截止日期之前删除对象版本。
*** 这些用户可以增加、减少或删除对象的保留截止日期。




 a| 
合规性
 a| 
*** 在达到保留截止日期之前、无法删除此对象。
*** 对象的保留截止日期可以增加、但不能减少。
*** 在达到该日期之前、无法删除对象的保留截止日期。


*注意*：网格管理员必须允许您使用兼容模式。

|===
.. 如果启用了*默认保留*，请指定存储分段的*默认保留期限*。
+
*默认保留期限*表示添加到此存储分段的新对象应保留多长时间、从其被插入开始。指定一个小于或等于网格管理员设置的租户最长保留期限的值。

+
网格管理员创建租户时会设置一个_maximum _保留期限、该保留期限的值可以介于1天到100年之间。如果设置了_default_保留期限、则该保留期限不能超过为最长保留期限设置的值。如果需要、请让网格管理员增加或减少最长保留期限。



. [[Capacity－Limit]](可选)选择*启用容量限制*。
+
容量限制是指可用于此存储分段对象的最大容量。此值表示逻辑数量(对象大小)、而不是物理数量(磁盘上的大小)。

+
如果未设置限制、则此存储分段的容量为无限制。有关详细信息、请参见 link:../tenant/understanding-tenant-manager-dashboard.html#bucket-capacity-usage["容量限制使用量"] 。

. 选择 * 创建存储分段 * 。
+
此时将创建存储分段并将其添加到 " 存储分段 " 页面上的表中。

. (可选)选择*转至存储分段详细信息页面*link:viewing-s3-bucket-details.html["查看存储分段详细信息"]并执行其他配置。

