---
permalink: tenant/creating-groups-for-swift-tenant.html 
sidebar: sidebar 
keywords: how to create Swift tenant groups 
summary: 您可以通过导入联合组或创建本地组来管理 Swift 租户帐户的访问权限。至少有一个组必须具有 Swift 管理员权限，这是管理 Swift 租户帐户的容器和对象所必需的。 
---
= 为 Swift 租户创建组
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以通过导入联合组或创建本地组来管理 Swift 租户帐户的访问权限。至少有一个组必须具有 Swift 管理员权限，这是管理 Swift 租户帐户的容器和对象所必需的。


NOTE: 对Swift客户端应用程序的支持已弃用、将在未来版本中删除。

.开始之前
* 您已使用登录到租户管理器link:../admin/web-browser-requirements.html["支持的 Web 浏览器"]。
* 您属于具有的用户组link:tenant-management-permissions.html["root访问权限"]。
* 如果您计划导入联盟组，则已导入link:using-identity-federation.html["已配置身份联合"]，并且已配置的身份源中已存在联盟组。




== 访问创建组向导

.步骤
首先、访问创建组向导。

. 选择 * 访问管理 * > * 组 * 。
. 选择 * 创建组 * 。




== 选择组类型

您可以创建本地组或导入联合组。

.步骤
. 选择 * 本地组 * 选项卡以创建本地组，或者选择 * 联合组 * 选项卡以从先前配置的身份源导入组。
+
如果为 StorageGRID 系统启用了单点登录（ SSO ），则属于本地组的用户将无法登录到租户管理器，但他们可以根据组权限使用客户端应用程序管理租户的资源。

. 输入组的名称。
+
** * 本地组 * ：输入显示名称和唯一名称。您可以稍后编辑显示名称。
** * 联合组 * ：输入唯一名称。对于Active Directory、唯一名称是与属性关联的名称 `sAMAccountName`。对于OpenLDAP、唯一名称是与属性关联的名称 `uid`。


. 选择 * 继续 * 。




== 管理组权限

组权限控制用户可在租户管理器和租户管理API中执行的任务。

.步骤
. 对于*Access mode*，请选择以下选项之一：
+
** *读写*(默认)：用户可以登录到租户管理器并管理租户配置。
** * 只读 * ：用户只能查看设置和功能。他们无法在租户管理器或租户管理API中进行任何更改或执行任何操作。本地只读用户可以更改自己的密码。
+

NOTE: 如果用户属于多个组，并且任何组设置为只读，则用户将对所有选定设置和功能具有只读访问权限。



. 如果组用户需要登录到租户管理器或租户管理API、请选中* root访问*复选框。
. 选择 * 继续 * 。




== 设置Swift组策略

Swift用户需要管理员权限才能通过Swift REST API的身份验证来创建容器和导入对象。

. 如果组用户需要使用Swift REST API来管理容器和对象、请选中* Swift administrator*复选框。
. 如果要创建本地组，请选择 * 继续 * 。如果要创建联合组，请选择 * 创建组 * 和 * 完成 * 。




== 添加用户（仅限本地组）

您可以保存组而不添加用户、也可以选择添加任何已存在的本地用户。

.步骤
. 或者，为此组选择一个或多个本地用户。
+
如果尚未创建本地用户、则可以在用户页面上将此组添加到用户。请参阅。 link:../tenant/managing-local-users.html["管理本地用户"]

. 选择 * 创建组 * 和 * 完成 * 。
+
您创建的组将显示在组列表中。


