---
permalink: tenant/enabling-or-disabling-last-access-time-updates.html 
sidebar: sidebar 
keywords: how to enable or disable last access time updates 
summary: 当网格管理员为 StorageGRID 系统创建信息生命周期管理 \ （ ILM ）规则时，他们可以选择指定对象的最后访问时间来确定是否将该对象移动到其他存储位置。如果您使用的是 S3 租户，则可以通过为 S3 存储分段中的对象启用上次访问时间更新来利用此类规则。 
---
= 启用或禁用上次访问时间更新
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
当网格管理员为 StorageGRID 系统创建信息生命周期管理（ ILM ）规则时，他们可以选择指定对象的最后访问时间来确定是否将该对象移动到其他存储位置。如果您使用的是 S3 租户，则可以通过为 S3 存储分段中的对象启用上次访问时间更新来利用此类规则。

这些说明仅适用于至少包含一个使用*上次访问时间*选项作为高级筛选器或参考时间的ILM规则的StorageGRID 系统。如果您的 StorageGRID 系统不包含此类规则，则可以忽略这些说明。有关详细信息、请参见。 link:../ilm/using-last-access-time-in-ilm-rules.html["在ILM规则中使用上次访问时间"]

.开始之前
* 您已使用登录到租户管理器link:../admin/web-browser-requirements.html["支持的 Web 浏览器"]。
* 您属于具有的用户组link:tenant-management-permissions.html["管理所有分段或root访问权限"]。这些权限将覆盖组或存储分段策略中的权限设置。


.关于此任务
*上次访问时间*是ILM规则的*参考时间*放置指令的可用选项之一。通过将规则的"参考时间"设置为上次访问时间、网格管理员可以根据上次检索(读取或查看)对象的时间指定将对象放置在某些存储位置。

例如，为了确保最近查看的对象保持在较快的存储上，网格管理员可以创建一个 ILM 规则，指定以下内容：

* 过去一个月检索到的对象应保留在本地存储节点上。
* 过去一个月未检索到的对象应移至异地位置。


默认情况下，对上次访问时间的更新处于禁用状态。如果您的StorageGRID 系统包含使用*上次访问时间*选项的ILM规则、而您希望此选项应用于此存储分段中的对象、则必须为该规则中指定的S3存储分段启用上次访问时间更新。


CAUTION: 在检索对象时更新上次访问时间会降低 StorageGRID 性能，尤其是对于小型对象。

上次访问时间更新会影响性能，因为每次检索对象时， StorageGRID 都必须执行以下附加步骤：

* 使用新的时间戳更新对象
* 将对象添加到 ILM 队列，以便根据当前 ILM 规则和策略对其进行重新评估


下表汇总了禁用或启用上次访问时间时应用于存储分段中所有对象的行为。

[cols="1a,1a,1a,1a,1a"]
|===


.2+| 请求类型 2+| 禁用上次访问时间时的行为（默认） 2+| 启用上次访问时间时的行为 


| 上次访问时间是否已更新？ | 对象是否已添加到 ILM 评估队列？ | 上次访问时间是否已更新？ | 对象是否已添加到 ILM 评估队列？ 


 a| 
发出 HEAD 操作时请求检索对象的元数据
 a| 
否
 a| 
否
 a| 
否
 a| 
否



 a| 
请求检索对象，其访问控制列表或其元数据
 a| 
否
 a| 
否
 a| 
是
 a| 
是



 a| 
请求更新对象的元数据
 a| 
是
 a| 
是
 a| 
是
 a| 
是



 a| 
列出对象或对象版本的请求
 a| 
否
 a| 
否
 a| 
否
 a| 
否



 a| 
请求将对象从一个存储分段复制到另一个存储分段
 a| 
* 否，对于源副本
* 是，对于目标副本

 a| 
* 否，对于源副本
* 是，对于目标副本

 a| 
* 是，对于源副本
* 是，对于目标副本

 a| 
* 是，对于源副本
* 是，对于目标副本




 a| 
请求完成多部分上传
 a| 
是，对于已组装的对象
 a| 
是，对于已组装的对象
 a| 
是，对于已组装的对象
 a| 
是，对于已组装的对象

|===
.步骤
. 从信息板中选择*查看存储分段*，或选择*存储(S3)*>*存储分段*。
. 从表中选择分段名称。
+
此时将显示存储分段详细信息页面。

. 从*存储分段选项*选项卡中，选择*上次访问时间更新*可接触框。
. 启用或禁用上次访问时间更新。
. 选择 * 保存更改 * 。

