---
permalink: tenant/ilm-policy-tags.html 
sidebar: sidebar 
keywords: how to assign ilm policy tag to bucket 
summary: 根据对象存储要求选择要分配给存储分段的ILM策略标记。 
---
= 将ILM策略标记应用于存储分段
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
根据对象存储要求选择要应用于存储分段的ILM策略标记。

ILM策略控制对象数据的存储位置以及是否在特定时间段后将其删除。网格管理员创建ILM策略、并在使用多个活动策略时将其分配给ILM策略标记。


NOTE: 避免频繁重新分配存储分段的策略标记。否则、可能会发生性能问题。

.开始之前
* 您已使用登录到租户管理器link:../admin/web-browser-requirements.html["支持的 Web 浏览器"]。
* 您属于具有的用户组link:tenant-management-permissions.html["root访问权限、管理所有分段权限或查看所有分段权限"]。这些权限会覆盖组或存储分段策略中的权限设置。


.步骤
. 从信息板中选择*查看存储分段*，或选择*存储(S3)*>*存储分段*。
+
此时将显示"分段"页面。您可以根据需要按任何列对信息进行排序，也可以在列表中向前和向后翻页。

. 选择要将ILM策略标记分配到的存储分段的名称。
+
您还可以更改已分配标记的存储分段的ILM策略标记分配。

+

NOTE: 显示的对象计数和已用空间值为估计值。这些估计值受载入时间，网络连接和节点状态的影响。如果分段启用了版本控制，则删除的对象版本将包含在对象计数中。

. 在存储分段选项选项卡中、展开ILM策略标记可展开框。只有当网格管理员启用了自定义策略标记的使用时、才会显示此可风框。
. 阅读每个策略标记的问题描述以确定应将哪个标记应用于存储分段。
+

CAUTION: 更改存储分段的ILM策略标记将触发存储分段中所有对象的ILM重新评估。如果新策略将对象保留一段有限的时间、则较早的对象将被删除。

. 选择要分配给存储分段的标记对应的单选按钮。
. 选择 * 保存更改 * 。此时将使用ILM策略标记名称的密钥和值在此存储分段上设置一个新的S3存储分段标记 `NTAP-SG-ILM-BUCKET-TAG`。
+

CAUTION: 确保S3应用程序不会意外覆盖或删除新存储分段标记。如果在向存储分段应用新标记集时省略此标记、则存储分段中的对象将还原为根据默认ILM策略进行评估。

+

CAUTION: 仅使用已验证ILM策略标记的租户管理器或租户管理器API设置和修改ILM策略标记。请勿使用S3 PutBucketTag API或S3 DeleteBucketTag API修改 `NTAP-SG-ILM-BUCKET-TAG`ILM策略标记。

+

NOTE: 在使用新ILM策略重新评估对象时、更改分配给存储分段的策略标记会暂时影响性能。


