---
permalink: tenant/manage-branch-buckets.html 
sidebar: sidebar 
keywords: how to create branch bucket 
summary: 使用租户管理器创建和查看分支存储桶的详细信息。 
---
= 管理分支存储桶
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用租户管理器创建和查看分支存储桶的详细信息。

.开始之前
* 您已使用link:../admin/web-browser-requirements.html["支持的 Web 浏览器"]。
* 您属于具有 Root 访问权限的用户组，或者link:tenant-management-permissions.html["管理所有存储分段权限"]。这些权限将覆盖组或存储桶策略中的权限设置。
* 您要从中创建分支的基本存储桶具有link:../tenant/changing-bucket-versioning.html["已启用版本控制"]。
* 您是基本存储桶的所有者。


.关于此任务
请注意分支存储桶的以下信息：

* 设置存储桶或对象的 S3 对象锁定属性的权限可以通过以下方式授予link:../s3/use-access-policies.html["存储分段策略或组策略"]。
* 如果您暂停对基本存储桶进行版本控制，则基本存储桶的内容将不再在其分支存储桶中可见。



CAUTION: 配置并创建分支存储桶后，您无法更改该配置。



== 创建分支存储桶

.步骤
. 从信息板中选择*查看存储分段*，或选择*存储(S3)*>*存储分段*。
. 选择要从中创建分支的存储桶（“基本存储桶”）。
. 在存储桶详情页面，选择*分支* > *创建分支存储桶*。
+
如果基本存储桶未启用版本控制，则“创建分支存储桶”按钮将被禁用。





== 输入详细信息

.步骤
. 输入分支存储桶的详细信息。
+
[cols="1a,3a"]
|===
| 字段 | 说明 


 a| 
分支存储桶名称
 a| 
符合以下规则的分支存储桶的名称：

** 每个 StorageGRID 系统必须是唯一的（而不仅仅是租户帐户中的唯一）。
** 必须符合 DNS 要求。
** 必须包含至少3个且不超过63个字符。
** 每个标签必须以小写字母或数字开头和结尾，并且只能使用小写字母，数字和连字符。
** 在虚拟托管模式请求中不得包含句点。句点会在验证服务器通配符证书时出现发生原因 问题。


有关详细信息，请参见 https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html["有关存储分段命名规则的 Amazon Web Services （ AWS ）文档"^]。

*注意*：创建分支存储桶后，您无法更改名称。



 a| 
区域（无法修改分支存储桶）
 a| 
分支存储桶的区域。

分支存储桶的区域必须与基本存储桶的区域匹配，因此该字段对于分支存储桶是禁用的。



 a| 
时间之前
 a| 
可从分支存储桶访问在基础存储桶中创建的对象版本的截止时间。分支存储桶提供对早于之前时间创建的对象版本的访问。

之前时间必须是已经过去的日期和时间。它不能是未来的日期。



 a| 
分支桶类型
 a| 
** *读写*：您可以在分支存储桶中添加或删除对象或对象版本。
** *只读*：您不能修改分支存储桶中的对象。


*注意*：仅当分支存储桶为空时，您才可以将分支存储桶类型设置为只读。如果现有分支存储桶的类型设置为读写，而您尚未写入，则可以将类型更改为只读。

|===
. 选择 * 继续 * 。




== 管理对象设置（可选）

分支存储桶的对象设置不会影响基础存储桶中的对象版本。

.步骤
. 如果启用了全局 S3 对象锁定设置，则可以选择为分支存储桶启用 S3 对象锁定。要启用 S3 对象锁，分支存储桶必须是读写存储桶。
+
仅当您需要将对象保留一段固定的时间（例如，为了满足某些监管要求）时，才为分支存储桶启用 S3 对象锁定。  S3 对象锁定是一种永久性设置，可帮助您防止对象在固定时间内或无限期内被删除或覆盖。

+

CAUTION: 一旦为存储桶启用 S3 对象锁定设置，就无法禁用它。任何拥有正确权限的人都可以将对象添加到无法更改的分支存储桶中。您可能无法删除这些对象或分支存储桶本身。

. 如果您选择了“启用 S3 对象锁定”，则可以选择为分支存储桶启用“默认保留”。
+

NOTE: 网格管理员必须授予您访问的权限link:../tenant/using-s3-object-lock.html["使用S3对象锁定的特定功能"]。

+
当启用*默认保留*时，添加到分支存储桶的新对象将自动受到保护，免遭删除或覆盖。  *默认保留*设置不适用于具有自己的保留期的对象。

+
.. 如果启用了*默认保留*，请为分支存储桶指定*默认保留模式*。
+
[cols="1a,2a"]
|===
| 默认保留模式 | 说明 


 a| 
监管
 a| 
*** 具有权限的用户 `s3:BypassGovernanceRetention`可以使用 `x-amz-bypass-governance-retention: true`请求标头绕过保留设置。
*** 这些用户可以在达到保留截止日期之前删除对象版本。
*** 这些用户可以增加、减少或删除对象的保留截止日期。




 a| 
合规性
 a| 
*** 在达到保留截止日期之前、无法删除此对象。
*** 对象的保留截止日期可以增加、但不能减少。
*** 在达到该日期之前、无法删除对象的保留截止日期。


*注意*：网格管理员必须允许您使用兼容模式。

|===
.. 如果启用了*默认保留*，请指定分支存储桶的*默认保留期*。
+
*默认保留期*表示从提取新对象开始，添加到分支存储桶中的新对象应保留多长时间。指定一个小于或等于网格管理员设置的租户最大保留期的值。

+
网格管理员创建租户时会设置一个_maximum _保留期限、该保留期限的值可以介于1天到100年之间。如果设置了_default_保留期限、则该保留期限不能超过为最长保留期限设置的值。如果需要、请让网格管理员增加或减少最长保留期限。



. 或者，选择“启用容量限制”。
+
容量限制是分支桶可用的最大容量。该值代表逻辑量（对象大小），而不是物理量（磁盘上的大小）。

+
如果没有设置限制，则分支桶的容量是无限的。请参阅link:../tenant/understanding-tenant-manager-dashboard.html#bucket-capacity-usage["容量限制使用量"]了解更多信息。

+

NOTE: 此设置仅适用于直接提取到分支存储桶中的对象，而不适用于通过分支存储桶从基础存储桶中可见的对象。

. 或者，选择“启用对象计数限制”。
+
对象计数限制是分支存储桶可以包含的最大对象数。该值代表逻辑数量（对象计数）。如果没有设置限制，则对象数量不受限制。

+

NOTE: 此设置仅适用于直接提取到分支存储桶中的对象，而不适用于通过分支存储桶从基础存储桶中可见的对象。

. 选择 * 创建存储分段 * 。
+
分支存储桶已创建并添加到“存储桶”页面上的表中。

. 或者，选择“转到存储桶详细信息页面”link:viewing-s3-bucket-details.html["查看分支存储桶详细信息"]并执行额外的配置。
+
在 Bucket 详情页面，对于只读 Bucket，一些与修改对象相关的配置选项被禁用。


