---
permalink: tenant/manage-branch-buckets.html 
sidebar: sidebar 
keywords: how to create branch bucket 
summary: 通过分支分段、可以访问分段中在某一特定时间存在的对象、前提是这些对象仍位于分段中。使用租户管理器创建和查看分支分段。 
---
= 管理分支存储分段
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通过分支分段、可以访问分段中在某一特定时间存在的对象、前提是这些对象仍位于分段中。使用租户管理器创建和查看分支分段。

分支分段可用于访问受保护的数据、但不用作备份。要继续保护数据、请在基本存储分段上使用以下功能：

* link:../tenant/using-s3-object-lock.html["S3 对象锁定"]
* link:../admin/grid-federation-what-is-cross-grid-replication.html["跨网格复制"]用于基本铲斗
* link:../tenant/manage-bucket-policy.html["存储分段策略"]用于清理旧对象版本的版本分段


.关于此任务
您可以从现有存储分段创建分支存储分段。创建分支存储分段后、创建该存储分段的原始存储分段称为基本存储分段。此外、您还可以从其他分支存储分段创建分支存储分段。在基本分段上执行操作时、分支分段上的结果取决于所创建的操作和分支分段的类型。

您可以使用分支存储分段删除损坏的对象、方法是从发生损坏之前的某个时间点创建分支存储分段、然后将应用程序指向分支存储分段、而不是指向包含损坏对象的基本存储分段。


CAUTION: 分支存储分段不会用作备份、而是提供对受保护数据的访问。您必须继续使用link:../ilm/managing-objects-with-s3-object-lock.html["S3 对象锁定"]或link:../admin/grid-federation-what-is-cross-grid-replication.html["跨网格复制"]来保护数据。

分支分段不支持跨网格复制。

.开始之前
* 您已使用登录到租户管理器link:../admin/web-browser-requirements.html["支持的 Web 浏览器"]。
* 您属于具有root访问权限或管理所有存储分段的用户组link:tenant-management-permissions.html["权限"]。这些权限将覆盖组或存储分段策略中的权限设置。
* 要从中创建分支的基本存储分段具有link:../tenant/changing-bucket-versioning.html["已启用版本控制"]。
* 您是基础存储分段的所有者。
+

NOTE: 可以通过授予设置或修改分段或对象的S3对象锁定属性的权限link:../s3/bucket-and-group-access-policies.html["存储分段策略或组策略"]。





== 创建分支存储分段

.步骤
. 从信息板中选择*查看存储分段*，或选择*存储(S3)*>*存储分段*。
. 选择要从中创建分支的存储分段("基本存储分段")。
. 在存储分段详细信息页面上、选择*分支*>*创建分支存储分段*。
+
如果基本分段未启用版本控制，则禁用*创建分支分段*按钮。





== 输入详细信息

.步骤
. 输入分支存储分段的详细信息。
+
[cols="1a,3a"]
|===
| 字段 | 说明 


 a| 
分支分段名称
 a| 
符合以下规则的分支分段名称：

** 每个 StorageGRID 系统必须是唯一的（而不仅仅是租户帐户中的唯一）。
** 必须符合 DNS 要求。
** 必须包含至少3个且不超过63个字符。
** 每个标签必须以小写字母或数字开头和结尾，并且只能使用小写字母，数字和连字符。
** 在虚拟托管模式请求中不得包含句点。句点会在验证服务器通配符证书时出现发生原因 问题。


有关详细信息，请参见 https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html["有关存储分段命名规则的 Amazon Web Services （ AWS ）文档"^]。

*注意*:创建分支分段后不能更改名称。



 a| 
区域(无法修改分支分段)
 a| 
分支存储分段的区域。

分支存储分段的区域必须与基础存储分段的区域匹配、因此对于分支存储分段、此字段处于禁用状态。



 a| 
提前
 a| 
要从分支分段访问在基本分段中创建的对象版本的截止时间。通过分支分段、您可以访问比以前创建的对象版本。



 a| 
分支存储分段类型
 a| 
** *读写*：可以在分支分段中添加或删除对象或对象版本。
** *只读*：不能修改分支分段中的对象。


|===
. 选择 * 继续 * 。




== 管理设置

分支分段的设置不会影响基本分段中的对象版本。

.步骤
. 如果启用了全局S3对象锁定设置、则可以选择为分支分段启用S3对象锁定。要启用S3对象锁定、分支分段必须是读写分段。
+
只有在需要将对象保留固定时间(例如为了满足特定法规要求)时、才为分支分段启用S3对象锁定。S3对象锁定是一种永久设置、可帮助您防止在固定时间内或无限期删除或覆盖对象。

+

CAUTION: 为存储分段启用S3对象锁定设置后、便无法将其禁用。具有正确权限的任何人都可以向分支存储分段添加无法更改的对象。您可能无法删除这些对象或分支存储分段本身。

. 如果选择了*启用S3对象锁定*，则可以选择为分支分段启用*默认保留*。
+

NOTE: 网格管理员必须授予您访问的权限link:../tenant/using-s3-object-lock.html["使用S3对象锁定的特定功能"]。

+
启用*默认保留*后，添加到分支存储分段的新对象将自动受到保护，不会被删除或覆盖。*默认保留*设置不适用于具有自己保留期限的对象。

+
.. 如果启用了*默认保留*，请为分支存储分段指定*默认保留模式*。
+
[cols="1a,2a"]
|===
| 默认保留模式 | 说明 


 a| 
监管
 a| 
*** 具有权限的用户 `s3:BypassGovernanceRetention`可以使用 `x-amz-bypass-governance-retention: true`请求标头绕过保留设置。
*** 这些用户可以在达到保留截止日期之前删除对象版本。
*** 这些用户可以增加、减少或删除对象的保留截止日期。




 a| 
合规性
 a| 
*** 在达到保留截止日期之前、无法删除此对象。
*** 对象的保留截止日期可以增加、但不能减少。
*** 在达到该日期之前、无法删除对象的保留截止日期。


*注意*：网格管理员必须允许您使用兼容模式。

|===
.. 如果启用了*默认保留*，请为分支存储分段指定*默认保留期限*。
+
*默认保留期限*表示添加到分支存储分段的新对象应保留多长时间、从其被插入开始。指定一个小于或等于网格管理员设置的租户最长保留期限的值。

+
网格管理员创建租户时会设置一个_maximum _保留期限、该保留期限的值可以介于1天到100年之间。如果设置了_default_保留期限、则该保留期限不能超过为最长保留期限设置的值。如果需要、请让网格管理员增加或减少最长保留期限。



. [[Capacity－Limit]](可选)选择*启用容量限制*。
+
容量限制是指分支存储分段的最大可用容量。此值表示逻辑数量(对象大小)、而不是物理数量(磁盘上的大小)。

+
如果未设置任何限制、则分支存储分段的容量为无限制。有关详细信息、请参见 link:../tenant/understanding-tenant-manager-dashboard.html#bucket-capacity-usage["容量限制使用量"] 。

+

NOTE: 此设置仅适用于直接插入分支存储分段的对象、而不适用于从基础存储分段通过分支存储分段可见的对象。

. (可选)选择*启用对象计数限制*。
+
对象计数限制是指分支分段可以包含的最大对象数。此值表示逻辑数量(对象计数)。如果未设置任何限制、则对象计数不受限制。

+

NOTE: 此设置仅适用于直接插入分支存储分段的对象、而不适用于从基础存储分段通过分支存储分段可见的对象。

. 选择 * 创建存储分段 * 。
+
此时将创建分支分段并将其添加到"分段"页面上的表中。

. (可选)选择*转至存储分段详细信息页面*link:viewing-s3-bucket-details.html["查看分支存储分段详细信息"]并执行其他配置。
+
在存储分段详细信息页面上、与修改对象相关的某些配置选项已对只读存储分段禁用。


