---
permalink: tenant/tenant-management-permissions.html 
sidebar: sidebar 
keywords: tenant management permissions 
summary: 在创建租户组之前，请考虑要分配给该组的权限。租户管理权限用于确定用户可以使用租户管理器或租户管理 API 执行的任务。一个用户可以属于一个或多个组。如果用户属于多个组，则权限是累积的。 
---
= 租户管理权限
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在创建租户组之前，请考虑要分配给该组的权限。租户管理权限用于确定用户可以使用租户管理器或租户管理 API 执行的任务。一个用户可以属于一个或多个组。如果用户属于多个组，则权限是累积的。

要登录到租户管理器或使用租户管理 API ，用户必须属于至少具有一个权限的组。所有可以登录的用户均可执行以下任务：

* 查看信息板
* 更改自己的密码（适用于本地用户）


对于所有权限，组的访问模式设置将确定用户是否可以更改设置并执行操作，或者是否只能查看相关设置和功能。


NOTE: 如果用户属于多个组，并且任何组设置为只读，则用户将对所有选定设置和功能具有只读访问权限。

您可以为组分配以下权限。请注意， S3 租户和 Swift 租户具有不同的组权限。

[cols="1a,3a,3a"]
|===
| 权限 | 说明 | 详细信息 


 a| 
root 访问权限
 a| 
提供对租户管理器和租户管理 API 的完全访问权限。
 a| 
Swift用户必须具有root访问权限才能登录到租户帐户。



 a| 
管理员
 a| 
仅限 Swift 租户。提供对此租户帐户的 Swift 容器和对象的完全访问权限
 a| 
Swift用户必须具有Swift管理员权限才能使用Swift REST API执行任何操作。



 a| 
管理您自己的S3凭据
 a| 
允许用户创建和删除自己的 S3 访问密钥。
 a| 
没有此权限的用户看不到*storage (S3)*>*My S3 access keys*菜单选项。



 a| 
查看所有存储分段
 a| 
*S3租户*：允许用户查看所有存储分段和存储分段配置。

*Swift租户*：允许Swift用户使用租户管理API查看所有容器和容器配置。
 a| 
没有“查看所有存储分段”或“管理所有存储分段”权限的用户不会看到“*存储分段*”菜单选项。

此权限将被"管理所有存储分段"权限所取代。它不会影响S3客户端或S3控制台使用的S3存储分段或组策略。

您只能从租户管理API将此权限分配给Swift组。您不能使用租户管理器将此权限分配给Swift组。



 a| 
管理所有存储分段
 a| 
* S3租户*：允许用户使用租户管理器和租户管理API创建和删除S3存储分段、并管理租户帐户中所有S3存储分段的设置、而不管S3存储分段或组策略如何。

*Swift租户*：允许Swift用户使用租户管理API控制Swift容器的一致性。
 a| 
没有“查看所有存储分段”或“管理所有存储分段”权限的用户不会看到“*存储分段*”菜单选项。

此权限将取代查看所有存储分段权限。它不会影响S3客户端或S3控制台使用的S3存储分段或组策略。

您只能从租户管理API将此权限分配给Swift组。您不能使用租户管理器将此权限分配给Swift组。



 a| 
管理端点
 a| 
允许用户使用租户管理器或租户管理API创建或编辑平台服务端点、这些端点用作StorageGRID 平台服务的目标。
 a| 
没有此权限的用户看不到“*平台服务端点*”菜单选项。



 a| 
使用S3控制台选项卡
 a| 
与查看所有存储分段或管理所有存储分段权限结合使用时、用户可以从存储分段详细信息页面上的S3控制台选项卡查看和管理对象。
 a| 

|===