---
permalink: tenant/update-default-retention-settings.html 
sidebar: sidebar 
keywords: update default retention for s3 object lock bucket, default retention mode, default retention period, compliance, governance 
summary: '如果您在创建存储分段时启用了S3对象锁定、则可以编辑存储分段以更改默认保留设置。您可以启用(或禁用)默认保留并设置默认保留模式和保留期限。' 
---
= 更新S3对象锁定默认保留
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您在创建存储分段时启用了S3对象锁定、则可以编辑存储分段以更改默认保留设置。您可以启用(或禁用)默认保留并设置默认保留模式和保留期限。

.开始之前
* 您已使用登录到租户管理器link:../admin/web-browser-requirements.html["支持的 Web 浏览器"]。
* 您属于具有的用户组link:tenant-management-permissions.html["管理所有分段或root访问权限"]。这些权限将覆盖组或存储分段策略中的权限设置。
* 系统会为您的StorageGRID 系统全局启用S3对象锁定、您可以在创建存储分段时启用S3对象锁定。请参阅。 link:using-s3-object-lock.html["使用S3对象锁定保留对象"]


.步骤
. 从信息板中选择*查看存储分段*，或选择*存储(S3)*>*存储分段*。
. 从表中选择分段名称。
+
此时将显示存储分段详细信息页面。

. 从*存储分段选项*选项卡中，选择*S3对象锁定*可触摸板。
. (可选)为此存储分段启用或禁用*默认保留*。
+
对此设置所做的更改不会应用于存储分段中已有的对象或可能具有自己保留期限的任何对象。

. 如果启用了*默认保留*，请为存储分段指定*默认保留模式*。
+
[cols="1a,2a"]
|===
| 默认保留模式 | 说明 


 a| 
监管
 a| 
** 具有权限的用户 `s3:BypassGovernanceRetention`可以使用 `x-amz-bypass-governance-retention: true`请求标头绕过保留设置。
** 这些用户可以在达到保留截止日期之前删除对象版本。
** 这些用户可以增加、减少或删除对象的保留截止日期。




 a| 
合规性
 a| 
** 在达到保留截止日期之前、无法删除此对象。
** 对象的保留截止日期可以增加、但不能减少。
** 在达到该日期之前、无法删除对象的保留截止日期。


*注意*：网格管理员必须允许您使用兼容模式。

|===
. 如果启用了*默认保留*，请指定存储分段的*默认保留期限*。
+
*默认保留期限*表示添加到此存储分段的新对象应保留多长时间、从其被插入开始。指定一个小于或等于网格管理员设置的租户最长保留期限的值。

+
网格管理员创建租户时会设置一个_maximum _保留期限、该保留期限的值可以介于1天到100年之间。如果设置了_default_保留期限、则该保留期限不能超过为最长保留期限设置的值。如果需要、请让网格管理员增加或减少最长保留期限。

. 选择 * 保存更改 * 。

