---
permalink: tenant/using-storagegrid-tenant-account.html 
sidebar: sidebar 
keywords: how to use tenant account 
summary: '租户帐户允许您使用简单存储服务\(S3\) REST API在StorageGRID系统中存储和检索对象。' 
---
= 使用 StorageGRID 租户帐户
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
租户帐户允许您使用简单存储服务(S3) REST API在StorageGRID系统中存储和检索对象。

每个租户帐户都有自己的联合组或本地组、用户、S3分段和对象。


TIP: Swift详细信息已从此版本的文档站点中删除。请参阅。 https://docs.netapp.com/us-en/storagegrid-118/tenant/using-storagegrid-tenant-account.html["StorageGRID 11.8：使用StorageGRID租户帐户"^]

也可以使用租户帐户按不同的实体隔离存储的对象。例如，以下任一使用情形均可使用多个租户帐户：

* * 企业用例： * 如果在企业中使用 StorageGRID 系统，则网格的对象存储可能会被组织中的不同部门隔离。例如，可能存在营销部门，客户支持部门，人力资源部门等的租户帐户。
+

NOTE: 如果使用 S3 客户端协议，则还可以使用 S3 分段和分段策略在企业中的各个部门之间隔离对象。您无需创建单独的租户帐户。有关详细信息、请参见实施说明link:../s3/bucket-and-group-access-policies.html["S3存储分段和存储分段策略"]。

* * 服务提供商用例： * 如果服务提供商正在使用 StorageGRID 系统，则网格的对象存储可能会被租用该存储的不同实体分隔。例如，可能存在公司 A ，公司 B ，公司 C 等的租户帐户。




== 创建租户帐户

租户帐户由 StorageGRID 网格管理员使用网格管理器创建。创建租户帐户时，网格管理员会指定以下信息：

* 租户的显示名称(系统会自动分配租户的帐户ID、并且无法更改)。
* 租户帐户将使用S3协议还是Swift协议。
* 对于 S3 租户帐户：是否允许租户帐户使用平台服务。如果允许使用平台服务，则必须对网格进行配置，以支持使用这些服务。
* （可选）租户帐户的存储配额—租户对象可用的最大 GB ， TB 或 PB 数。租户的存储配额表示逻辑容量（对象大小），而不是物理容量（磁盘大小）。
* 如果为 StorageGRID 系统启用了身份联合，则哪个联合组具有 root 访问权限来配置租户帐户。
* 如果 StorageGRID 系统未使用单点登录（ SSO ），则表示租户帐户是使用自己的身份源还是共享网格的身份源，以及租户的本地 root 用户的初始密码。


此外，如果 S3 租户帐户需要符合法规要求，网格管理员可以为 StorageGRID 系统启用 S3 对象锁定设置。启用 S3 对象锁定后，所有 S3 租户帐户均可创建和管理合规的存储分段。



== 配置 S3 租户

创建 S3 租户帐户后，您可以访问租户管理器以执行如下任务：

* 设置身份联合（除非身份源与网格共享）或创建本地组和用户
* 管理 S3 访问密钥
* 创建和管理 S3 存储分段，包括合规存储分段
* 使用平台服务（如果已启用）
* 监控存储使用情况



TIP: 虽然您可以使用租户管理器创建和管理 S3 存储分段，但您必须具有 S3 访问密钥，并使用 S3 REST API 载入和管理对象。

.相关信息
* link:../admin/index.html["管理 StorageGRID"]
* link:../s3/index.html["使用S3 REST API"]

