---
permalink: rhel/downloading-and-extracting-storagegrid-installation-files.html 
sidebar: sidebar 
keywords: red hat linux installation files, how to download installation files 
summary: 您必须下载 StorageGRID 安装归档并提取所需文件。您也可以手动验证安装包中的文件。 
---
= 下载并提取 StorageGRID 安装文件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必须下载 StorageGRID 安装归档并提取所需文件。您也可以手动验证安装包中的文件。

.步骤
. 转到。 https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["StorageGRID 的 "NetApp 下载 " 页面"^]
. 选择用于下载最新版本的按钮，或者从下拉菜单中选择其他版本并选择 * 执行 * 。
. 使用您的 NetApp 帐户的用户名和密码登录。
. 如果显示Cauy/MustRead语句，请阅读该语句并选中该复选框。
+

CAUTION: 安装 StorageGRID 版本后，您必须应用任何所需的修补程序。有关详细信息，请参见link:../maintain/storagegrid-hotfix-procedure.html["恢复和维护说明中的热修补程序操作步骤"]。

. 阅读最终用户许可协议，选中复选框，然后选择*接受并继续*。
. 在*安装Linux*列中，选择用于Red Hat StorageGRID的.tgz或.zip安装归档文件。
+

NOTE: 如果您在服务笔记本电脑上运行Windows、请选择此 `.zip`文件。

. 保存安装归档文件。
. [[rRHEL下载验证包]]如果需要验证安装归档文件：
+
.. 下载StorageGRID代码签名验证包。此软件包的文件名使用格式 `StorageGRID_<version-number>_Code_Signature_Verification_Package.tar.gz`，其中 `<version-number>`是StorageGRID软件版本。
.. 按照步骤执行link:../rhel/download-files-verify.html["手动验证安装文件"]。


. 从安装归档文件中提取文件。
. 选择所需的文件。
+
所需的文件取决于您规划的网格拓扑以及如何部署 StorageGRID 系统。

+

NOTE: 表中列出的路径与提取的安装归档所安装的顶级目录相对



[cols="1a,1a"]
|===
| 路径和文件名 | 说明 


| ./rpms/README  a| 
一个文本文件，用于描述 StorageGRID 下载文件中包含的所有文件。



| ./rpms/NLF000000.txt  a| 
一种免费许可证，不提供产品的任何支持授权。



| ./rpms/StorageGRID-Webscale-Images-_version_-SHA.rpm  a| 
RPM软件包、用于在RHEL主机上安装StorageGRID节点映像。



| ./rpms/StorageGRID-Webscale-Service-_version_-SHA.rpm  a| 
RPM软件包、用于在RHEL主机上安装StorageGRID主机服务。



| 部署脚本工具 | 说明 


| ./rpms/configure-storagegrid.py  a| 
一种用于自动配置 StorageGRID 系统的 Python 脚本。



| ./rpms/configure-sga.py  a| 
一种用于自动配置 StorageGRID 设备的 Python 脚本。



| ./rpms/configure-storagegrid.sample.json  a| 
用于脚本的示例配置文件 `configure-storagegrid.py`。



| ./rpms/storagegrid-ssoauth.py  a| 
一个示例 Python 脚本，启用单点登录后，您可以使用该脚本登录到网格管理 API 。您也可以使用此脚本进行Ping联盟集成。



| ./rpms/configure-storagegrid.blank.json  a| 
用于脚本的空配置文件 `configure-storagegrid.py`。



| ./rpms/Extras 或 Ansible  a| 
用于为StorageGRID容器部署配置RHEL主机的AndsableRole和操作手册示例。您可以根据需要自定义角色或攻略手册。



| ./rpms/storagegrid-ssoauth-azure.py  a| 
一个Python脚本示例、在使用Active Directory或Ping联合启用单点登录(Single Sign On、SSO)时、您可以使用该脚本登录到网格管理API。



| ./rpms/storagegrid－ssoauth-azure.js  a| 
由配套Python脚本调用的帮助程序 `storagegrid-ssoauth-azure.py`脚本、用于与Azure执行SSO交互。



| ./rpms/Extras 或 API 架构  a| 
StorageGRID 的 API 架构。

*注意*：如果您没有用于升级兼容性测试的非生产StorageGRID 环境，则在执行升级之前，可以使用这些模式来确认为使用StorageGRID 管理API而编写的任何代码是否与新的StorageGRID 版本兼容。

|===