---
permalink: admin/admin-group-permissions.html 
sidebar: sidebar 
keywords: admin group permissions 
summary: 创建管理员用户组时，您可以选择一个或多个权限来控制对网格管理器特定功能的访问。然后，您可以将每个用户分配给一个或多个管理组，以确定用户可以执行的任务。 
---
= 管理组权限
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
创建管理员用户组时，您可以选择一个或多个权限来控制对网格管理器特定功能的访问。然后，您可以将每个用户分配给一个或多个管理组，以确定用户可以执行的任务。

您必须为每个组至少分配一个权限；否则，属于该组的用户将无法登录到网格管理器或网格管理 API 。

默认情况下，属于至少具有一个权限的组的任何用户均可执行以下任务：

* 登录到网格管理器
* 查看信息板
* 查看节点页面
* 查看当前警报和已解决警报
* 更改自己的密码（仅限本地用户）
* 查看配置和维护页面上提供的某些信息




== 权限与访问模式之间的交互

对于所有权限，组的 * 访问模式 * 设置将确定用户是否可以更改设置并执行操作，或者是否只能查看相关设置和功能。如果用户属于多个组，并且任何组设置为 * 只读 * ，则用户将对所有选定设置和功能具有只读访问权限。

以下各节介绍了在创建或编辑管理组时可以分配的权限。未明确提及的任何功能都需要具有 * 根访问权限 * 。



== root 访问权限

通过此权限，可以访问所有网格管理功能。



== 更改租户 root 密码

通过此权限，您可以访问租户页面上的 * 更改 root 密码 * 选项，从而可以控制谁可以更改租户的本地 root 用户的密码。启用 S3 密钥导入功能后，此权限也用于迁移 S3 密钥。没有此权限的用户看不到*更改root密码*选项。


NOTE: 要授予对包含 * 更改 root 密码 * 选项的租户页面的访问权限，还需要分配 * 租户帐户 * 权限。



== ILM

通过此权限，您可以访问以下 * ILM * 菜单选项：

* 规则
* 策略
* 策略标记
* 存储池
* 存储等级
* regions
* 对象元数据查找



NOTE: 用户必须具有*其他网格配置*权限才能管理存储等级。



== 维护

用户必须具有维护权限才能使用以下选项：

* *配置* > *访问控制*：
+
** 网格密码


* *配置* > *网络*：
+
** S3端点域名


* *维护* > *任务*：
+
** 停用
** 扩展
** 对象存在检查
** 恢复


* *维护* > *系统*：
+
** 恢复包
** 软件更新


* *支持* > *工具*：
+
** 日志




没有维护权限的用户可以查看但不能编辑以下页面：

* *维护* > *网络*：
+
** DNS 服务器
** 网格网络
** NTP 服务器


* *维护* > *系统*：
+
** 许可证


* *配置* > *网络*：
+
** S3端点域名


* *配置* > *安全*：
+
** 证书


* *配置* > *监控*：
+
** 审核和系统日志服务器






== 管理警报

通过此权限，您可以访问用于管理警报的选项。用户必须具有此权限才能管理静音，警报通知和警报规则。



== 指标查询

此权限提供对以下内容的访问权限：

* *支持* > *工具* > *指标*页面
* 使用网格管理API的*Metrics*部分自定义Prometheus指标查询
* 包含指标的Grid Manager信息板卡




== 对象元数据查找

通过此权限，您可以访问 * ILM * > * 对象元数据查找 * 页面。



== 其他网格配置

此权限提供对这些附加网格配置选项的访问：

* * ILM ：
+
** 存储等级


* *配置* > *系统*：
* *支持* > *其他*：
+
** 链路成本






== 存储设备管理员

此权限提供：

* 通过网格管理器访问存储设备上的E系列SANtricity System Manager。
* 能够在管理驱动器选项卡上对支持这些操作的设备执行故障排除和维护任务。




== 租户帐户

此权限可用于：

* 访问租户页面、在此可以创建、编辑和删除租户帐户
* 查看现有流量分类策略
* 查看包含租户详细信息的Grid Manager信息板卡

