---
permalink: admin/change-node-console-password.html 
sidebar: sidebar 
keywords: node console password, console password, change password, password 
summary: 网格中的每个节点都有一个唯一的节点控制台密码，您需要使用该密码登录到该节点。按照以下步骤更改网格中每个节点的节点控制台密码。密码存储在恢复包中。 
---
= 更改节点控制台密码
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
网格中的每个节点都有一个唯一的节点控制台密码，您需要使用该密码登录到该节点。按照以下步骤更改网格中每个节点的每个唯一节点控制台密码。

.开始之前
* 您已使用登录到网格管理器link:../admin/web-browser-requirements.html["支持的 Web 浏览器"]。
* 您拥有link:admin-group-permissions.html["维护或root访问权限"]。
* 您具有当前配置密码短语。


.关于此任务
使用节点控制台密码通过SSH以"admin"身份登录到节点、或者通过VM/物理控制台连接登录到root用户。更改节点控制台密码过程会为网格中的每个节点创建新密码、并将这些密码存储在恢复软件包中经过更新的 `Passwords.txt`文件中。密码将在 Passwords.txt 文件的 Password 列中列出。


NOTE: 用于节点间通信的 SSH 密钥具有单独的 SSH 访问密码。此操作步骤 不会更改SSH访问密码。



== 访问向导

.步骤
. 选择 * 配置 * > * 访问控制 * > * 网格密码 * 。
. 在*更改节点控制台密码*下、选择*进行更改*。




== 输入配置密码短语

.步骤
. 输入网格的配置密码短语。
. 选择 * 继续 * 。




== [[download-current ]]下载当前恢复软件包

在更改节点控制台密码之前、请下载当前的恢复软件包。如果任何节点的密码更改过程失败、您可以使用此文件中的密码。

.步骤
. 选择 * 下载恢复包 * 。
. 将恢复软件包文件(`.zip`()复制到两个安全、安全、独立的位置。
+

CAUTION: 恢复包文件必须受到保护，因为它包含可用于从 StorageGRID 系统获取数据的加密密钥和密码。

. 选择 * 继续 * 。
. 出现确认对话框时、如果您已准备好开始更改节点控制台密码、请选择*是*。
+
此过程启动后、您无法取消。





== 更改节点控制台密码

当节点控制台密码过程开始时、将生成一个包含新密码的新恢复包。然后、在每个节点上更新密码。

.步骤
. 等待生成新的恢复软件包、这可能需要几分钟的时间。
. 选择 * 下载新恢复包 * 。
. 下载完成后：
+
.. 打开 `.zip`文件。
.. 确认您可以访问包含新节点控制台密码的内容、包括 `Passwords.txt`文件。
.. 将新的恢复软件包文件(`.zip`()复制到两个安全、安全、独立的位置。
+

CAUTION: 请勿覆盖旧的恢复软件包。

+
恢复包文件必须受到保护，因为它包含可用于从 StorageGRID 系统获取数据的加密密钥和密码。



. 选中此复选框以指示您已下载新的恢复软件包并验证其内容。
. 选择*更改节点控制台密码*、然后等待所有节点使用新密码进行更新。这可能需要几分钟时间。
+
如果所有节点的密码均已更改，则会显示一个绿色的成功横幅。转至下一步。

+
如果更新过程中出现错误，则会显示一条横幅消息，列出无法更改密码的节点数。系统将在任何无法更改密码的节点上自动重试此过程。如果此过程结束时某些节点仍没有更改密码，则会显示 * 重试 * 按钮。

+
如果一个或多个节点的密码更新失败：

+
.. 查看表中列出的错误消息。
.. 解决问题。
.. 选择 * 重试 * 。
+

NOTE: 重试仅会更改先前尝试更改密码期间失败的节点上的节点控制台密码。



. 更改所有节点的节点控制台密码后，删除<<download-current,下载的第一个恢复软件包>>。
. 或者，也可以使用 * 恢复软件包 * 链接下载新恢复软件包的其他副本。

