---
permalink: admin/change-node-console-password.html 
sidebar: sidebar 
keywords: node console password, console password, change password, password 
summary: 网格中的每个节点都有一个节点控制台密码，您可以使用该密码登录该节点。默认情况下，每个节点都有一个唯一的密码。您可以将每个密码更改为新的唯一密码，也可以将每个节点的密码更改为使用全局密码。密码存储在恢复包中。 
---
= 更改节点控制台密码
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
网格中的每个节点都有一个节点控制台密码，您可以使用该密码登录该节点。默认情况下，每个节点都有一个唯一的密码。您可以将每个密码更改为新的唯一密码，也可以将每个节点的密码更改为使用全局密码。密码存储在恢复包中。

.开始之前
* 您已使用登录到网格管理器link:../admin/web-browser-requirements.html["支持的 Web 浏览器"]。
* 您拥有link:admin-group-permissions.html["维护或root访问权限"]。
* 您具有当前配置密码短语。


.关于此任务
您可以使用节点控制台密码通过 SSH 以“管理员”身份登录到节点，或者通过 VM/物理控制台连接以 root 用户身份登录。您可以使用以下选项之一更改节点控制台密码：

* 自动对每个节点应用随机密码
* 指定一个全局密码并将其应用于所有节点
* 指定并将唯一密码应用于一个或多个节点


密码存储在更新的 `Passwords.txt`恢复包中的文件。密码列在文件的密码列中。


NOTE: 这link:../admin/change-ssh-access-passwords.html["SSH 访问密码"]用于节点间通信的 SSH 密钥与节点控制台密码是分开的。此过程不会更改 SSH 访问密码。



== 访问向导

.步骤
. 选择*配置* > *访问控制* > *电网密码*。
. 在*更改节点控制台密码*下、选择*进行更改*。




== [[download-current ]]下载当前恢复软件包

在更改节点控制台密码之前，请下载当前的恢复包。如果任何节点的密码更改过程失败，您可以使用此文件中的密码。

.步骤
. 输入网格的配置密码短语。
. 选择 * 下载恢复包 * 。
. 复制恢复包文件(`.zip`）到两个安全、可靠且独立的位置。
+

CAUTION: 恢复包文件必须是安全的，因为它包含可用于从StorageGRID系统获取数据的加密密钥和密码。

. 选择 * 继续 * 。




== 提供新密码

. 选择您想要使用的密码更改方法。
+
** *自动*： StorageGRID自动为所有节点分配一个新的随机控制台密码。
** *自定义*：您提供控制台密码。




[role="tabbed-block"]
====
.自动
--
. 选择 * 继续 * 。


--
.自定义
--
. 选择以下选项之一：
+
** *全局控制台密码*：对所有节点应用相同的控制台密码。
** *唯一的控制台密码*：在一个或多个节点上应用不同的密码。


. 如果您选择了*全局控制台密码*，请输入您想要用于所有节点的密码。
. 如果选择了“唯一控制台密码”，请为一个或多个节点输入唯一密码。
. 选择 * 继续 * 。


--
====


== 完成密码修改

. 当确认对话框出现时，如果您准备好让StorageGRID开始更改节点控制台密码，请选择 *是*。
+

NOTE: 此过程启动后、您无法取消。

+
StorageGRID生成一个包含新密码的新恢复包。

. 当新的恢复包准备好后，选择*下载新的恢复包*并保存恢复包。
. 打开 `.zip`文件。
. 确认您可以访问包含新节点控制台密码的内容、包括 `Passwords.txt`文件。
. 复制新的恢复包文件(`.zip`）到两个安全、可靠且独立的地点。
+

CAUTION: 不要覆盖旧的恢复包。

+
您必须保护恢复文件，因为它包含可用于从StorageGRID系统获取数据的加密密钥和密码。

. 选中复选框表示您已下载新的恢复包并验证了内容。
. 选择 * 继续 * 。
+
StorageGRID更新每个节点的密码。

+
如果更新过程中出现错误，进度条会列出密码更改失败的节点数。系统将自动在密码更改失败的任何节点上重试该过程。如果该过程结束时某些节点仍未更改密码，则会出现“重试”按钮。

. 如果一个或多个节点的密码更新失败：
+
.. 查看表中列出的错误消息。
.. 解决问题。
.. 选择 * 重试 * 。
+

NOTE: 重试仅会更改先前尝试更改密码期间失败的节点上的节点控制台密码。



. 当进度条显示没有剩余更新时，选择*完成*。
. 更改所有节点的节点控制台密码后，删除<<download-current,您下载的第一个恢复包>>。

