---
permalink: admin/change-ssh-access-passwords.html 
sidebar: sidebar 
keywords: ssh access keys, change ssh access keys 
summary: 更改管理节点的SSH访问密码还会更新网格中每个节点的唯一内部SSH密钥集。主管理节点使用这些SSH密钥通过安全、无密码身份验证访问节点。 
---
= 更改管理节点的SSH访问密码
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
更改管理节点的SSH访问密码还会更新网格中每个节点的唯一内部SSH密钥集。主管理节点使用这些SSH密钥通过安全、无密码身份验证访问节点。

使用SSH密钥以root用户身份登录到节点、或者通过VM或物理控制台连接登录到 `admin`root用户。

.开始之前
* 您已使用登录到网格管理器link:../admin/web-browser-requirements.html["支持的 Web 浏览器"]。
* 您拥有link:admin-group-permissions.html["维护或root访问权限"]。
* 您具有当前配置密码短语。


.关于此任务
管理节点的新访问密码和每个节点的新内部密钥存储在 `Passwords.txt`恢复包中的文件。密钥列在该文件中的密码列中。

用于节点间通信的 SSH 密钥具有单独的 SSH 访问密码。此过程不会对其进行更改。



== 访问向导

.步骤
. 选择*配置* > *访问控制* > *电网密码*。
. 在*更改SSH密钥*下，选择*进行更改*。




== [[download-current ]]下载当前恢复软件包

在更改 SSH 访问密钥之前，请下载当前的恢复包。如果任何节点的密钥更改过程失败，您可以使用此文件中的密钥。

.步骤
. 输入网格的配置密码短语。
. 选择 * 下载恢复包 * 。
. 复制恢复包文件(`.zip`）到两个安全、可靠且独立的位置。
+

CAUTION: 恢复包文件必须是安全的，因为它包含可用于从StorageGRID系统获取数据的加密密钥和密码。

. 选择 * 继续 * 。
. 出现确认对话框时，如果您准备好开始更改SSH访问密钥，请选择*Yes*。
+

CAUTION: 此过程启动后、您无法取消。





== 更改SSH访问密钥

当更改 SSH 访问密钥过程开始时，将生成一个包含新密钥的新恢复包。然后，在每个节点上更新密钥。

.步骤
. 等待新的恢复包生成，这可能需要几分钟。
. 当“下载新的恢复包”按钮启用时，选择“*下载新的恢复包*”并保存新的恢复包文件(`.zip`）到两个安全、可靠且独立的地点。
. 下载完成后：
+
.. 打开 `.zip`文件。
.. 确认您可以访问包含新SSH访问密钥的内容、包括 `Passwords.txt`文件。
.. 复制新的恢复包文件(`.zip`）到两个安全、可靠且独立的地点。
+

CAUTION: 不要覆盖旧的恢复包。

+
恢复包文件必须是安全的，因为它包含可用于从StorageGRID系统获取数据的加密密钥和密码。



. 等待每个节点上的密钥更新、这可能需要几分钟时间。
+
如果更改了所有节点的密钥、则会显示绿色成功横幅。

+
如果在更新过程中出现错误、则会显示一条横幅消息、列出无法更改密钥的节点数量。系统将在任何未能更改密钥的节点上自动重试此过程。如果此过程结束时某些节点的密钥仍未更改，则会显示*Retry*按钮。

+
如果一个或多个节点的密钥更新失败：

+
.. 查看表中列出的错误消息。
.. 解决问题。
.. 选择 * 重试 * 。
+
重试仅会更改先前尝试更改密钥期间失败的节点上的SSH访问密钥。



. 在所有节点的 SSH 访问密钥更改后，删除<<download-current,您下载的第一个恢复包>>。
. 或者，选择“*维护*”>“*系统*”>“*恢复包*”来下载新恢复包的附加副本。

