---
permalink: admin/changing-browser-session-timeout-interface.html 
sidebar: sidebar 
keywords: security, browser inactivity timeout, management API stack track 
summary: 通过接口安全设置、您可以控制在用户处于非活动状态的时间超过指定时间时是否注销、以及是否在API错误响应中包含堆栈跟踪。 
---
= 更改接口安全设置
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通过接口安全设置、您可以控制在用户处于非活动状态的时间超过指定时间时是否注销、以及是否在API错误响应中包含堆栈跟踪。

.开始之前
* 您已使用登录到网格管理器link:../admin/web-browser-requirements.html["支持的 Web 浏览器"]。
* 您拥有 link:admin-group-permissions.html["root访问权限"]。


.关于此任务
“*安全设置”页面包括*浏览器非活动超时*和*管理API堆栈跟踪*设置。

浏览器非活动超时:: 指示用户的浏览器在注销前可以处于非活动状态的时间长度。默认值为 15 分钟。
+
--
浏览器非活动超时还受以下因素控制：

* 一个单独的不可配置 StorageGRID 计时器，其中包括用于系统安全保护的计时器。每个用户的身份验证令牌将在用户登录后16小时过期。当用户的身份验证过期时、即使禁用了浏览器非活动超时或未达到浏览器超时值、该用户也会自动注销。要续订令牌，用户必须重新登录。
* 身份提供程序的超时设置(假设为StorageGRID 启用了单点登录(SSO))。
+
如果启用了 SSO 并且用户的浏览器超时，则用户必须重新输入其 SSO 凭据才能再次访问StorageGRID 。看link:how-sso-works.html["SSO 的工作原理"] 。



--
管理API堆栈跟踪:: 控制是否在Grid Manager和租户管理器API错误响应中返回堆栈跟踪。
+
--
默认情况下、此选项处于禁用状态、但您可能希望在测试环境中启用此功能。通常、您应在生产环境中禁用堆栈跟踪、以避免在发生API错误时泄露内部软件详细信息。

--


.步骤
. 选择*配置* > *安全* > *安全设置*。
. 选择*Interface*选项卡。
. 要更改浏览器非活动超时设置：
+
.. 展开可展开面。
.. 要更改超时期限、请指定一个介于60秒和7天之间的值。默认超时为15分钟。
.. 要禁用此功能、请取消选中此复选框。
.. 选择 * 保存 * 。
+
新设置不会影响当前已登录的用户。用户必须重新登录或刷新其浏览器、新超时设置才能生效。



. 要更改管理API堆栈跟踪设置、请执行以下操作：
+
.. 展开可展开面。
.. 选中此复选框可在Grid Manager和租户管理器API错误响应中返回堆栈跟踪。
+

CAUTION: 在生产环境中禁用堆栈跟踪、以避免在发生API错误时泄露内部软件详细信息。

.. 选择 * 保存 * 。



