---
permalink: admin/creating-tenant-account.html 
sidebar: sidebar 
keywords: create tenant, tenant account 
summary: 您必须至少创建一个租户帐户，才能控制对 StorageGRID 系统中存储的访问。 
---
= 创建租户帐户
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必须至少创建一个租户帐户，才能控制对 StorageGRID 系统中存储的访问。

创建租户帐户的步骤取决于link:using-identity-federation.html["身份联合"]和link:how-sso-works.html["单点登录"]是否配置，以及用于创建租户帐户的网格管理器帐户是否属于具有 Root 访问权限的管理员组。

.开始之前
* 您已使用登录到网格管理器link:../admin/web-browser-requirements.html["支持的 Web 浏览器"]。
* 您拥有link:admin-group-permissions.html["root访问权限或租户帐户权限"]。
* 如果租户帐户将使用为网格管理器配置的身份源，并且您要将租户帐户的 root 访问权限授予某个联合组，则您已将该联合组导入到网格管理器中。您无需为此管理员组分配任何网格管理器权限。请参阅。 link:managing-admin-groups.html["管理管理组"]
* 如果要允许S3租户克隆帐户数据并使用网格联合连接将存储分段对象复制到另一个网格：
+
** 您拥有 link:grid-federation-create-connection.html["已配置网格联合连接"]。
** 连接状态为*已连接*。
** 您具有 root 访问权限。
** 您已查看的注意事项link:grid-federation-manage-tenants.html["管理网格联盟允许的租户"]。
** 如果租户帐户将使用为Grid Manager配置的身份源、则您已将同一联盟组导入到两个网格上的Grid Manager中。
+
创建租户时、您需要选择此组、以获得源租户帐户和目标租户帐户的初始root访问权限。

+

TIP: 如果在创建租户之前此管理员组不在两个网格上、则不会将租户复制到目标。







== 访问向导

.步骤
. 选择*租户*。
. 选择 * 创建 * 。




== 输入详细信息

.步骤
. 输入租户的详细信息。
+
[cols="1a,3a"]
|===
| 字段 | 说明 


 a| 
名称
 a| 
租户帐户的名称。租户名称不需要唯一。创建租户帐户时、它会收到一个唯一的20位数帐户ID。



 a| 
问题描述 (可选)
 a| 
用于帮助识别租户的问题描述。

如果您要创建将使用网格联合连接的租户、也可以使用此字段帮助确定哪个是源租户、哪个是目标租户。例如、对于在网格1上创建的租户、如果该租户复制到网格2、则也会显示此问题描述 ："This租户was created on Grid 1"(此租户已在网格1上创建)。



 a| 
客户端类型
 a| 
必须为*S3*。



 a| 
存储配额(可选)
 a| 
如果希望此租户具有存储配额、则为配额和单位指定一个数值。

|===
. 选择 * 继续 * 。




== [[admin-租 户-Select-permissions ]]选择权限

.步骤
. (可选)选择希望此租户具有的基本权限。
+

NOTE: 其中某些权限还有其他要求。有关详细信息、请选择每个权限的帮助图标。

+
[cols="1a,3a"]
|===
| 权限 | 如果选择... 


 a| 
允许平台服务
 a| 
租户可以使用CloudMirror等S3平台服务。请参阅。 link:../admin/manage-platform-services-for-tenants.html["管理 S3 租户帐户的平台服务"]



 a| 
使用自己的身份源
 a| 
租户可以为联合组和用户配置和管理自己的身份源。如果您有以下情况，则此选项被禁用link:../admin/how-sso-works.html["已配置SSO"]适用于您的StorageGRID系统。



 a| 
允许S3选择
 a| 
租户可以通过问题描述 S3选择对象内容API请求筛选和检索对象数据。请参阅。 link:../admin/manage-s3-select-for-tenant-accounts.html["管理租户帐户的 S3 Select"]

*重要*：选择对象内容请求会降低所有S3客户端和所有租户的负载平衡器性能。仅在需要时才启用此功能，并且仅适用于受信任租户。

|===
. (可选)选择希望此租户具有的高级权限。
+
[cols="1a,3a"]
|===
| 权限 | 如果选择... 


 a| 
网格联合连接
 a| 
租户可以使用网格联合连接、该连接可以：

** 使此租户以及添加到帐户的所有租户组和用户从此网格(_ssource grid _)克隆到选定连接中的另一网格(_dDestination grid _)。
** 允许此租户在每个网格上的相应分段之间配置跨网格复制。


请参阅。 link:../admin/grid-federation-manage-tenants.html["管理网格联盟允许的租户"]



 a| 
S3 对象锁定
 a| 
允许租户使用S3对象锁定的特定功能：

** *设置最长保留期限*用于定义添加到此存储分段的新对象应保留多长时间、从其被插入开始。
** *允许兼容模式*可防止用户在保留期间覆盖或删除受保护的对象版本。


|===
. 选择 * 继续 * 。




== 定义root访问权限并创建租户

.步骤
. 根据您的StorageGRID 系统是使用身份联合、单点登录(SSO)还是同时使用这两者、定义租户帐户的root访问权限。
+
[cols="1a,2a"]
|===
| 选项 | 执行此操作 ... 


 a| 
如果未启用身份联合
 a| 
指定以本地root用户身份登录租户时要使用的密码。



 a| 
如果启用了身份联合
 a| 
.. 选择一个现有联盟组、以便对租户具有root访问权限。
.. (可选)指定以本地root用户身份登录到租户时要使用的密码。




 a| 
如果同时启用了身份联合和单点登录(SSO)
 a| 
选择一个现有联盟组、以便对租户具有root访问权限。没有本地用户可以登录。

|===
. 选择 * 创建租户 * 。
+
此时将显示一条成功消息、新租户将列在租户页面上。要了解如何查看租户详细信息和监控租户活动，请参见link:../monitor/monitoring-tenant-activity.html["监控租户活动"]。

+

NOTE: 根据网络连接、节点状态和cassandr操作、在网格中应用租户设置可能需要15分钟或更长时间。

. 如果为租户选择了*使用网格联合连接*权限：
+
.. 确认已将同一租户复制到连接中的另一个网格。两个网格上的租户将具有相同的20位数帐户ID、名称、问题描述 、配额和权限。
+

NOTE: 如果您看到错误消息“租户在没有克隆的情况下创建”，请参阅中的说明link:grid-federation-troubleshoot.html["对网格联合错误进行故障排除"]。

.. 如果您在定义root访问权限时提供了本地root用户密码、则link:changing-password-for-tenant-local-root-user.html["更改本地root用户的密码"]适用于复制的租户。
+

TIP: 在更改密码之前、本地root用户无法登录到目标网格上的租户管理器。







== 登录到租户(可选)

您可以根据需要立即登录到新租户以完成配置、也可以稍后登录到租户。登录步骤取决于您是使用默认端口(443)还是使用受限端口登录到网格管理器。请参阅。 link:controlling-access-through-firewalls.html["在外部防火墙处控制访问"]



=== 立即登录

[cols="1a,3a"]
|===
| 如果使用的是... | 操作 


 a| 
端口443、并且您为本地root用户设置了密码
 a| 
. 选择*以root身份登录*。
+
登录时、将显示用于配置分段、身份联合、组和用户的链接。

. 选择用于配置租户帐户的链接。
+
每个链接都会在租户管理器中打开相应的页面。要完成此页面，请参见link:../tenant/index.html["有关使用租户帐户的说明"]。





 a| 
端口443、并且您没有为本地root用户设置密码
 a| 
选择*Sign In*，然后输入root访问联合组中用户的凭据。



 a| 
受限端口
 a| 
. 选择*完成*
. 在租户表中选择*受限*、了解有关访问此租户帐户的更多信息。
+
租户管理器的 URL 格式如下：

+
`https://_FQDN_or_Admin_Node_IP:port_/?accountId=_20-digit-account-id_/`

+
** `_FQDN_or_Admin_Node_IP_`是管理节点的完全限定域名或IP地址
** `_port_`是仅租户端口
** `_20-digit-account-id_`是租户的唯一帐户ID




|===


=== 请稍后登录

[cols="1a,3a"]
|===
| 如果使用的是... | 执行以下操作之一 ... 


 a| 
端口 443
 a| 
* 从网格管理器中，选择“租户”，然后选择租户名称右侧的“Sign in”。
* 在 Web 浏览器中输入租户的 URL ：
+
`https://_FQDN_or_Admin_Node_IP_/?accountId=_20-digit-account-id_/`

+
** `_FQDN_or_Admin_Node_IP_`是管理节点的完全限定域名或IP地址
** `_20-digit-account-id_`是租户的唯一帐户ID






 a| 
受限端口
 a| 
* 从网格管理器中，选择*租户*，然后选择*受限*。
* 在 Web 浏览器中输入租户的 URL ：
+
`https://_FQDN_or_Admin_Node_IP:port_/?accountId=_20-digit-account-id_`

+
** `_FQDN_or_Admin_Node_IP_`是管理节点的完全限定域名或IP地址
** `_port_`是仅租户受限端口
** `_20-digit-account-id_`是租户的唯一帐户ID




|===


== 配置租户

按照中的说明link:../tenant/index.html["使用租户帐户"]管理租户组和用户、S3访问密钥、分段、平台服务以及帐户克隆和跨网格复制。
