---
permalink: admin/creating-traffic-classification-policies.html 
sidebar: sidebar 
keywords: traffic classification, network traffic, traffic limits, policy 
summary: 如果要按分段，租户， IP 子网或负载平衡器端点监控网络流量，并可选择限制此流量，则可以创建流量分类策略。您也可以根据带宽，并发请求数或请求率为策略设置限制。 
---
= 创建流量分类策略
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果要监控网络流量、您可以创建流量分类策略、也可以选择按分段、分段正则表达式、CIDR、负载平衡器端点或租户限制网络流量。您也可以根据带宽，并发请求数或请求率为策略设置限制。

.开始之前
* 您已使用登录到网格管理器link:../admin/web-browser-requirements.html["支持的 Web 浏览器"]。
* 您拥有link:admin-group-permissions.html["root访问权限"]。
* 您已创建要匹配的任何负载平衡器端点。
* 您已创建要匹配的任何租户。


.步骤
. 选择 * 配置 * > * 网络 * > * 流量分类 * 。
. 选择 * 创建 * 。
. 为策略输入名称和问题描述 (可选)，然后选择*CONTINUE*。
+
例如，描述此流量分类策略适用场景 及其限制。

. 选择*添加规则*并指定以下详细信息，为策略创建一个或多个匹配规则。您创建的任何策略都应至少具有一个匹配规则。选择 * 继续 * 。
+
[cols="1a,3a"]
|===
| 字段 | 说明 


 a| 
键入
 a| 
选择与规则适用场景 匹配的流量类型。流量类型包括存储分段、存储分段正则表达式、CIDR、负载平衡器端点和租户。



 a| 
匹配值
 a| 
输入与选定类型匹配的值。

** 存储分段：输入一个或多个存储分段名称。
** b分 段正则表达式：输入用于匹配一组分段名称的一个或多个正则表达式。
+
正则表达式已取消锁定。在分段名称的开头使用^锚定进行匹配、在名称的结尾使用$锚定进行匹配。正则表达式匹配支持PCRE (Perl兼容正则表达式)语法的子集。

** cidr：以CIDR表示法输入一个或多个与所需子网匹配的IPv4子网。
** 负载平衡器端点：选择端点名称。这些是您在上定义的负载平衡器端点link:../admin/configuring-load-balancer-endpoints.html["配置负载平衡器端点"]。
** 租户：租户匹配使用访问密钥ID。如果此请求不包含访问密钥ID (例如、匿名访问)、则会使用所访问存储分段的所有权来确定租户。




 a| 
反向匹配
 a| 
如果要匹配与刚刚定义的类型和匹配值一致的所有网络流量_例外_流量，请选中*反向匹配*复选框。否则、请清除此复选框。

例如，如果要将此策略应用于除一个负载平衡器端点之外的所有端点，请指定要排除的负载平衡器端点，然后选择*Inverse Match*。

对于包含多个匹配器且至少有一个是反向匹配器的策略，请注意不要创建与所有请求匹配的策略。

|===
. (可选)选择*添加限制*，然后选择以下详细信息以添加一个或多个限制，以控制规则匹配的网络流量。
+

NOTE: 即使您未添加任何限制、StorageGRID 也会收集指标、以便您了解流量趋势。

+
[cols="1a,3a"]
|===
| 字段 | 说明 


 a| 
键入
 a| 
要应用于规则匹配的网络流量的限制类型。例如、您可以限制带宽或请求速率。

*注意*：您可以创建策略来限制聚合带宽或限制每个请求的带宽。但是、StorageGRID 不能同时限制这两种类型的带宽。使用聚合带宽时、每个请求的带宽不可用。相反、如果正在使用每个请求的带宽、则聚合带宽将不可用。聚合带宽限制可能会对非受限流量产生额外的轻微性能影响。

对于带宽限制， StorageGRID 会应用与设置的限制类型最匹配的策略。例如，如果您的策略仅限制一个方向的流量，则相反方向的流量将是无限制的，即使存在与具有带宽限制的其他策略匹配的流量也是如此。StorageGRID 按以下顺序实施带宽限制的"最佳"匹配：

** 确切的 IP 地址（ /32 掩码）
** 确切的存储分段名称
** 分段正则表达式
** 租户
** 端点
** 非精确的 CIDR 匹配项（非 /32 ）
** 反向匹配




 a| 
适用场景
 a| 
这是否会限制适用场景 客户端读取请求(GET或HEAD)或写入请求(Put、POST或DELETE)。



 a| 
价值
 a| 
根据您选择的单位、网络流量将限制为的值。例如、输入10并选择MiB/秒、以防止与此规则匹配的网络流量超过10 MiB/秒

*注意*：根据单位设置，可用单位可以是二进制(例如GiB)或十进制(例如GB)。要更改单位设置，请选择网格管理器右上角的用户下拉列表，然后选择*用户首选项*。



 a| 
Unit
 a| 
描述您输入的值的单位。

|===
+
例如、如果要为SLA层创建40 Gb/秒带宽限制、请创建两个聚合带宽限制：GET /机头为40 Gb/秒、而Put / POST / DELETE为40 Gb/秒

. 选择 * 继续 * 。
. 阅读并查看流量分类策略。使用*上一步*按钮返回并根据需要进行更改。对策略满意后，选择*保存并继续*。
+
现在、S3客户端流量将根据流量分类策略进行处理。



.完成后
link:viewing-network-traffic-metrics.html["查看网络流量指标"]验证策略是否强制实施了预期的流量限制。
