---
permalink: admin/deactivate-features-from-api.html 
sidebar: sidebar 
keywords: deactivate features from api 
summary: 您可以使用网格管理 API 完全停用 StorageGRID 系统中的某些功能。停用某个功能后，不能为任何人分配执行与该功能相关的任务的权限。 
---
= 使用 API 停用功能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用网格管理 API 完全停用 StorageGRID 系统中的某些功能。停用某个功能后，不能为任何人分配执行与该功能相关的任务的权限。

.关于此任务
停用的功能系统允许您阻止访问 StorageGRID 系统中的某些功能。停用某个功能是防止 root 用户或具有 * root 访问权限 * 的管理组中的用户能够使用该功能的唯一方法。

要了解此功能的有用程度，请考虑以下情形：

_Company A 是一家服务提供商，通过创建租户帐户租用其 StorageGRID 系统的存储容量。为了保护租户对象的安全， A 公司希望确保自己的员工在部署帐户后永远不能访问任何租户帐户。 _

_Company A 可以通过使用网格管理 API 中的停用功能系统来实现此目标。通过完全停用网格管理器(UI和API)中的*更改租户root密码*功能，公司A可确保管理员用户(包括root用户和属于具有* root访问权限*的组的用户)不能更改任何租户帐户root用户的密码。_

.步骤
. 访问网格管理 API 的 Swagger 文档。请参阅。 link:using-grid-management-api.html["使用网格管理 API"]
. 找到停用功能端点。
. 要停用更改租户 root 密码等功能，请按如下所示向 API 发送正文：
+
`{ "grid": {"changeTenantRootPassword": true} }`

+
请求完成后，更改租户根密码功能将被禁用。用户界面中不再显示*更改租户根密码*管理权限、任何尝试更改租户根密码的API请求都将失败、并显示"403禁止"。





== 重新激活已停用的功能

默认情况下，您可以使用网格管理 API 重新激活已停用的功能。但是，如果要防止重新激活已停用的功能，则可以停用 * 激活功能 * 功能本身。


CAUTION: 无法重新激活*activateFeature*功能。如果您决定停用此功能，请注意，您将永远无法重新激活任何其他已停用的功能。要还原任何丢失的功能，您必须联系技术支持。

.步骤
. 访问网格管理 API 的 Swagger 文档。
. 找到停用功能端点。
. 要重新激活所有功能，请按如下所示将正文发送到 API ：
+
`{ "grid": null }`

+
此请求完成后，包括更改租户 root 密码功能在内的所有功能都将重新激活。现在， " 更改租户根密码 " 管理权限将显示在用户界面中，如果用户具有 * 根访问权限 * 或 * 更改租户根密码 * 管理权限，则尝试更改租户根密码的任何 API 请求都将成功。




TIP: 上一示例将重新激活 _all_ 已停用的功能。如果其他功能已停用，而这些功能应保持停用状态，则必须在 PUT 请求中明确指定它们。例如、要重新激活更改租户root密码功能并继续停用存储管理员管理权限、请发送此放置请求：+
`{ "grid": {"storageAdmin": true} }`
