---
permalink: admin/grid-federation-compare-cgr-to-cloudmirror.html 
sidebar: sidebar 
keywords: cross-grid replication, cloudmirror replication 
summary: 在开始使用网格联盟时、请查看跨网格复制和StorageGRID CloudMirror复制服务之间的相似之处和不同之处。 
---
= 请比较跨网格复制和CloudMirror复制
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
开始使用网格联合时，请查看和之间的相似之处和不同之link:grid-federation-what-is-cross-grid-replication.html["跨网格复制"]link:../tenant/understanding-cloudmirror-replication-service.html["StorageGRID CloudMirror 复制服务"]处。

[cols="1a,3a,3a"]
|===
|  | 跨网格复制 | CloudMirror 复制服务 


 a| 
主要目的是什么？
 a| 
一个StorageGRID 系统充当灾难恢复系统。分段中的对象可以在网格之间进行一个或两个方向的复制。
 a| 
允许租户自动将对象从StorageGRID (源)中的存储分段复制到外部S3存储分段(目标)。

CloudMirror 复制会在独立的 S3 基础架构中为对象创建一个独立副本。此独立副本不会用作备份、但通常会在云中进行进一步处理。



 a| 
如何设置？
 a| 
. 配置两个网格之间的网格联合连接。
. 添加新租户帐户、这些帐户将自动克隆到其他网格。
. 添加新的租户组和用户、这些组和用户也会进行克隆。
. 在每个网格上创建相应的存储分段、并允许跨网格复制在一个或两个方向进行。

 a| 
. 租户用户可通过使用租户管理器或S3 API定义CloudMirror端点(IP地址、凭据等)来配置CloudMirror复制。
. 可以将该租户帐户拥有的任何存储分段配置为指向CloudMirror端点。




 a| 
谁负责设置？
 a| 
* 网格管理员配置连接和租户。
* 租户用户配置组、用户、密钥和分段。

 a| 
通常指租户用户。



 a| 
目标是什么？
 a| 
网格联盟连接中另一个StorageGRID 系统上的相应且相同的S3存储分段。
 a| 
* 任何兼容的S3基础架构(包括Amazon S3)。
* Google Cloud Platform （ GCP ）




 a| 
是否需要对象版本控制？
 a| 
是的、源分段和目标分段都必须启用对象版本控制。
 a| 
不可以、CloudMirror复制支持源和目标上的任何未受版本控制的分段和受版本控制的分段组合。



 a| 
将对象移动到目标的原因是什么？
 a| 
将对象添加到启用了跨网格复制的存储分段时、系统会自动复制这些对象。
 a| 
将对象添加到配置了CloudMirror端点的存储分段时、系统会自动复制这些对象。在为源存储分段配置CloudMirror端点之前、源存储分段中存在的对象不会进行复制、除非对其进行了修改。



 a| 
如何复制对象？
 a| 
跨网格复制可创建版本控制对象、并将版本ID从源存储分段复制到目标存储分段。这样可以在两个网格之间保持版本顺序。
 a| 
CloudMirror复制不需要启用了版本控制的分段、因此CloudMirror只能保持站点内密钥的顺序。对于向不同站点的对象发出的请求、不保证会保持排序。



 a| 
如果无法复制对象、该怎么办？
 a| 
对象将排队等待复制、但要遵守元数据存储限制。
 a| 
对象将排队等待复制，但受平台服务限制的限制(请参见link:manage-platform-services-for-tenants.html["使用平台服务的建议"])。



 a| 
是否复制了对象的系统元数据？
 a| 
可以、当将对象复制到另一个网格时、也会复制其系统元数据。两个网格上的元数据将相同。
 a| 
不可以、将对象复制到外部存储分段时、系统将更新其系统元数据。元数据因位置而异、具体取决于加数据时间以及独立S3基础架构的行为。



 a| 
如何检索对象？
 a| 
应用程序可以通过向任一网格上的存储分段发出请求来检索或读取对象。
 a| 
应用程序可以通过向StorageGRID 或S3目标发出请求来检索或读取对象。例如，假设您使用 CloudMirror 复制将对象镜像到合作伙伴组织。配对节点可以使用自己的应用程序直接从 S3 目标读取或更新对象。不需要使用 StorageGRID 。



 a| 
删除对象会发生什么情况？
 a| 
* 包含版本ID的删除请求不会复制到目标网格。
* 如果删除请求不包含版本ID、请向源存储分段添加一个删除标记、此标记可以选择复制到目标网格。
* 如果只为一个方向配置了跨网格复制、则可以删除目标存储分段中的对象、而不会影响源。

 a| 
根据源分段和目标分段的版本控制状态、结果会有所不同(不必相同)：

* 如果这两个存储分段都已分版本、则删除请求将在这两个位置添加一个删除标记。
* 如果仅对源存储分段进行了版本控制、则删除请求会向源添加一个删除标记、但不会向目标添加此标记。
* 如果两个存储分段均未进行版本控制、则删除请求将从源中删除对象、而不是从目标中删除对象。


同样，可以删除目标分段中的对象而不影响源。

|===