---
permalink: admin/guidelines-for-storagegrid-networks.html 
sidebar: sidebar 
keywords: admin network, client network, grid network, access interface, trunk interface 
summary: StorageGRID 在每个网格节点上最多支持三个网络接口，使您可以根据安全和访问要求为每个网格节点配置网络。 
---
= StorageGRID 网络准则
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用网格管理器配置和管理 StorageGRID 网络和连接。

请参见link:configuring-client-connections.html["配置S3客户端连接"]、了解如何连接S3客户端。



== 默认 StorageGRID 网络

默认情况下， StorageGRID 支持每个网格节点使用三个网络接口，从而可以根据您的安全和访问要求为每个网格节点配置网络。

有关网络拓扑的详细信息，请参见link:../network/index.html["网络连接准则"]。



=== 网格网络

必填。网格网络用于所有内部 StorageGRID 流量。它可以在网格中的所有节点之间以及所有站点和子网之间建立连接。



=== 管理网络

可选。管理网络通常用于系统管理和维护。它也可用于客户端协议访问。管理网络通常是一个专用网络，不需要在站点之间进行路由。



=== 客户端网络

可选。客户端网络是一种开放式网络、通常用于提供对S3客户端应用程序的访问、因此可以隔离网格网络并确保其安全。客户端网络可以与可通过本地网关访问的任何子网进行通信。



== 准则

* 每个StorageGRID节点为其分配的每个网络都需要一个专用网络接口、IP地址、子网掩码和网关。
* 一个网格节点不能在一个网络上具有多个接口。
* 支持每个网格节点在每个网络上使用一个网关，并且该网关必须与节点位于同一子网中。如果需要，您可以在网关中实施更复杂的路由。
* 在每个节点上，每个网络都映射到一个特定的网络接口。
+
[cols="1a,1a"]
|===
| 网络 | 接口名称 


 a| 
网格
 a| 
eth0



 a| 
admin （可选）
 a| 
eth1



 a| 
客户端（可选）
 a| 
eth2

|===
* 如果节点连接到 StorageGRID 设备，则每个网络都使用特定端口。有关详细信息，请参见适用于您的设备的安装说明。
* 每个节点都会自动生成默认路由。如果启用了 eth2 ，则 0.0.0.0/0 将在 eth2 上使用客户端网络。如果未启用 eth2 ，则 0.0.0.0/0 将在 eth0 上使用网格网络。
* 只有在网格节点加入网格后，客户端网络才会正常运行
* 可以在网格节点部署期间配置管理网络，以便在网格完全安装之前能够访问安装用户界面。




== 可选接口

您也可以向节点添加额外的接口。例如、您可能希望向管理节点或网关节点添加中继接口、以便使用link:../admin/configure-vlan-interfaces.html["VLAN 接口"]隔离属于不同应用程序或租户的流量。或者，您可能需要添加要在中使用的访问接口link:../admin/configure-high-availability-group.html["高可用性（ HA ）组"]。

要添加中继或访问接口，请参见以下内容：

* *VMware (安装节点后)*：link:../maintain/vmware-adding-trunk-or-access-interfaces-to-node.html["VMware ：向节点添加中继或访问接口"]
+
** *Red Hat Enterprise Linux (安装节点之前)*：link:../rhel/creating-node-configuration-files.html["创建节点配置文件"]
** *Ubuntu或Debian (安装节点之前)*：link:../ubuntu/creating-node-configuration-files.html["创建节点配置文件"]
** *RHEL、Ubuntu或Debian (安装节点后)*：link:../maintain/linux-adding-trunk-or-access-interfaces-to-node.html["Linux ：向节点添加中继或访问接口"]



