---
permalink: admin/increasing-metadata-reserved-space-setting.html 
sidebar: sidebar 
keywords: increase metadata reserved space setting 
summary: '如果存储节点满足特定的RAM和可用空间要求、则可以增加"元数据预留空间"系统设置。' 
---
= 增加元数据预留空间设置
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果存储节点满足特定的RAM和可用空间要求、则可以增加"元数据预留空间"系统设置。

.您需要的内容
* 您已使用登录到网格管理器link:web-browser-requirements.html["支持的 Web 浏览器"]。
* 你有link:admin-group-permissions.html["Root 访问权限或其他网格配置权限"]。


.关于此任务
您可以手动将系统范围的元数据预留空间设置增加到8 TB。

只有当以下两项陈述均为 true 时，才能增加系统范围的元数据预留空间设置的值：

* 系统中任何站点的存储节点均具有 128 GB 或更多 RAM 。
* 系统中任何站点的存储节点在存储卷 0 上都有足够的可用空间。


请注意，如果增加此设置，则会同时减少所有存储节点的存储卷 0 上可用于对象存储的空间。因此，您可能希望根据预期对象元数据要求将元数据预留空间设置为小于 8 TB 的值。


NOTE: 一般来说，最好使用较高的值，而不是较低的值。如果 " 元数据预留空间 " 设置过大，您可以稍后减小此设置。相比之下，如果稍后增加该值，系统可能需要移动对象数据以释放空间。

有关“元数据预留空间”设置如何影响特定存储节点上对象元数据存储的允许空间的详细说明，请参见link:managing-object-metadata-storage.html["管理对象元数据存储"]。

.步骤
. 确定当前的元数据预留空间设置。
+
.. 选择*配置* > *系统* > *存储设置*。
.. 注意*元数据保留空间*的值。


. 确保每个存储节点的存储卷 0 上有足够的可用空间来增加此值。
+
.. 选择*节点*。
.. 选择网格中的第一个存储节点。
.. 选择存储选项卡。
.. 在卷部分中，找到 * /var/local/rangedb/0* 条目。
.. 确认可用值等于或大于要使用的新值与当前元数据预留空间值之间的差值。
+
例如，如果元数据预留空间设置当前为 4 TB ，而您希望将其增加到 6 TB ，则可用值必须为 2 TB 或更大。

.. 对所有存储节点重复上述步骤。
+
*** 如果一个或多个存储节点没有足够的可用空间，则无法增加元数据预留空间值。请勿继续使用此操作步骤。
*** 如果每个存储节点在卷 0 上都有足够的可用空间，请转至下一步。




. 确保每个存储节点上至少有 128 GB 的 RAM 。
+
.. 选择*节点*。
.. 选择网格中的第一个存储节点。
.. 选择 * 硬件 * 选项卡。
.. 将光标悬停在 " 内存使用量 " 图表上。确保 * 总内存 * 至少为 128 GB 。
.. 对所有存储节点重复上述步骤。
+
*** 如果一个或多个存储节点没有足够的可用总内存，则无法增加元数据预留空间值。请勿继续使用此操作步骤。
*** 如果每个存储节点的总内存至少为 128 GB ，请转至下一步。




. 更新元数据预留空间设置。
+
.. 选择*配置* > *系统* > *存储设置*。
.. 选择*元数据保留空间*。
.. 输入新值。
+
例如，要输入 8 TB 作为支持的最大值，请输入 * 80000000000000000* （ 8 ，后跟 12 个零）

.. 选择 * 保存 * 。



