---
permalink: admin/managing-tenants.html 
sidebar: sidebar 
keywords: manage tenants, tenant account, what is a tenant 
summary: '租户帐户允许您使用简单存储服务\(S3\) REST API在StorageGRID系统中存储和检索对象。' 
---
= 什么是租户帐户？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
租户帐户允许您使用简单存储服务(S3) REST API在StorageGRID系统中存储和检索对象。


TIP: Swift详细信息已从此版本的文档站点中删除。请参阅。 https://docs.netapp.com/us-en/storagegrid-118/admin/managing-tenants.html["StorageGRID 11.8:管理租户"^]

作为网格管理员、您可以创建和管理S3客户端用于存储和检索对象的租户帐户。

每个租户帐户都具有联合组或本地组、用户、S3分段和对象。

租户帐户可用于按不同实体隔离存储的对象。例如，以下任一使用情形均可使用多个租户帐户：

* * 企业用例： * 如果您在企业应用程序中管理 StorageGRID 系统，则可能需要按组织中的不同部门隔离网格的对象存储。在这种情况下，您可以为营销部门，客户支持部门，人力资源部门等创建租户帐户。
+

NOTE: 如果您使用 S3 客户端协议，则可以使用 S3 存储桶和存储桶策略在企业各部门之间隔离对象。您不需要使用租户帐户。请参阅实施说明link:../s3/use-access-policies.html["S3存储分段和存储分段策略"]了解更多信息。

* * 服务提供商用例： * 如果您将 StorageGRID 系统作为服务提供商进行管理，则可以按要在网格上租用存储的不同实体来隔离网格的对象存储。在这种情况下，您将为公司 A ，公司 B ，公司 C 等创建租户帐户。


有关详细信息，请参见 link:../tenant/index.html["使用租户帐户"]。



== 如何创建租户帐户？

使用网格管理器创建租户帐户。创建租户帐户时，您可以指定以下信息：

* 基本信息、包括租户名称、客户端类型(S3)和可选存储配额。
* 租户帐户的权限、例如租户帐户是否可以使用S3平台服务、配置自己的身份源、使用S3 Select或使用网格联盟连接。
* 租户的初始root访问权限、具体取决于StorageGRID 系统是使用本地组和用户、身份联合还是单点登录(SSO)。


此外、如果S3租户帐户需要符合法规要求、您可以为StorageGRID 系统启用S3对象锁定设置。启用 S3 对象锁定后，所有 S3 租户帐户均可创建和管理合规的存储分段。



== 租户管理器的用途是什么？

创建租户帐户后、租户用户可以登录到租户管理器来执行如下任务：

* 设置身份联合(除非身份源与网格共享)
* 管理组和用户
* 使用网格联盟进行帐户克隆和跨网格复制
* 管理 S3 访问密钥
* 创建和管理S3存储分段
* 使用S3平台服务
* 使用 S3 Select
* 监控存储使用情况



TIP: 虽然S3租户用户可以使用租户管理器创建和管理S3访问密钥和存储分段、但他们必须使用S3客户端应用程序来加存和管理对象。有关详细信息、请参见。 link:../s3/index.html["使用S3 REST API"]
