---
permalink: admin/summary-ip-addresses-and-ports-for-client-connections.html 
sidebar: sidebar 
keywords: ip addresses for client, how to connect to storagegrid, ports, vip 
summary: '要存储或检索对象、S3客户端应用程序会连接到负载平衡器服务(包含在所有管理节点和网关节点上)或本地分发路由器(LDR)服务(包含在所有存储节点上)。' 
---
= 摘要：客户端连接的 IP 地址和端口
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
要存储或检索对象、S3客户端应用程序会连接到负载平衡器服务(包含在所有管理节点和网关节点上)或本地分发路由器(LDR)服务(包含在所有存储节点上)。

客户端应用程序可以使用网格节点的IP地址以及该节点上服务的端口号连接到StorageGRID。或者、您也可以为负载平衡节点创建高可用性(HA)组、以提供使用虚拟IP (VIP)地址的高可用性连接。如果要使用完全限定域名(FQDN)而不是IP或VIP地址连接到StorageGRID 、则可以配置DNS条目。

此表总结了客户端连接到 StorageGRID 的不同方式以及每种连接类型所使用的 IP 地址和端口。如果已创建负载平衡器端点和高可用性(HA)组、请参见<<从何处查找IP地址>>以在网格管理器中查找这些值。

[cols="1a,1a,1a,1a"]
|===
| 建立连接的位置 | 客户端连接到的服务 | IP 地址 | 端口 


 a| 
HA组
 a| 
负载平衡器
 a| 
HA 组的虚拟 IP 地址
 a| 
分配给负载平衡器端点的端口



 a| 
管理节点
 a| 
负载平衡器
 a| 
管理节点的 IP 地址
 a| 
分配给负载平衡器端点的端口



 a| 
网关节点
 a| 
负载平衡器
 a| 
网关节点的 IP 地址
 a| 
分配给负载平衡器端点的端口



 a| 
存储节点
 a| 
LDR
 a| 
存储节点的 IP 地址
 a| 
默认 S3 端口：

* HTTPS：18082
* HTTP：18084


|===


== 示例URL

要将客户端应用程序连接到网关节点HA组的负载平衡器端点、请使用如下所示的URL结构：

`https://_VIP-of-HA-group:LB-endpoint-port_`

例如、如果HA组的虚拟IP地址为192.0.2.5、负载平衡器端点的端口号为10443、则应用程序可以使用以下URL连接到StorageGRID ：

`\https://192.0.2.5:10443`



== 从何处查找IP地址

. 使用登录到网格管理器link:../admin/web-browser-requirements.html["支持的 Web 浏览器"]。
. 要查找网格节点的 IP 地址，请执行以下操作：
+
.. 选择*节点*。
.. 选择要连接到的管理节点，网关节点或存储节点。
.. 选择 * 概述 * 选项卡。
.. 在节点信息部分中，记下节点的 IP 地址。
.. 选择 * 显示更多 * 可查看 IPv6 地址和接口映射。
+
您可以建立从客户端应用程序到列表中任何 IP 地址的连接：

+
*** * eth0 ： * 网格网络
*** * eth1 ： * 管理网络（可选）
*** * eth2 ： * 客户端网络（可选）
+

NOTE: 如果您正在查看管理节点或网关节点，并且该节点是高可用性组中的活动节点，则 eth2 上会显示 HA 组的虚拟 IP 地址。





. 要查找高可用性组的虚拟 IP 地址，请执行以下操作：
+
.. 选择*配置* > *网络* > *高可用性组*。
.. 在表中，记下 HA 组的虚拟 IP 地址。


. 查找负载平衡器端点的端口号：
+
.. 选择*配置* > *网络* > *负载均衡器端点*。
.. 记下要使用的端点的端口号。
+

NOTE: 如果端口号为80或443、则仅在网关节点上配置端点、因为这些端口是在管理节点上预留的。所有其他端口都在网关节点和管理节点上进行配置。

.. 从表中选择端点的名称。
.. 确认*客户端类型*(S3)与要使用端点的客户端应用程序匹配。



