---
permalink: admin/viewing-network-traffic-metrics.html 
sidebar: sidebar 
keywords: network traffic, traffic classification policy, monitor traffic 
summary: '您可以通过查看"流量分类策略"页面中提供的图形来监控网络流量。' 
---
= 查看网络流量指标
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以通过查看"流量分类策略"页面中提供的图形来监控网络流量。

.开始之前
* 您已使用登录到网格管理器link:../admin/web-browser-requirements.html["支持的 Web 浏览器"]。
* 您拥有link:admin-group-permissions.html["root访问权限或租户帐户权限"]。


.关于此任务
对于任何现有流量分类策略、您可以查看负载平衡器服务的指标、以确定该策略是否成功限制网络中的流量。图形中的数据可以帮助您确定是否需要调整策略。

即使没有为流量分类策略设置限制，也会收集指标，并且图形可提供有用的信息来了解流量趋势。

.步骤
. 选择 * 配置 * > * 网络 * > * 流量分类 * 。
+
此时将显示"流量分类策略"页面、表中将列出现有策略。

. 选择要查看其指标的流量分类策略名称。
. 选择*Metrics *选项卡。
+
此时将显示流量分类策略图形。这些图形仅显示与选定策略匹配的流量的指标。

+
页面上包含以下图形。

+
** 请求速率：此图提供与所有负载平衡器处理的此策略匹配的带宽量。收到的数据包括所有请求的请求标头以及包含正文数据的响应的正文数据大小。Sent包括所有请求的响应标头以及响应中包含正文数据的请求的响应正文数据大小。
+

NOTE: 请求完成后、此图表仅显示带宽使用量。对于速度较慢或较大的对象请求、实际瞬时带宽可能与此图中报告的值不同。

** 错误响应率：此图提供了与此策略匹配的请求向客户端返回错误(HTTP状态代码>= 400)的大致速率。
** 平均请求持续时间(无错误)：此图形提供与此策略匹配的成功请求的平均持续时间。
** 策略带宽使用量：此图提供与所有负载平衡器处理的此策略匹配的带宽量。收到的数据包括所有请求的请求标头以及包含正文数据的响应的正文数据大小。Sent包括所有请求的响应标头以及响应中包含正文数据的请求的响应正文数据大小。


. 将光标置于折线图上方、可查看该图特定部分上的值弹出窗口。
. 选择指标标题下方的* Grafana DDashboard *以查看策略的所有图形。除了*Metrics *选项卡中的四个图形之外，您还可以查看另外两个图形：
+
** Write Request Rate by object size：与此策略匹配的放置/后置/删除请求的速率。单个单元格上的定位显示每秒的速率。悬停视图中显示的速率会被截断为整数、如果存储分段中存在非零请求、则可能会报告0。
** 按对象大小划分的读取请求速率：与此策略匹配的GET或HEAD请求的速率。单个单元格上的定位显示每秒的速率。悬停视图中显示的速率会被截断为整数、如果存储分段中存在非零请求、则可能会报告0。


. 或者，也可以从 * 支持 * 菜单访问这些图形。
+
.. 选择 * 支持 * > * 工具 * > * 指标 * 。
.. 从* Grafana *部分选择*交通分类政策*。
.. 从页面左上角的菜单中选择策略。
.. 将光标置于图形上方可查看一个弹出窗口、其中显示了样本的日期和时间、汇总到计数中的对象大小以及该时间段内每秒的请求数。
+
流量分类策略通过其 ID 进行标识。策略ID将在"流量分类策略"页面上列出。



. 分析图形以确定策略限制流量的频率以及是否需要调整策略。

