---
permalink: monitor/access-snmp-mib.html 
sidebar: sidebar 
keywords: mib, snmp, monitoring 
summary: MIB文件包含有关网格中节点的受管资源和服务属性的定义和信息。您可以访问用于定义StorageGRID 对象和通知的MIB文件。这些文件可用于监控网格。 
---
= 访问MIB文件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MIB文件包含有关网格中节点的受管资源和服务属性的定义和信息。您可以访问用于定义StorageGRID 对象和通知的MIB文件。这些文件可用于监控网格。

有关SNMP和MIB文件的详细信息、请参见link:using-snmp-monitoring.html["使用 SNMP 监控"]。



== 访问MIB文件

按照以下步骤访问MIB文件。

.步骤
. 选择*配置* > *监控* > *SNMP 代理*。
. 在SNMP代理页面上、选择要下载的文件：
+
** *NetApp-STORAGEGRID-MIB.TXT*：定义可在所有管理节点上访问的警报表和通知(陷阱)。
** *ES-NetApp-06-MIB.MIB*：为基于E系列的设备定义对象和通知。
** *mib_1_10.zip*：使用BMC接口为设备定义对象和通知。
+

TIP: 您还可以在任何StorageGRID节点上访问以下位置的MIB文件： `/usr/share/snmp/mibs`



. 要从MIB文件中提取StorageGRID OID、请执行以下操作：
+
.. 获取StorageGRID MIB根目录的OID：
+
`root@user-adm1:~ # snmptranslate -On -IR storagegrid`

+
结果： `.1.3.6.1.4.1.789.28669` (`28669`始终为StorageGRID的OID)

.. 整个树中StorageGRID OID的gep (用于 `paste`连接行)：
+
`root@user-adm1:~ # snmptranslate -Tso | paste -d " " - - | grep 28669`

+

TIP:  `snmptranslate`命令提供了许多可用于浏览MIB的选项。此命令可在任何StorageGRID 节点上使用。







== MIB文件内容

所有对象都位于StorageGRID OID下。

[cols="1a,1a,2a"]
|===
| 对象名称 | 对象ID (OID) | 说明 


| .iso.org.dod.internet。+私有企业。+ NetApp.storagegrid | .1.3.6.1.4.1.789.28669  a| 
NetApp StorageGRID实体的MIB模块。

|===


== MIB对象

[cols="1a,1a,1a,1a,1a,2a"]
|===
| 对象名称 | 对象ID (OID) | 键入 | 使用权 | MIB 模块 | 说明 


| 活动的计数 | 1.3.6.1.4.1。+ 789.28669.1.3  a| 
Integer32
 a| 
只读
 a| 
NETAPP-STORAGEGRID-MIB
 a| 
activeAlert表中活动警报的数量。



| 活动的活动的表 | 1.3.6.1.4.1。+ 789.28669.1.4  a| 
ActiveAlertEntry 的序列
 a| 
不可访问
 a| 
NETAPP-STORAGEGRID-MIB
 a| 
StorageGRID 中活动警报的表。



| 活动警报条目 | .1.3.6.1.4.1.  + 789.28669.1.4.1  a| 
顺序
 a| 
不可访问
 a| 
NETAPP-STORAGEGRID-MIB
 a| 
单个StorageGRID警报，按警报 ID 索引。



| 活动的标识号 | 1.3.6.1.4.1。+ 789.28669.1.4.1.1  a| 
八位字节串
 a| 
只读
 a| 
NETAPP-STORAGEGRID-MIB
 a| 
警报的ID。仅在当前一组活动警报中是唯一的。



| 活动报告名称 | 1.3.6.1.4.1。+ 789.28669.1.4.1.2  a| 
八位字节串
 a| 
只读
 a| 
NETAPP-STORAGEGRID-MIB
 a| 
警报的名称。



| 已执行的活动的活动的实例 | 1.3.6.1.4.1。+ 789.28669.1.4.1.3  a| 
八位字节串
 a| 
只读
 a| 
NETAPP-STORAGEGRID-MIB
 a| 
生成警报的实体的名称、通常为节点名称。



| 活动告警严重性 | 1.3.6.1.4.1。+ 789.28669.1.4.1.4  a| 
八位字节串
 a| 
只读
 a| 
NETAPP-STORAGEGRID-MIB
 a| 
警报的严重性。



| 活动的起始时间 | 1.3.6.1.4.1。+ 789.28669.1.4.1.5  a| 
日期和时间
 a| 
只读
 a| 
NETAPP-STORAGEGRID-MIB
 a| 
触发警报的时间。

|===