---
permalink: monitor/collecting-log-files-and-system-data.html 
sidebar: sidebar 
keywords: how to collect system data, how to collect logs 
summary: 您可以检索StorageGRID日志文件和系统数据（包括配置数据），并将其发送给技术支持。 
---
= 收集日志文件和系统数据
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以检索StorageGRID日志文件和系统数据（包括配置数据），并将其发送给技术支持。

.开始之前
* 您已使用任意管理节点登录到网格管理器link:../admin/web-browser-requirements.html["支持的 Web 浏览器"]。
* 您拥有 link:../admin/admin-group-permissions.html["特定访问权限"]。
* 您具有配置密码短语。


.关于此任务
使用网格管理器来收集link:logs-files-reference.html["日志文件"]、系统数据和来自任何网格节点的您选择的时间段的配置数据。数据被收集并归档在 `.tar.gz`然后您可以将其下载到本地计算机或发送给技术支持。

或者，您可以更改审计日志的目标并将审计信息发送到外部系统日志服务器。当配置外部系统日志服务器时，将继续生成和存储审计记录的本地日志。看link:../monitor/configure-log-management.html["配置日志管理和外部系统日志服务器"] 。

.步骤
. 选择*支持* > *工具* > *日志收集*。显示节点表。
. 选择要收集日志文件的网格节点。
+
您可以按节点名称、站点和节点类型进行排序。站点和节点类型列包含按单个站点和节点类型选择的过滤器。

. 选择 * 继续 * 。
. 选择要包含在日志文件中的数据的日期和时间范围。
+
如果您选择很长的时间段或从大型网格中的所有节点收集日志，则日志存档可能会变得太大而无法存储在节点上，或者太大而无法由管理节点收集进行下载。如果发生任何一种情况，请使用较小的数据集重新开始日志收集。

. 选择要收集的日志类型。
+
** *应用程序日志*：技术支持最常用于故障排除的应用程序特定日志。收集的日志是可用应用程序日志的子集。
** *审计日志*：包含系统正常运行期间生成的审计消息的日志。
** *网络跟踪*：用于网络调试的日志。
** *Prometheus 数据库*：来自所有节点上的服务的时间序列指标。


. 或者，使用 *Notes* 文本框输入有关您正在收集的日志文件的注释。
+
您可以使用这些注释提供有关提示您收集日志文件的问题的技术支持信息。您的注释将与有关日志文件收集的其他信息一起添加到名为的文件中 `info.txt`。该 `info.txt`文件将保存在日志文件归档包中。

. 在 *Provisioning passphrase* 文本框中，输入StorageGRID系统的配置密码。
. 选择*收集日志*。
+
您可以使用日志收集页面来监控每个网格节点的日志文件收集进度。

+
如果您收到有关日志大小的错误消息，请尝试收集较短时间段或较少节点的日志。

. 如果日志收集失败：
+
** 如果出现“日志收集失败”消息，您可以重试日志收集或完成会话而无需重试。
** 如果出现“日志收集部分失败”消息，您可以重试日志收集、完成会话、下载部分日志文件或将部分日志文件发送到AutoSupport。


. 当日志文件收集完成时：
+
** 选择*下载*下载 `.tar.gz`文件。
** 选择“发送至AutoSupport”以发送 `.tar.gz`文件发送给技术支持。
+
这 `.tar.gz`文件包含所有成功收集日志的网格节点的所有日志文件。合并后的 `.tar.gz`文件包含每个网格节点的一个日志文件存档。

+
AutoSupport软件包的主题是 `USER_TRIGGERED_SUPPORT_BUNDLE`。



. 选择 * 完成 * 。
+

CAUTION: 这 `.tar.gz`当您选择*完成*时，文件将被删除。请确保您先下载或发送该文件。


