---
permalink: monitor/collecting-log-files-and-system-data.html 
sidebar: sidebar 
keywords: how to collect system data, how to collect logs 
summary: '您可以检索StorageGRID日志文件和系统数据(包括配置数据)、并将其发送给技术支持。' 
---
= 收集日志文件和系统数据
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以检索StorageGRID日志文件和系统数据(包括配置数据)、并将其发送给技术支持。

.开始之前
* 您已使用登录到主管理节点上的网格管理器link:../admin/web-browser-requirements.html["支持的 Web 浏览器"]。
* 您拥有 link:../admin/admin-group-permissions.html["特定访问权限"]。
* 您具有配置密码短语。


.关于此任务
使用网格管理器可以link:logs-files-reference.html["日志文件"]从任意网格节点收集所选时间段内的、系统数据和配置数据。数据会收集并归档在一个文件中 `.tar.gz`、然后下载到本地计算机或发送给技术支持。

您也可以更改审核日志的目标并将审核信息发送到外部系统日志服务器。配置外部系统日志服务器后，仍会生成并存储审核记录的本地日志。请参阅。 link:../monitor/configure-audit-messages.html["配置审核消息和外部系统日志服务器"]

.步骤
. 选择 * 支持 * > * 工具 * > * 日志 * 。此时将显示一个节点表。
. 选择要收集日志文件的网格节点。
+
您可以按节点名称、站点和节点类型进行排序。"站点"和"节点类型"列包含用于按各个站点和节点类型进行选择的筛选器。

. 选择 * 继续 * 。
. 选择要包含在日志文件中的数据的日期和时间范围。
+
如果选择很长的时间段或从大型网格中的所有节点收集日志，则日志归档可能会变得过大，无法存储在节点上，或者可能会变得过大，无法收集到主管理节点以供下载。如果发生上述任一情况、请使用一组较小的数据重新启动日志收集。

. 选择要收集的日志类型。
+
** *应用程序日志*：技术支持最常使用的应用程序特定日志进行故障排除。收集的日志是可用应用程序日志的一部分。
** *Audit logs*：包含在正常系统操作期间生成的审核消息的日志。
** *Network trace*:用于网络调试的日志。
** *Prometheus数据库*：所有节点上的服务的时间序列指标。


. (可选)使用*Notes*文本框输入有关正在收集的日志文件的注释。
+
您可以使用这些注释提供有关提示您收集日志文件的问题的技术支持信息。您的注释将与有关日志文件收集的其他信息一起添加到名为的文件中 `info.txt`。该 `info.txt`文件将保存在日志文件归档包中。

. 在*配置密码短语*文本框中，输入StorageGRID系统的配置密码短语。
. 选择*收集日志*。
+
您可以使用日志页面监控每个网格节点的日志文件收集进度。

+
如果您收到有关日志大小的错误消息，请尝试收集较短时间段或较少节点的日志。

. 如果日志收集失败：
+
** 如果显示"Log Collection failed (日志收集失败)"消息、您可以重试日志收集或完成会话、而无需重试。
** 如果出现"日志收集部分失败"消息、您可以重试日志收集、完成会话、下载部分日志文件或将部分日志文件发送到AutoSupport。


. 日志文件收集完成后：
+
** 选择*Download*下载 `.tar.gz`文件。
** 选择*Send to AutoSupport (发送到Windows)*将文件发送 `.tar.gz`给技术支持。
+
此 `.tar.gz`文件包含已成功收集日志的所有网格节点中的所有日志文件。组合 `.tar.gz`文件包含每个网格节点的一个日志文件归档。

+
AutoSupport软件包的主题是 `USER_TRIGGERED_SUPPORT_BUNDLE`。



. 选择 * 完成 * 。
+

CAUTION:  `.tar.gz`选择*完成*后，文件将被删除。确保先下载或发送文件。


