---
permalink: monitor/configuring-snmp-agent.html 
sidebar: sidebar 
keywords: snmp agent, mib, trap, inform 
summary: 您可以将StorageGRID SNMP代理配置为使用第三方SNMP管理系统进行只读MIB访问和通知。 
---
= 配置 SNMP 代理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以将StorageGRID SNMP代理配置为使用第三方SNMP管理系统进行只读MIB访问和通知。

.开始之前
* 您已使用登录到网格管理器link:../admin/web-browser-requirements.html["支持的 Web 浏览器"]。
* 您拥有link:../admin/admin-group-permissions.html["root访问权限"]。


.关于此任务
StorageGRID SNMP代理支持SNMPv1、SNMPv2c和SNMPv3。您可以为代理配置一个或多个版本。对于SNMPv3、仅支持用户安全模型(User Security Model、USM)身份验证。

网格中的所有节点都使用相同的SNMP配置。



== 指定基本配置

首先、启用StorageGRID SMNP代理并提供基本信息。

.步骤
. 选择 * 配置 * > * 监控 * > * SNMP 代理 * 。
+
此时将显示SNMP代理页面。

. 要在所有网格节点上启用SNMP代理，请选中*Enable SNMP*复选框。
. 在Basic configuration部分中输入以下信息。
+
[cols="1a,2a"]
|===
| 字段 | 说明 


 a| 
系统联系人
 a| 
可选。StorageGRID系统的主要联系人、在SNMP消息中以sysContact的形式返回。

系统联系人通常是一个电子邮件地址。此值用于适用场景StorageGRID系统中的所有节点。*系统联系人*最多可以包含255个字符。



 a| 
系统位置
 a| 
可选。StorageGRID系统的位置、在SNMP消息中以sysLocation的形式返回。

系统位置可以是任何有助于确定StorageGRID系统所在位置的信息。例如，您可以使用设施的街道地址。此值用于适用场景StorageGRID系统中的所有节点。*系统位置*最多可以是255个字符。



 a| 
启用SNMP代理通知
 a| 
** 如果选中此选项、StorageGRID SNMP代理将发送陷阱和通知通知。
** 如果未选中、则SNMP代理支持只读MIB访问、但不会发送任何SNMP通知。




 a| 
启用身份验证陷阱
 a| 
如果选中此选项、则StorageGRID SNMP代理会在收到未经正确身份验证的协议消息时发送身份验证陷阱。

|===




== 输入社区字符串

如果使用SNMPv1或SNMPv2c、请完成社区字符串部分。

当管理系统查询 StorageGRID MIB 时，它会发送一个社区字符串。如果社区字符串与此处指定的值之一匹配，则 SNMP 代理会向管理系统发送响应。

.步骤
. 对于*只读社区*，可选择输入社区字符串，以允许对IPv4和IPv6代理地址进行只读MIB访问。
+

TIP: 为确保StorageGRID系统的安全性、请勿使用"public"作为社区字符串。如果将此字段留空、SNMP代理将使用StorageGRID系统的网格ID作为社区字符串。

+
每个社区字符串最多可以包含32个字符、并且不能包含空格字符。

. 选择*添加其他社区字符串*以添加其他字符串。
+
最多允许五个字符串。





== [[SELECT陷阱目标]]创建陷阱目标

使用其他配置部分中的陷阱目标选项卡为StorageGRID陷阱或通知定义一个或多个目标。如果启用SNMP代理并选择*保存*，则在触发警报时，StorageGRID会向每个定义的目标发送通知。此外，还会为受支持的 MIB-II 实体（例如 ifdown 和 coldstart ）发送标准通知。

.步骤
. 对于*默认陷阱社区*字段、可选择输入要用于SNMPv1或SNMPv2陷阱目标的默认社区字符串。
+
定义特定陷阱目标时、您可以根据需要提供不同的("自定义")社区字符串。

+
*默认陷阱社区*最多可包含32个字符、不能包含空格字符。

. 要添加陷阱目标，请选择*Cree*。
. 选择要用于此陷阱目标的SNMP版本。
. 完成所选版本的创建陷阱目标表单。
+
[role="tabbed-block"]
====
.SNMPv1
--
如果选择SNMPv1作为版本、请填写这些字段。

[cols="1a,2a"]
|===
| 字段 | 说明 


 a| 
键入
 a| 
必须为SNMPv1陷阱。



 a| 
主机
 a| 
用于接收陷阱的IPv4或IPv6地址或完全限定域名(FQDN)。



 a| 
端口
 a| 
使用162、这是SNMP陷阱的标准端口、除非您必须使用其他值。



 a| 
协议
 a| 
使用UDP、这是标准SNMP陷阱协议、除非您需要使用TCP。



 a| 
社区字符串
 a| 
使用默认陷阱团体(如果已指定)、或者为此陷阱目标输入自定义社区字符串。

自定义社区字符串最多可以包含32个字符、并且不能包含空格。

|===
--
.SNMPv2c
--
如果选择SNMPv2c作为版本、请填写这些字段。

[cols="1a,2a"]
|===
| 字段 | 说明 


 a| 
键入
 a| 
目标将用于陷阱还是通知。



 a| 
主机
 a| 
用于接收陷阱的IPv4或IPv6地址或FQDN。



 a| 
端口
 a| 
请使用162、这是SNMP陷阱的标准端口、除非您必须使用其他值。



 a| 
协议
 a| 
使用UDP、这是标准SNMP陷阱协议、除非您需要使用TCP。



 a| 
社区字符串
 a| 
使用默认陷阱团体(如果已指定)、或者为此陷阱目标输入自定义社区字符串。

自定义社区字符串最多可以包含32个字符、并且不能包含空格。

|===
--
.SNMPv3
--
如果选择SNMPv3作为版本、请填写这些字段。

[cols="1a,2a"]
|===
| 字段 | 说明 


 a| 
键入
 a| 
目标将用于陷阱还是通知。



 a| 
主机
 a| 
用于接收陷阱的IPv4或IPv6地址或FQDN。



 a| 
端口
 a| 
请使用162、这是SNMP陷阱的标准端口、除非您必须使用其他值。



 a| 
协议
 a| 
使用UDP、这是标准SNMP陷阱协议、除非您需要使用TCP。



 a| 
USM用户
 a| 
要用于身份验证的USM用户。

** 如果选择了 * 陷阱 * ，则仅显示不具有权威引擎 ID 的 USM 用户。
** 如果选择 * 通知 * ，则仅显示具有权威引擎 ID 的 USM 用户。
** 如果未显示任何用户：
+
... 创建并保存陷阱目标。
... 转到<<create-usm-users,创建USM用户>>并创建用户。
... 返回到陷阱目标选项卡，从表中选择保存的目标，然后选择*Edit*。
... 选择用户。




|===
--
====
. 选择 * 创建 * 。
+
此时将创建陷阱目标并将其添加到表中。





== 创建代理地址

(可选)使用“其他配置”部分中的“业务代表地址”选项卡指定一个或多个“侦听地址”。这些地址是SNMP代理可以接收查询的StorageGRID地址。

如果不配置代理地址、则所有StorageGRID 网络上的默认侦听地址均为UDP端口161。

.步骤
. 选择 * 创建 * 。
. 输入以下信息。
+
[cols="1a,2a"]
|===
| 字段 | 说明 


 a| 
互联网协议
 a| 
此地址将使用IPv4还是IPv6。

默认情况下， SNMP 使用 IPv4 。



 a| 
传输协议
 a| 
此地址将使用UDP还是TCP。

默认情况下， SNMP 使用 UDP 。



 a| 
StorageGRID网络
 a| 
代理将侦听哪个StorageGRID网络。

** 网格、管理和客户端网络：SNMP代理将侦听所有三个网络上的查询。
** 网格网络
** 管理网络
** 客户端网络
+
*注意*：如果使用客户端网络处理不安全的数据，并为客户端网络创建代理地址，请注意SNMP流量也不安全。





 a| 
端口
 a| 
(可选) SNMP代理应侦听的端口号。

SNMP 代理的默认 UDP 端口为 161 ，但您可以输入任何未使用的端口号。

*注意*：保存SNMP代理时，StorageGRID会自动打开内部防火墙上的代理地址端口。您必须确保任何外部防火墙允许访问这些端口。

|===
. 选择 * 创建 * 。
+
此时将创建代理地址并将其添加到表中。





== [[crea-usM-user]]创建USM用户

如果使用SNMPv3、请使用其他配置部分中的USM用户选项卡定义有权查询MIB或接收陷阱和通知的USM用户。


NOTE: SNMPv3 _INFORM _目标必须具有具有引擎ID的用户。SNMPv3 _陷阱_目标不能包含具有引擎ID的用户。

如果您仅使用SNMPv1或SNMPv2c、则这些步骤不适用。

.步骤
. 选择 * 创建 * 。
. 输入以下信息。
+
[cols="1a,2a"]
|===
| 字段 | 说明 


 a| 
用户名
 a| 
此USM用户的唯一名称。

用户名最多可以包含32个字符、且不能包含空格字符。创建用户后、无法更改此用户名。



 a| 
只读MIB访问
 a| 
如果选中、则此用户应对MIB具有只读访问权限。



 a| 
权威引擎ID
 a| 
如果要在通知目标中使用此用户、则为该用户的权威引擎ID。

输入10到64个十六进制字符(5到32字节)、不含空格。要在陷阱目标中选择用于通知的USM用户需要此值。要在陷阱目标中为陷阱选择的USM用户不允许使用此值。

*注意*：如果您选择了*只读MIB访问*，则不会显示此字段，因为具有只读MIB访问权限的USM用户不能具有引擎ID。



 a| 
安全级别
 a| 
USM用户的安全级别：

** * authPriv* ：此用户与身份验证和隐私（加密）通信。您必须指定身份验证协议和密码以及隐私协议和密码。
** * authNoPriv* ：此用户使用身份验证进行通信，并且没有隐私（无加密）。您必须指定身份验证协议和密码。




 a| 
身份验证协议
 a| 
始终设置为SHA、这是唯一支持的协议(HMAC-SHA-96)。



 a| 
密码
 a| 
此用户将用于身份验证的密码。



 a| 
隐私协议
 a| 
仅当您选择了*authPriv*并始终设置为AES时显示，AES是唯一支持的隐私协议。



 a| 
密码
 a| 
仅在选择了*authSv*时显示。此用户用于保护隐私的密码。

|===
. 选择 * 创建 * 。
+
此时将创建 USM 用户并将其添加到表中。

. 完成SNMP代理配置后，选择*Save*。
+
新的 SNMP 代理配置将变为活动状态。


