---
permalink: monitor/monitoring-load-balancing-operations.html 
sidebar: sidebar 
keywords: load balancing, monitoring 
summary: 如果您使用负载平衡器管理客户端与 StorageGRID 的连接，则应在最初配置系统之后以及在进行任何配置更改或执行扩展之后监控负载平衡操作。 
---
= 监控负载平衡操作
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您使用负载平衡器管理客户端与 StorageGRID 的连接，则应在最初配置系统之后以及在进行任何配置更改或执行扩展之后监控负载平衡操作。

.关于此任务
您可以在管理节点、网关节点或外部第三方负载平衡器上使用负载平衡器服务在多个存储节点之间分布客户端请求。

配置负载平衡后，您应确认对象载入和检索操作在存储节点之间均匀分布。均匀分布的请求可确保 StorageGRID 始终响应负载下的客户端请求，并有助于保持客户端性能。

如果您在主动备份模式下为网关节点或管理节点配置了一个高可用性（ HA ）组，则该组中只有一个节点会主动分发客户端请求。

有关详细信息，请参见 link:../admin/configuring-client-connections.html["配置S3客户端连接"]。

.步骤
. 如果S3客户端使用负载平衡器服务进行连接、请检查管理节点或网关节点是否按预期主动分布流量：
+
.. 选择 * 节点 * 。
.. 选择网关节点或管理节点。
.. 在*Overview*选项卡上，检查节点接口是否位于HA组中，以及节点接口是否具有Primary角色。
+
角色为Primary的节点以及不属于HA组的节点应主动向客户端分发请求。

.. 对于应主动分发客户端请求的每个节点，请选择link:viewing-load-balancer-tab.html["负载平衡器选项卡"]。
.. 查看上一周的负载平衡器请求流量图表，以确保节点一直在主动分发请求。
+
主动备份 HA 组中的节点可能会不时承担备份角色。在此期间、节点不会分发客户端请求。

.. 查看上周的负载平衡器传入请求速率图表，查看节点的对象吞吐量。
.. 对 StorageGRID 系统中的每个管理节点或网关节点重复上述步骤。
.. (可选)使用流量分类策略查看负载平衡器服务提供的流量的更详细分析。


. 验证这些请求是否均匀分布到存储节点。
+
.. 选择 * 存储节点 _* > * LDR* > * HTTP * 。
.. 查看 * 当前已建立的传入会话 * 的数量。
.. 对网格中的每个存储节点重复上述步骤。
+
所有存储节点的会话数应大致相等。




