---
permalink: monitor/monitoring-information-lifecycle-management.html 
sidebar: sidebar 
keywords: lifecycle management, lifecycle, monitoring, ILM, information lifecycle management 
summary: 信息生命周期管理 \ （ ILM ）系统可为网格中存储的所有对象提供数据管理。您必须监控ILM操作、以了解网格是否可以处理当前负载、或者是否需要更多资源。 
---
= 监控信息生命周期管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
信息生命周期管理（ ILM ）系统可为网格中存储的所有对象提供数据管理。您必须监控ILM操作、以了解网格是否可以处理当前负载、或者是否需要更多资源。

.关于此任务
StorageGRID系统通过应用活动ILM策略来管理对象。ILM策略和关联的ILM规则可确定创建的副本数、创建的副本类型、副本放置位置以及每个副本的保留时间长度。

对象加载和其他与对象相关的活动可能会超过StorageGRID 评估ILM的速率、从而导致系统对无法近乎实时地执行ILM放置指令的对象进行排队。您应监控StorageGRID是否与客户端操作保持一致。



== 使用Grid Manager信息板选项卡

.步骤
使用网格管理器信息板上的ILM选项卡监控ILM操作：

. 登录到网格管理器。
. 从信息板中、选择ILM选项卡、并记下ILM队列(对象)卡和ILM评估速率卡上的值。
+
信息板上的ILM队列(对象)卡可能会出现临时峰值。但是、如果队列持续增加而从未减少、网格需要更多资源才能高效运行：要么增加存储节点、要么增加ILM策略将对象放置在远程位置的网络带宽。





== 使用节点页面

.步骤
此外，请使用*N节点*页调查ILM队列：


NOTE: 在未来的StorageGRID版本中，*节点*页面上的图表将替换为相应的信息板卡。

. 选择 * 节点 * 。
. 选择 * 网格名称 _* > * ILM * 。
. 将光标置于ILM队列图上方、可查看在给定时间点的以下属性值：
+
** * 已排队的对象（来自客户端操作） * ：由于客户端操作（例如载入）而等待 ILM 评估的对象总数。
** * 已排队的对象（从所有操作） * ：等待 ILM 评估的对象总数。
** * 扫描速率（对象 / 秒） * ：为 ILM 扫描网格中的对象并使其排队的速率。
** * 评估速率（对象 / 秒） * ：根据网格中的 ILM 策略评估对象的当前速率。


+

NOTE: ILM队列部分仅适用于网格。此信息不会显示在站点或存储节点的 "ILM " 选项卡上。

. 在 "ILM Queue" 部分中，查看以下属性。
+
** *扫描期限-估计*：完成对所有对象的完整ILM扫描的估计时间。
+

NOTE: 完全扫描并不能保证 ILM 已应用于所有对象。

** *已尝试修复*：已尝试对复制数据执行的对象修复操作的总数。每当存储节点尝试修复高风险对象时，此计数都会递增。如果网格繁忙，高风险 ILM 修复会优先处理。
+
如果修复后复制失败，则同一对象修复可能会再次增加。+在监控存储节点卷恢复进度时、这些属性非常有用。如果尝试的维修次数停止增加、并且已完成完全扫描、则修复可能已完成。



. 或者，提交和 `storagegrid_ilm_repairs_attempted`的Prometheus查询 `storagegrid_ilm_scan_period_estimated_minutes`。

