---
permalink: maintain/considerations-for-decommissioning-storage-nodes.html 
sidebar: sidebar 
keywords: storage node decommission, considerations, appliance node clone 
summary: 在停用存储节点之前、请考虑是否可以克隆此节点。然后、如果您决定停用此节点、请查看StorageGRID在停用操作步骤期间如何管理对象和元数据。 
---
= 停用存储节点的注意事项
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在停用存储节点之前、请考虑是否可以克隆此节点。然后、如果您决定停用此节点、请查看StorageGRID在停用操作步骤期间如何管理对象和元数据。



== 何时克隆节点而不是停用节点

如果要将旧设备存储节点更换为新设备或更大的设备、请考虑克隆设备节点、而不是在扩展中添加新设备、然后停用旧设备。

通过设备节点克隆、您可以轻松地将现有设备节点更换为同一StorageGRID站点上的兼容设备。克隆过程会将所有数据传输到新设备、将新设备置于运行状态、并使旧设备处于预安装状态。

如果需要，您可以克隆设备节点：

* 更换即将达到使用寿命的产品。
* 升级现有节点以利用改进的设备技术。
* 增加网格存储容量，而不更改 StorageGRID 系统中的存储节点数。
* 提高存储效率、例如通过更改RAID模式。


有关详细信息、请参见。 https://docs.netapp.com/us-en/storagegrid-appliances/commonhardware/how-appliance-node-cloning-works.html["设备节点克隆"^]



== 已连接存储节点的注意事项

查看停用已连接存储节点的注意事项。

* 在一个 " 停用节点 " 操作步骤 中停用的存储节点不应超过 10 个。
* 系统必须始终包括足够多的存储节点以满足操作要求，包括link:understanding-adc-service-quorum.html["ADC仲裁"]和活动link:reviewing-ilm-policy-and-storage-configuration.html["ILM策略"]。要满足此限制，您可能需要在扩展操作中添加新的存储节点，然后才能停用现有存储节点。
+
在包含基于软件的纯元数据节点的网格中停用存储节点时、请务必小心谨慎。如果停用配置为存储_Both _对象和元数据的所有节点、则会从网格中删除存储对象的功能。有关纯元数据存储节点的详细信息、请参见link:../primer/what-storage-node-is.html#types-of-storage-nodes["存储节点的类型"]。

* 删除存储节点后、将通过网络传输大量对象数据。尽管这些传输不会影响正常系统操作、但它们会影响StorageGRID系统占用的网络带宽总量。
* 与正常系统操作相关的任务相比，与存储节点停用相关的任务的优先级更低。这意味着停用不会干扰 StorageGRID 系统的正常运行，也不需要计划系统在一段时间内处于非活动状态。由于停用是在后台执行的，因此很难估计完成此过程需要多长时间。通常，在系统处于静默状态或一次仅删除一个存储节点时，停用速度会更快。
* 停用存储节点可能需要数天或数周时间。相应地规划此操作步骤 。尽管停用过程不会影响系统运行，但它会限制其他过程。通常，在删除网格节点之前，您应执行任何计划内的系统升级或扩展。
* 如果您需要在删除存储节点期间执行另一个维护过程、则可以在另一过程完成后继续执行link:pausing-and-resuming-decommission-process-for-storage-nodes.html["暂停停用操作步骤"]。
+

NOTE: 只有在达到 ILM 评估或纠删编码的数据停用阶段时， * 暂停 * 按钮才会启用；但是， ILM 评估（数据迁移）将继续在后台运行。

* 正在运行停用任务时、无法在任何网格节点上运行数据修复操作。
* 在停用存储节点期间、不应对ILM策略进行任何更改。
* 要永久安全地删除数据、您必须在停用操作步骤完成后擦除存储节点的驱动器。




== 断开连接的存储节点的注意事项

查看停用已断开连接的存储节点的注意事项。

* 切勿停用已断开连接的节点、除非您确定该节点无法联机或恢复。
+

CAUTION: 如果您认为可以从节点中恢复对象数据、请勿执行此操作步骤。请联系技术支持以确定是否可以进行节点恢复。

* 停用已断开连接的存储节点时、StorageGRID会使用其他存储节点中的数据重建已断开连接的节点上的对象数据和元数据。
* 如果停用多个断开连接的存储节点、可能会发生数据丢失。如果没有足够的对象副本，纠删编码片段或对象元数据保持可用，则系统可能无法重建数据。在使用基于软件的纯元数据节点的网格中停用存储节点时、停用配置为同时存储对象和元数据的所有节点会从网格中删除所有对象存储。有关纯元数据存储节点的详细信息、请参见link:../primer/what-storage-node-is.html#types-of-storage-nodes["存储节点的类型"]。
+

CAUTION: 如果您有多个无法恢复的已断开连接的存储节点、请联系技术支持以确定最佳操作方案。

* 停用已断开连接的存储节点时， StorageGRID 会在停用过程结束时启动数据修复作业。这些作业会尝试重建已断开连接的节点上存储的对象数据和元数据。
* 停用已断开连接的存储节点时，停用操作步骤 的完成速度相对较快。但是、数据修复作业可能需要数天或数周才能运行、并且不受停用操作步骤 的监控。您必须手动监控这些作业并根据需要重新启动它们。请参阅。 link:checking-data-repair-jobs.html["检查数据修复作业"]
* 如果停用的存储节点已断开连接，而该存储节点包含某个对象的唯一副本，则该对象将丢失。只有当当前连接的存储节点上至少存在一个复制副本或足够多的纠删编码片段时，数据修复作业才能重建和恢复对象。

