---
permalink: maintain/copying-audit-logs-from-failed-non-primary-admin-node.html 
sidebar: sidebar 
keywords: storagegrid, audit log, copy audit log, copying audit log, non-primary admin node, non primary admin node 
summary: 如果您能够从出现故障的管理节点复制审核日志，则应保留这些日志以维护网格中的系统活动和使用情况记录。您可以在恢复的非主管理节点启动并运行后将保留的审核日志还原到该节点。 
---
= 从出现故障的非主管理节点复制审核日志
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您能够从出现故障的管理节点复制审核日志，则应保留这些日志以维护网格中的系统活动和使用情况记录。您可以在恢复的非主管理节点启动并运行后将保留的审核日志还原到该节点。

此操作步骤 会将审核日志文件从故障管理节点复制到单独网格节点上的临时位置。然后，可以将这些保留的审核日志复制到替代管理节点。审核日志不会自动复制到新的管理节点。

根据故障类型，您可能无法从发生故障的管理节点复制审核日志。如果部署只有一个管理节点，则恢复的管理节点将开始在新的空文件中将事件记录到审核日志中，并且先前记录的数据将丢失。如果部署包含多个管理节点，则可以从另一个管理节点恢复审核日志。


NOTE: 如果现在无法在故障管理节点上访问审核日志、您可以稍后访问这些日志、例如、在主机恢复之后。

. 如果可能，请登录到出现故障的管理节点。否则，请登录到主管理节点或其他管理节点（如果有）。
+
.. 输入以下命令： `ssh admin@grid_node_IP`
.. 输入文件中列出的密码 `Passwords.txt`。
.. 输入以下命令切换到root： `su -`
.. 输入文件中列出的密码 `Passwords.txt`。


+
当您以root用户身份登录时，提示符将从更 `$`改为 `#`。

. 停止AMS服务以防止其创建新日志文件：``service ams stop``
. 导航到审核导出目录：
+
`cd /var/local/audit/export/`

. 将源audit.log文件重命名为唯一编号的文件名。例如，将audit.log文件重命名为 `2023-10-25.txt.1`。
+
[listing]
----
ls -l
mv audit.log 2023-10-25.txt.1
----
. 重新启动AMS服务： `service ams start`
. 创建目录以将所有审核日志文件复制到单独网格节点上的临时位置： `ssh admin@grid_node_IP mkdir -p /var/local/tmp/saved-audit-logs`
+
出现提示时，输入 admin 的密码。

. 将所有审核日志文件复制到临时位置： `scp -p * admin@grid_node_IP:/var/local/tmp/saved-audit-logs`
+
出现提示时，输入 admin 的密码。

. 以root身份注销： `exit`

