---
permalink: maintain/how-site-recovery-is-performed-by-technical-support.html 
sidebar: sidebar 
keywords: storagegrid, site recovery, technical support, tech support 
summary: 如果整个 StorageGRID 站点出现故障或多个存储节点出现故障，您必须联系技术支持。技术支持将评估您的情况，制定恢复计划，然后按照符合您业务目标的方式恢复故障节点或站点，优化恢复时间并防止不必要的数据丢失。 
---
= 技术支持如何恢复站点
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果整个 StorageGRID 站点出现故障或多个存储节点出现故障，您必须联系技术支持。技术支持将评估您的情况，制定恢复计划，然后按照符合您业务目标的方式恢复故障节点或站点，优化恢复时间并防止不必要的数据丢失。


CAUTION: 站点恢复只能由技术支持执行。

StorageGRID 系统可以对各种故障进行故障恢复，您可以自行成功执行许多恢复和维护过程。但是，创建一个简单的通用站点恢复操作步骤 很困难，因为详细步骤取决于您的具体情况。例如：

* * 您的业务目标 * ：在完全丢失 StorageGRID 站点后，您应评估如何以最佳方式实现您的业务目标。例如，是否要原位重建丢失的站点？是否要在新位置更换丢失的 StorageGRID 站点？每个客户的情况都不同，您的恢复计划必须针对您的优先事项进行设计。
* *故障的确切性质*：在开始站点恢复之前、请确定故障站点上的任何节点是否完好无损、或者任何存储节点是否包含可恢复的对象。如果重建包含有效数据的节点或存储卷，可能会发生不必要的数据丢失。
* *活动ILM策略*：网格中对象副本的数量、类型和位置由活动ILM策略控制。ILM策略的具体内容可能会影响可恢复数据量以及恢复所需的特定技术。
+

CAUTION: 如果某个站点包含某个对象的唯一副本，而该站点丢失，则该对象将丢失。

* *存储分段(或容器)一致性*：应用于存储分段(或容器)的一致性会影响StorageGRID是否在通知客户端对象成功装载之前将对象元数据完全复制到所有节点和站点。如果一致性值允许最终实现一致性、则某些对象元数据可能会在站点故障中丢失。这可能会影响可恢复的数据量以及恢复操作步骤 的详细信息。
* *近期变更历史*：恢复操作步骤的详细信息可能会受到发生故障时是否正在执行任何维护过程或最近是否对ILM策略进行了任何更改的影响。在开始站点恢复之前，技术支持必须评估网格的最新历史记录及其当前状况。



CAUTION: 站点恢复只能由技术支持执行。

下面概括介绍了技术支持用于恢复故障站点的过程：

. 技术支持：
+
.. 对故障进行详细评估。
.. 与您一起审核业务目标。
.. 根据您的具体情况制定恢复计划。


. 如果主管理节点出现故障、技术支持将对其进行恢复。
. 技术支持将按照以下概述恢复所有存储节点：
+
.. 根据需要更换 Storage Node 硬件或虚拟机。
.. 将对象元数据还原到故障站点。
.. 将对象数据还原到已恢复的存储节点。
+

CAUTION: 如果对单个故障存储节点执行恢复过程，则会发生数据丢失。

+

NOTE: 当整个站点出现故障时、技术支持将使用专用命令成功还原对象和对象元数据。



. 技术支持可恢复其他故障节点。
+
恢复对象元数据和数据后、技术支持将使用标准过程恢复发生故障的网关节点或非主管理节点。



.相关信息
link:site-decommissioning.html["站点停用"]
