---
permalink: maintain/how-your-system-is-affected-when-you-apply-hotfix.html 
sidebar: sidebar 
keywords: storagegrid, hotfix 
summary: 您必须了解应用修补程序时 StorageGRID 系统将受到什么影响。 
---
= 应用修补程序时对系统的影响
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必须了解应用修补程序时 StorageGRID 系统将受到什么影响。



== StorageGRID修补程序无中断运行

在整个修复程序过程中、StorageGRID系统可以从客户端应用程序中加热和检索数据。如果您批准所有类型相同的节点加入修补程序(例如存储节点)、则这些节点一次关闭一个、因此所有网格节点或特定类型的所有网格节点都不可用。

为了保证持续可用性、请确保ILM策略包含指定存储每个对象的多个副本的规则。此外、还必须确保所有外部S3客户端均配置为向以下项之一发送请求：

* 高可用性(HA)组虚拟IP地址
* 高可用性第三方负载平衡器
* 每个客户端具有多个网关节点
* 每个客户端具有多个存储节点




== 客户端应用程序可能会发生短期中断

StorageGRID 系统可以在整个修补程序过程中从客户端应用程序载入和检索数据；但是，如果修补程序需要在各个网关节点或存储节点上重新启动服务，则客户端与这些节点的连接可能会暂时中断。修复程序过程完成并在各个节点上恢复服务后，连接将恢复。

如果无法接受短时间内断开连接，您可能需要计划停机时间以应用修补程序。您可以使用选择性批准来计划某些节点的更新时间。


NOTE: 您可以使用多个网关和高可用性（ High Availability ， HA ）组在修复程序过程中提供自动故障转移。请参阅的说明link:../admin/configure-high-availability-group.html["配置高可用性组"]。



== 可能会触发警报和 SNMP 通知

当服务重新启动以及 StorageGRID 系统作为混合版本环境运行时（某些网格节点运行早期版本，而另一些网格节点已升级到更高版本），可能会触发警报和 SNMP 通知。通常，这些警报和通知将在修复程序完成时清除。



== 配置更改受限

将修补程序应用于 StorageGRID 时：

* 在将修补程序应用于所有节点之前、请勿更改任何网格配置(例如、指定网格网络子网或批准待定网格节点)。
* 在将修补程序应用于所有节点之前、请勿更新ILM配置。

