---
permalink: maintain/move-adc-service.html 
sidebar: sidebar 
keywords: storagegrid, move adc, adc quorum 
summary: 您可以将 ADC 服务移动到同一站点上的另一个存储节点。 
---
= 移动 ADC 服务
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以将 ADC 服务移动到同一站点上的另一个存储节点。

.开始之前
* 您已使用登录到网格管理器link:../admin/web-browser-requirements.html["支持的 Web 浏览器"]。
* 你有link:../admin/admin-group-permissions.html["维护或root访问权限"]。
* 源节点包含 ADC 服务。
* 目标节点不包含 ADC 服务。
* 目标节点是仅元数据节点或组合（元数据和对象数据）节点。
* 源节点和目标节点位于同一站点。


.关于此任务
当您想要执行以下操作时，请使用移动 ADC 过程：

* 停用托管 ADC 服务的存储节点
* 将承载 ADC 服务的存储节点转换为仅数据的存储节点


当您想要停用存储节点或link:../maintain/convert-to-data-only-node.html["将存储节点转换为仅数据节点"]，首先您可能需要使用移动 ADC 程序。您需要确保link:../maintain/understanding-adc-service-quorum.html["ADC 仲裁得以维持"]。

此过程将 ADC、IDNT、ACCT 和 RSM 服务从一个存储节点移动到同一站点上的另一个存储节点。  RSM、IDNT 和 ACCT 服务依赖于 ADC 服务，因此当 ADC 服务移动时，它们也会自动移动。

.步骤
. 记录源节点和目标节点的节点ID。
+
在网格管理 API 中，源节点 ID 被称为 `sourceNodeId`。目标节点 ID 称为 `targetNodeId`。

. 在网格管理器的顶部，选择帮助图标，然后选择*API documents*。
. 选择*转至专用API文档*。
. 选择 `POST /private/move-adc/start`手术。请参阅link:../admin/using-grid-management-api.html#issue-api-requests["问题描述 API 请求"]了解更多信息。
+
在此过程中，两个节点将依次重新启动。源节点首先重新启动，然后是目标节点。

. 您可以使用 `GET /private/move-adc`监控该过程。如果出现错误，请选择 `POST /private/move-adc/retry`重试该过程。
. link:../maintain/downloading-recovery-package.html["下载恢复包"]完成此过程后。

