---
permalink: maintain/rebooting-grid-node-from-grid-manager.html 
sidebar: sidebar 
keywords: reboot grid node, tasks tab 
summary: 您可以从节点页面上的任务选项卡重新启动单个网格节点。 
---
= 从任务选项卡重新启动网格节点
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以从节点页面上的任务选项卡重新启动单个网格节点。

.开始之前
* 您已使用登录到网格管理器link:../admin/web-browser-requirements.html["支持的 Web 浏览器"]。
* 您拥有link:../admin/admin-group-permissions.html["维护或root访问权限"]。
* 您具有配置密码短语。
* 如果要重新启动主管理节点或任何存储节点、请查看以下注意事项：
+
** 重新启动主管理节点后、浏览器将暂时失去对网格管理器的访问权限。
** 如果重新启动给定站点上的两个或更多存储节点、则在重新启动期间可能无法访问某些对象。如果任何ILM规则使用*双提交*加注选项(或规则指定了*平衡*并且无法立即创建所有所需副本)、则可能会发生此问题描述。在这种情况下、StorageGRID会将新加载的对象提交到同一站点上的两个存储节点、并在稍后评估ILM。
** 为了确保您可以在存储节点重新启动时访问所有对象，请在重新启动节点之前，停止在站点上载入对象大约一小时。




.关于此任务
当StorageGRID重新启动网格节点时、它会对该节点发出 `reboot`命令、从而导致该节点关闭并重新启动。所有服务都会自动重新启动。

* 重新启动VMware节点将重新启动虚拟机。
* 重新启动Linux节点将重新启动容器。
* 重新启动StorageGRID设备节点将重新启动计算控制器。



TIP: 如果需要重新启动多个节点，可以使用link:../maintain/rolling-reboot-procedure.html["滚动重新启动操作步骤"]。

.步骤
. 选择 * 节点 * 。
. 选择要重新启动的网格节点。
. 选择 * 任务 * 选项卡。
. 选择 * 重新启动 * 。
+
此时将显示确认对话框。如果要重新启动主管理节点，则确认对话框会提醒您，服务停止后，浏览器与网格管理器的连接将暂时断开。

. 输入配置密码短语，然后选择 * 确定 * 。
. 等待节点重新启动。
+
关闭服务可能需要一些时间。

+
重新启动节点时、节点页面上会显示此节点的灰色(管理员关闭)图标。当所有服务重新启动且节点成功连接到网格后、节点页面应显示正常状态(节点名称左侧无图标)、表示没有处于活动状态的警报、并且节点已连接到网格。


