---
permalink: maintain/rename-grid-site-node-overview.html 
sidebar: sidebar 
keywords: rename grid, rename site, rename node, display name, system name 
summary: 您可以根据需要更改整个网格、每个站点和每个节点在网格管理器中显示的显示名称。您可以根据需要随时安全地更新显示名称。 
---
= 使用重命名过程
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以根据需要更改整个网格、每个站点和每个节点在网格管理器中显示的显示名称。您可以根据需要随时安全地更新显示名称。



== 什么是重命名操作步骤 ？

首次安装StorageGRID 时、您需要为网格、每个站点和每个节点指定一个名称。这些初始名称称为_system names"、它们是最初在整个StorageGRID 中显示的名称。

内部StorageGRID 操作需要系统名称、并且无法更改。但是、您可以使用重命名操作步骤 为网格、每个站点和每个节点定义新的_display names"。这些显示名称显示在不同的StorageGRID 位置、而不是(在某些情况下、除了显示)底层系统名称。

使用重命名操作步骤 可更正错误、实施不同的命名约定或指示某个站点及其所有节点均已重新定位。与系统名称不同、显示名称可以根据需要随时更新、而不会影响StorageGRID 操作。



== 系统名称和显示名称显示在何处？

下表总结了系统名称和显示名称在StorageGRID 用户界面和StorageGRID 文件中的显示位置。

[cols="1a,1a,3a"]
|===
| 位置 | 系统名称 | 显示名称 


 a| 
网格管理器页面
 a| 
除非重命名项目、否则显示
 a| 
如果重命名某个项目、则会在以下位置显示、而不是显示系统名称：

* 信息板
* 节点页面
* 高可用性组、负载平衡器端点、VLAN接口、密钥管理服务器、网格密码的配置页面 和防火墙控制
* 警报
* 存储池定义
* 对象元数据查找页面
* 与维护过程相关的页面、包括升级、修补程序、SANtricity OS升级、停用、 扩展、恢复和对象存在性检查
* 支持页面(日志和诊断)
* 单点登录页面、位于管理节点详细信息表中管理节点主机名旁边




 a| 
*节点* > 节点的 *概览* 选项卡
 a| 
始终显示
 a| 
仅在重命名项目时显示



 a| 
*节点健康* API
 a| 
总是返回
 a| 
仅当重命名项目时返回



 a| 
使用SSH访问节点时的提示
 a| 
显示为主名称、除非该项目已重命名：

`admin@SYSTEM-NAME: ~ $`

重命名项目时包含在圆括号中：

`admin@DISPLAY-NAME(SYSTEM-NAME):~ $`
 a| 
重命名项目时显示为主名称：

`admin@DISPLAY-NAME(SYSTEM-NAME):~ $`



 a| 
`Passwords.txt`恢复包中的文件
 a| 
显示为 `Server Name`
 a| 
显示为 `Display Name`



 a| 
`/etc/hosts`文件

例如：

`10.96.99.128 SYSTEM-NAME 28989c59-a2c3-4d30-bb09-6879adf2437f DISPLAY-NAME localhost-grid # storagegrid-gen-host`
 a| 
始终显示在第二列中
 a| 
重命名项目时、显示在第四列中



 a| 
`topology-display-names.json`，随AutoSupport数据提供
 a| 
不包括
 a| 
为空、除非已重命名项；否则、会将网格、站点和节点ID映射到其显示名称。

|===


== 显示名称要求

在使用此操作步骤 之前、请查看显示名称的要求。



=== 显示节点的名称

节点的显示名称必须遵循以下规则：

* 必须在整个StorageGRID 系统中是唯一的。
* 不能与StorageGRID 系统中任何其他项目的系统名称相同。
* 必须包含至少1个且不超过32个字符。
* 可以包含数字、连字符(-)以及大小写字母。
* 可以以字母或数字开头或结尾、但不能以连字符开头或结尾。
* 不能全部为数字。
* 不区分大小写。例如、 `DC1-ADM`和 `dc1-adm`被视为重复项。


您可以使用先前由其他节点使用的显示名称重命名节点、只要重命名不会导致显示名称或系统名称重复即可。



=== 网格和站点的显示名称

网格和站点的显示名称遵循相同的规则、但以下情况除外：

* 可以包含空格。
* 可以包含以下特殊字符： `= - _ : , . @ !`
* 可以以特殊字符开头和结尾、包括连字符。
* 可以是所有数字或特殊字符。




== 显示名称最佳实践

如果您计划重命名多个项目、请在使用此操作步骤 之前记录您的常规命名方案。设计一个系统、确保名称唯一、一致且易于理解。

您可以使用符合组织要求的任何命名约定。请考虑以下基本建议、了解应包含哪些内容：

* *站点指示符*：如果有多个站点、请为每个节点名称添加一个站点代码。
* *节点类型*：节点名称通常表示节点的类型。您可以使用、 `adm`和 `gw`(存储节点、管理节点和网关节点)等缩写 `s`。
* *节点编号*：如果站点包含多个特定类型的节点、请在每个节点的名称中添加一个唯一编号。


在为名称添加可能随时间推移而变化的特定详细信息之前、请三思。例如、不要在节点名称中包含IP地址、因为这些地址可以更改。同样、如果您移动设备或升级硬件、机架位置或设备型号也可能会发生变化。



=== 示例显示名称

假设您的StorageGRID 系统有三个数据中心、每个数据中心都有不同类型的节点。您的显示名称可能很简单、如下所示：

* *网格*： `StorageGRID Deployment`
* *第一个站点*： `Data Center 1`
+
** `dc1-adm1`
** `dc1-s1`
** `dc1-s2`
** `dc1-s3`
** `dc1-gw1`


* *第二个站点*： `Data Center 2`
+
** `dc2-adm2`
** `dc2-s1`
** `dc2-s2`
** `dc2-s3`


* *第三站点*： `Data Center 3`
+
** `dc3-s1`
** `dc3-s2`
** `dc3-s3`



