---
permalink: maintain/reviewing-warnings-about-storage-volume-recovery.html 
sidebar: sidebar 
keywords: storagegrid, recover, volume warning 
summary: 在恢复存储节点的故障存储卷之前，您必须查看以下警告。 
---
= 存储卷恢复警告
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在为存储节点恢复故障存储卷之前、请查看以下警告。

存储节点中的存储卷（或卷组）由十六进制数标识，该十六进制数称为卷 ID 。例如， 0000 是第一个卷， 000f 是第 16 个卷。每个存储节点上的第一个对象存储（卷 0 ）最多使用 4 TB 的空间来执行对象元数据和 Cassandra 数据库操作；该卷上的任何剩余空间都用于对象数据。所有其他存储卷专用于对象数据。

如果卷 0 发生故障并需要恢复，则 Cassandra 数据库可能会作为卷恢复操作步骤 的一部分进行重建。在以下情况下，还可以重建 Cassandra ：

* 存储节点脱机超过 15 天后将恢复联机。
* 系统驱动器和一个或多个存储卷发生故障并已恢复。


重建 Cassandra 后，系统将使用其他存储节点中的信息。如果脱机的存储节点过多，则某些 Cassandra 数据可能不可用。如果 Cassandra 最近已重建，则 Cassandra 数据可能尚未在网格中保持一致。如果在存储节点过多脱机时重建 Cassandra ，或者在彼此 15 天内重建两个或多个存储节点，则可能会发生数据丢失。


CAUTION: 如果多个存储节点出现故障（或脱机），请联系技术支持。请勿执行以下恢复操作步骤。可能发生数据丢失。


CAUTION: 如果这是在存储节点发生故障或恢复后不到 15 天内第二个存储节点发生故障，请联系技术支持。在 15 天内在两个或多个存储节点上重建 Cassandra 可能会导致数据丢失。


NOTE: 如果一个站点上的多个存储节点出现故障，则可能需要一个站点恢复操作步骤 。请参阅。 link:how-site-recovery-is-performed-by-technical-support.html["技术支持如何恢复站点"]


CAUTION: 如果 ILM 规则配置为仅存储一个复制副本，而该副本位于发生故障的存储卷上，则您将无法恢复对象。

.相关信息
link:warnings-and-considerations-for-grid-node-recovery.html["有关网格节点恢复的警告和注意事项"]
