---
permalink: maintain/reviewing-warnings-for-system-drive-recovery.html 
sidebar: sidebar 
keywords: storagegrid, recover, system drive warning, storage node 
summary: 在恢复存储节点的故障系统驱动器之前、请查看有关网格节点恢复的一般警告和注意事项以及以下特定警告。 
---
= 存储节点系统驱动器恢复警告
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在恢复存储节点的故障系统驱动器之前、请查看常规link:warnings-and-considerations-for-grid-node-recovery.html["有关网格节点恢复的警告和注意事项"]警告和以下特定警告。

存储节点具有包含对象元数据的 Cassandra 数据库。在以下情况下、可能会重建cassand拉 数据库：

* 存储卷出现故障并已恢复。
* 系统驱动器和一个或多个存储卷发生故障并已恢复。


重建 Cassandra 后，系统将使用其他存储节点中的信息。如果 Cassandra 最近已重建，则 Cassandra 数据可能尚未在网格中保持一致。如果脱机的存储节点太多：

* 某些cassand拉 数据可能不可用。
* 可能发生数据丢失。



CAUTION: 如果多个存储节点出现故障（或脱机），请联系技术支持。请勿执行以下恢复操作步骤。可能发生数据丢失。有关详细信息，请参阅 link:how-site-recovery-is-performed-by-technical-support.html["技术支持如何恢复站点"]。


CAUTION: 如果此存储节点处于只读维护模式，以便允许存储卷出现故障的另一个存储节点检索对象，请先在存储卷出现故障的存储节点上恢复卷，然后再恢复此故障存储节点。请参阅的说明link:recovering-from-storage-volume-failure-where-system-drive-is-intact.html["从系统驱动器完好无损的存储卷故障中恢复"]。


CAUTION: 如果 ILM 规则配置为仅存储一个复制副本，而该副本位于发生故障的存储卷上，则您将无法恢复对象。
