---
permalink: maintain/shutting-down-grid-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, node shutdown, shut down node, node shut down 
summary: 您可以使用节点的命令 Shell 关闭网格节点。 
---
= 关闭网格节点
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用节点的命令 Shell 关闭网格节点。

.开始之前
* 您已获得 `Passwords.txt`文件。


.关于此任务
在执行此操作步骤 之前，请查看以下注意事项：

* 通常，一次关闭的节点不应超过一个，以避免中断。
* 除非文档或技术支持明确指示、否则请勿在维护操作步骤 期间关闭节点。
* 关闭过程取决于节点的安装位置，如下所示：
+
** 关闭 VMware 节点将关闭虚拟机。
** 关闭 Linux 节点将关闭容器。
** 关闭 StorageGRID 设备节点将关闭计算控制器。


* 如果您计划关闭一个站点上的多个存储节点、请在关闭这些节点之前停止在该站点上载入对象大约一小时。
+
如果任何ILM规则使用*双提交*写入选项(或者如果某个规则使用*平衡*选项且无法立即创建所有所需副本)、则StorageGRID 会立即将所有新加热的对象提交到同一站点上的两个存储节点、并在稍后评估ILM。如果某个站点上的多个存储节点关闭、则在关闭期间、您可能无法访问新载入的对象。如果站点上的可用存储节点太少、写入操作也可能失败。请参阅。 link:../ilm/index.html["使用 ILM 管理对象"]



.步骤
. 登录到网格节点：
+
.. 输入以下命令： `ssh admin@_grid_node_IP_`
.. 输入文件中列出的密码 `Passwords.txt`。
.. 输入以下命令切换到root： `su -`
.. 输入文件中列出的密码 `Passwords.txt`。


+
当您以root用户身份登录时，提示符将从更 `$`改为 `#`。

. 停止所有服务： `service servermanager stop`
+
服务可能需要长达 15 分钟才能关闭，您可能需要远程登录到系统以监控关闭过程。

. 如果此节点正在VMware虚拟机上运行、或者它是设备节点、请发出shutdown命令： `shutdown -h now`
+
无论命令的结果如何、均可执行此步骤 `service servermanager stop`。

+

NOTE: 在设备节点上发出命令后 `shutdown -h now`、必须重新启动设备以重新启动节点。

+
对于设备，此命令将关闭控制器，但设备仍处于打开状态。您必须完成下一步。

. 如果要关闭设备节点、请按照适用于您的设备的步骤进行操作。
+
[role="tabbed-block"]
====
.SG6160
--
.. 关闭SG6100-CN存储控制器的电源。
.. 等待SG6100-CN存储控制器上的蓝色电源LED熄灭。


--
.SGF6112
--
.. 关闭设备电源。
.. 等待蓝色电源 LED 熄灭。


--
.SG6000
--
.. 等待存储控制器背面的绿色缓存活动 LED 熄灭。
+
当需要将缓存的数据写入驱动器时，此 LED 亮起。您必须等待此 LED 关闭，然后再关闭电源。

.. 关闭设备电源，然后等待蓝色电源 LED 熄灭。


--
.SGs了
--
.. 等待存储控制器背面的绿色缓存活动 LED 熄灭。
+
当需要将缓存的数据写入驱动器时，此 LED 亮起。您必须等待此 LED 关闭，然后再关闭电源。

.. 从 SANtricity 系统管理器的主页中，选择 * 查看正在执行的操作 * 。
.. 确认所有操作均已完成，然后再继续下一步。
.. 关闭控制器架上的两个电源开关、然后等待控制器架上的所有LED熄灭。


--
.SG5700
--
.. 等待存储控制器背面的绿色缓存活动 LED 熄灭。
+
当需要将缓存的数据写入驱动器时，此 LED 亮起。您必须等待此 LED 关闭，然后再关闭电源。

.. 关闭设备电源，等待所有 LED 和七段显示活动停止。


--
.SG100或SG1000
--
.. 关闭设备电源。
.. 等待蓝色电源 LED 熄灭。


--
====

