---
permalink: maintain/starting-software-installation-on-services-appliance-recovery.html 
sidebar: sidebar 
keywords: storagegrid, recover, services appliance, start software installation 
summary: 要在服务设备上安装网关节点或管理节点、请使用该设备中提供的StorageGRID设备安装程序。 
---
= 在服务设备上启动 StorageGRID 软件安装
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
要在服务设备上安装网关节点或管理节点、请使用该设备中提供的StorageGRID设备安装程序。

.开始之前
* 设备安装在机架中、连接到您的网络并打开电源。
* 可以使用StorageGRID 设备安装程序为此设备配置网络链路和IP地址。
* 如果要安装网关节点或非主管理节点，则需要知道以下管理节点之一的 IP 地址：
+
** StorageGRID 网格的主管理节点
** 非主管理节点（如果可用），以及是否正用于恢复该节点


* 如果要使用非主管理节点恢复节点（包括主管理节点），则可以指定该管理节点的 IP 地址。
* StorageGRID 设备安装程序的"IP Configuration"(IP配置)页面上列出的所有网格网络子网都在主管理节点上的"Grid Network Subnet"(网格网络子网)列表中进行定义。
+
请参阅。 https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/index.html["硬件安装快速入门"^]

* 您正在使用link:../admin/web-browser-requirements.html["支持的 Web 浏览器"]。
* 您已将其中一个IP地址分配给此设备。您可以使用管理网络，网格网络或客户端网络的 IP 地址。
* 如果您要安装主管理节点，则可以使用此版本 StorageGRID 的 Ubuntu 或 Debian 安装文件。
+

NOTE: 在制造过程中，服务设备会预加载最新版本的 StorageGRID 软件。如果预加载的软件版本与StorageGRID 部署中使用的版本匹配、则不需要安装文件。



.关于此任务
要在服务设备上安装StorageGRID软件、请执行以下操作：

* 对于主管理节点，指定节点的名称，然后上传相应的软件包（如果需要）。如果要恢复主管理节点，并且网格中有非主管理节点，则可以选择使用非主管理节点恢复节点并指定该管理节点的 IP，也可以使用当前配置安装或恢复节点。
* 对于非主管理节点或网关节点，您可以指定或确认主管理节点的 IP 地址以及节点的名称。
* 您开始安装，并等待卷配置完毕并安装软件。
* 在整个过程中，安装将暂停。要恢复安装，您必须登录到网格管理器并将待定节点配置为故障节点的替代节点。
* 配置节点后，设备安装过程将完成，设备将重新启动。


.步骤
. 打开浏览器并输入服务设备的IP地址之一。
+
`https://_Controller_IP_:8443`

+
此时将显示 StorageGRID 设备安装程序主页页面。

. 要安装主管理节点：
+
.. 在 "This Node" 部分中，对于 "* 节点类型 " ，选择 "* 主管理 * " 。
.. 在*节点名称*字段中，输入与您正在恢复的节点相同的名称，然后选择*保存*。
.. 从"安装模式"部分提供的两种模式中选择一种合适的模式。您可以选择 Install a node or recover this node using current configuration 方法，也可以选择 Recover this node using a non-primary Admin Node 方法。
+
[role="tabbed-block"]
====
.当前配置方法
--
使用当前配置安装节点或恢复此节点。

... 在安装部分，检查当前状态下列出的软件版本。如果已准备好安装的软件版本正确，请跳至 <<installation_section_step,安装步骤>>。
... 如果您需要上传不同版本的软件，请在*高级*菜单下选择*上传 StorageGRID 软件*。此时将显示 Upload StorageGRID Software（上传 StorageGRID 软件）页面。
... 选择*浏览*以上传 StorageGRID 软件的*软件包*和*校验和文件*。文件在您选择后会自动上传。
... 选择*主页*返回 StorageGRID Appliance Installer 主页。


--
.非主管理节点方法
--
使用非主管理节点恢复此节点。

... 在非主管理节点IP字段中，输入要用于恢复的非主管理节点的网格网络IP地址，然后选择*保存*。
... 如果准备安装的软件版本正确，请跳至<<installation_section_step,安装步骤>>。


--
====


. 要安装网关节点或非主管理节点：
+
.. 在 "This Node" 部分中，对于 "* 节点类型 " ，根据要还原的节点类型选择 "* 网关 * " 或 "* 非主管理 * " 。
.. 在*节点名称*字段中，输入与您正在恢复的节点相同的名称，然后选择*保存*。
.. 在主管理节点连接部分中，确定是否需要指定主管理节点的 IP 地址。
+
假设主管理节点或至少一个配置了 admin_ip 的其他网格节点位于同一子网上， StorageGRID 设备安装程序可以自动发现此 IP 地址。

.. 如果未显示此 IP 地址或者您需要更改它，请指定地址：


+
[cols="1a,2a"]
|===
| 选项 | 说明 


 a| 
手动输入 IP
 a| 
.. 清除*启用管理节点发现*复选框。
.. 手动输入 IP 地址。
.. 选择 * 保存 * 。
.. 等待新IP地址的连接状态变为"就绪"。




 a| 
自动发现所有已连接的主管理节点
 a| 
.. 选中*启用管理节点发现*复选框。
.. 从已发现的 IP 地址列表中，选择要部署此服务设备的网格的主管理节点。
.. 选择 * 保存 * 。
.. 等待新IP地址的连接状态变为"就绪"。


|===
. 在 "Installation_section_steP]] 中，确认当前状态为 Ready to start installation of node name 且 * Start Installation* 按钮已启用。
+
如果未启用“*开始安装*”按钮，您可能需要更改网络配置或端口设置。请参阅您设备的维护说明。

. 从 StorageGRID 设备安装程序主页中，选择 *开始安装*。
+
当前状态更改为"正在安装"，并显示监控安装页面。

+

NOTE: 如果需要手动访问监视器安装页面，请从菜单栏中选择*监视器安装*。


