---
permalink: maintain/step-3-revise-ilm-policy.html 
sidebar: sidebar 
keywords: storagegrid, recover, revise ilm policies 
summary: '从停用站点向导的步骤3 (修订ILM策略)中、您可以确定站点是否由任何ILM策略引用。' 
---
= 第3步：修订ILM策略
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
从停用站点向导的第3步(修订ILM策略)中、您可以确定站点是否由任何ILM策略引用。

.开始之前
您已很好地了解如何link:../ilm/index.html["使用ILM管理对象"]。您熟悉创建存储池和ILM规则以及模拟和激活ILM策略。

.关于此任务
如果任何策略(活动或非活动)中的任何ILM规则引用某个站点、则StorageGRID无法停用该站点。

如果任何ILM策略引用要停用的站点、则必须删除或编辑这些策略、以使其满足以下要求：

* 全面保护所有对象数据。
* 请勿参考要停用的站点。
* 请勿使用引用该站点的存储池或使用"所有站点"选项。
* 请勿使用引用站点的纠删编码配置文件。
* 请勿使用StorageGRID 11.5或更早版本安装中的创建2个副本规则。



CAUTION: 切勿创建单个副本 ILM 规则来容纳站点的删除。如果 ILM 规则在任何时间段内仅创建一个复制副本，则会使数据面临永久丢失的风险。如果某个对象只存在一个复制副本，则在存储节点出现故障或出现严重错误时，该对象将丢失。在升级等维护过程中，您还会暂时失去对对象的访问权限。


TIP: 如果您正在执行_connec地点 停用_、则必须考虑StorageGRID应如何管理要删除的地点当前的对象数据。根据您的数据保护要求、新规则可以将现有对象数据移动到不同站点、也可以删除不再需要的任何额外对象副本。

如果您在设计新策略时需要帮助、请联系技术支持。

.步骤
. 从第3步(修订ILM策略)开始、确定是否有任何ILM策略引用您选择停用的站点。
. 如果未列出任何策略，请选择*下一步*转到link:step-4-remove-ilm-references.html["第 4 步：删除 ILM 引用"]。
. 如果列出了一个或多个_active_ ILM策略、请克隆每个现有策略或创建不引用要停用的站点的新策略：
+
.. 在策略名称列中选择策略的链接。
+
此策略的ILM策略详细信息页面将显示在新的浏览器选项卡中。" 取消配置站点 " 页面将在 " 其他 " 选项卡上保持打开状态。

.. 根据需要遵循以下准则和说明：
+
*** 使用ILM规则：
+
**** link:../ilm/creating-storage-pool.html["创建一个或多个存储池"]不是指站点。
**** link:../ilm/working-with-ilm-rules-and-ilm-policies.html["编辑或替换规则"]引用站点的。
+

NOTE: 请勿选择*创建2个副本*规则、因为该规则使用*所有存储节点*存储池、这是不允许的。



*** 使用ILM策略：
+
**** link:../ilm/working-with-ilm-rules-and-ilm-policies.html#clone-ilm-policy["克隆现有ILM策略"] 或 link:../ilm/creating-ilm-policy.html["创建新的ILM策略"]。
**** 确保默认规则和其他规则不引用站点。
+

CAUTION: 您必须确认 ILM 规则的顺序正确。激活策略后，新对象和现有对象将按列出的顺序从顶部开始进行评估。





.. 请加热测试对象并模拟策略、以确保应用正确的规则。
+

CAUTION: ILM 策略中的错误可能会导致发生原因 丢失不可恢复的数据。在激活策略之前，请仔细查看并模拟策略，以确认策略将按预期运行。

+

CAUTION: 激活新的 ILM 策略时， StorageGRID 会使用它来管理所有对象，包括现有对象和新载入的对象。在激活新的 ILM 策略之前，请查看对现有复制对象和纠删编码对象的放置方式所做的任何更改。在评估和实施新放置时，更改现有对象的位置可能会导致临时资源问题。

.. 激活新策略并确保旧策略现在处于非活动状态。
+
如果要激活多个策略，请link:../ilm/creating-ilm-policy.html#activate-ilm-policy["按照以下步骤创建ILM策略标记"]。

+
如果您要执行已连接站点停用，则一旦激活新的 ILM 策略， StorageGRID 就会开始从选定站点删除对象数据。移动或删除所有对象副本可能需要数周时间。尽管在站点上仍存在对象数据的情况下，您可以安全地开始站点停用，但如果您允许在实际停用操作步骤 之前从站点移动数据，则停用操作步骤 将更快地完成，并减少中断和性能影响 （通过在向导的步骤 5 中选择 * 启动取消配置 * ）。



. 对于每个_INEVIOUS_策略、请先按照前面的步骤所述选择每个策略的链接来编辑或删除该策略。
+
** link:../ilm/working-with-ilm-rules-and-ilm-policies.html#edit-ilm-policy["编辑策略"]因此、它并不是指要停用的站点。
** link:../ilm/working-with-ilm-rules-and-ilm-policies.html#remove-ilm-policy["删除策略"](英文)


. 完成对ILM规则和策略的更改后、第3步(修订ILM策略)中不应再列出任何策略。选择 * 下一步 * 。
+
此时将显示第 4 步（删除 ILM 参考）。


