---
permalink: maintain/storagegrid-hotfix-procedure.html 
sidebar: sidebar 
keywords: apply hotfix, install hotfix, replace primary admin node 
summary: 如果检测到软件问题并在功能版本之间得到解决，则可能需要将修补程序应用于 StorageGRID 系统。 
---
= StorageGRID 热修补程序操作步骤
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果检测到软件问题并在功能版本之间得到解决，则可能需要将修补程序应用于 StorageGRID 系统。

StorageGRID 修补程序包含在功能或修补程序版本之外进行的软件更改。未来版本也会进行同样的更改。此外，每个热修补程序版本都包含此功能或修补程序版本中所有以前的修补程序的汇总。



== 应用修补程序的注意事项

当另一个维护操作步骤 正在运行时、您无法应用StorageGRID 修补程序。例如、当停用、扩展或恢复操作步骤 正在运行时、您无法应用修补程序。


NOTE: 如果节点或站点停用操作步骤 已暂停，您可以安全地应用修补程序。此外，您还可以在 StorageGRID 升级操作步骤 的最后阶段应用修补程序。有关详细信息，请参见有关升级 StorageGRID 软件的说明。

在网格管理器中上传此修补程序后，此修补程序将自动应用于主管理节点。然后，您可以批准将此修补程序应用于 StorageGRID 系统中的其余节点。

如果某个修补程序无法应用到一个或多个节点，则失败的原因将显示在该修补程序进度表的详细信息列中。您必须解决导致失败的任何问题，然后重试整个过程。先前已成功应用此修补程序的节点将在后续应用程序中跳过。您可以根据需要安全地重试此修复程序多次，直到所有节点均已更新为止。要使应用程序完成，必须在所有网格节点上成功安装此修补程序。

虽然网格节点会使用新的修补程序版本进行更新，但修补程序中的实际更改可能仅影响特定类型节点上的特定服务。例如，某个修补程序可能只会影响存储节点上的 LDR 服务。



== 如何应用修补程序进行恢复和扩展

在将修补程序应用到网格后，主管理节点会自动为通过恢复操作还原或添加到扩展中的任何节点安装相同的修补程序版本。

但是，如果需要恢复主管理节点，则必须手动安装正确的 StorageGRID 版本，然后应用此修补程序。主管理节点的最终 StorageGRID 版本必须与网格中其他节点的版本匹配。

以下示例说明了如何在恢复主管理节点时应用修补程序：

. 假设网格运行的是具有最新修补程序的 StorageGRID 11._A.B_ 版本。"网格版本"为11._A.B.y_。
. 主管理节点出现故障。
. 您可以使用 StorageGRID 11._A.B_ 重新部署主管理节点，并执行恢复操作步骤 。
+

NOTE: 根据与网格版本匹配的要求、您可以在部署节点时使用次要版本；您无需先部署主要版本。

. 然后，将修补程序 11._A.B.y_ 应用于主管理节点。


有关详细信息，请参见 link:configuring-replacement-primary-admin-node.html["配置替代主管理节点"]。
