---
permalink: maintain/understanding-adc-service-quorum.html 
sidebar: sidebar 
keywords: storagegrid, recover, adc, adc quorum 
summary: 'ADC 仲裁可确保每个站点保持最低数量的管理域控制器 (ADC) 服务可用。StorageGRID 在需要时会在停用期间自动移动 ADC 服务。' 
---
= 什么是 StorageGRID ADC 仲裁？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ADC 仲裁可确保每个站点保持最低数量的管理域控制器 (ADC) 服务可用。StorageGRID 在需要时会在停用期间自动移动 ADC 服务。

某些存储节点上的ADC服务负责维护网格拓扑信息并为网格提供配置服务。StorageGRID 系统要求每个站点始终提供一定的数字转换服务仲裁。

如果删除存储节点会发生原因 使不再满足ADC仲裁、则无法停用该节点。要在停用期间满足ADC仲裁要求、每个站点上至少必须有三个存储节点具有ADC服务。如果站点中有三个以上的存储节点使用ADC服务、则停用后、这些节点中的简单多数必须保持可用： `((0.5 * _Storage Nodes with ADC_) + 1)`


CAUTION: 在包含基于软件的纯元数据节点的网格中停用存储节点时、请务必小心谨慎。如果停用配置为存储_Both _对象和元数据的所有节点、则会从网格中删除存储对象的功能。有关纯元数据存储节点的详细信息、请参见link:../primer/what-storage-node-is.html#types-of-storage-nodes["存储节点的类型"]。

例如、假设某个站点当前包含六个具有ADC服务的存储节点、而您要停用三个存储节点。由于需要使用 ADC 仲裁，您必须完成两个停用过程，如下所示：

* 在第一次停用过程中，必须确保具有ADC服务的四个存储节点保持可用： `((0.5 * 6) + 1)`。这意味着最初只能停用两个存储节点。
* 在第二个退役过程中，您可以删除第三个存储节点，因为 ADC 仲裁现在只需要三个 ADC 服务保持可用： `((0.5 * 4) + 1)` 。


当您停用具有 ADC 服务的存储节点时，如果停用会使站点的 ADC 计数低于法定数量，StorageGRID 会自动将 ADC 服务移动到同一站点上的另一个存储节点。自动移动要求网格中的所有节点都已连接，并且同一站点上有可用的非 ADC 存储节点来接收该服务。停用程序为每个站点至少维护三个 ADC 存储节点。例如，如果您停用站点上的四个或六个 ADC 节点，则假设同一站点上存在可用的非 ADC 节点，此过程完成后将保留三个 ADC 存储节点。

如果无法自动移动 ADC 服务，您可以link:move-adc-service.html["手动移动 ADC 服务"]到同一站点上的另一个存储节点，或者link:../expand/index.html["在扩展中添加新的 Storage Node"]并指定它应具有 ADC 服务。然后，您可以在不影响仲裁的情况下停用现有存储节点。
