---
permalink: maintain/warnings-and-considerations-for-grid-node-recovery.html 
sidebar: sidebar 
keywords: storagegrid, recover, warning 
summary: 如果网格节点发生故障，您必须尽快恢复。开始之前，您必须查看节点恢复的所有警告和注意事项。 
---
= 有关网格节点恢复的警告和注意事项
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果网格节点发生故障，您必须尽快恢复。开始之前，您必须查看节点恢复的所有警告和注意事项。


CAUTION: StorageGRID 是一个分布式系统，由多个节点组成，这些节点彼此协同工作。请勿使用磁盘快照还原网格节点。请参阅每种类型节点的恢复和维护过程。


NOTE: 如果整个StorageGRID站点出现故障，请联系技术支持。技术支持将与您合作制定并执行站点恢复计划，以最大限度地恢复数据量并满足您的业务目标。请参阅link:how-site-recovery-is-performed-by-technical-support.html["技术支持如何恢复站点"] 。

尽快恢复出现故障的网格节点的一些原因包括：

* 出现故障的网格节点可以减少系统和对象数据的冗余，因此，如果另一个节点发生故障，您容易受到永久数据丢失的风险。
* 网格节点发生故障可能会影响日常操作的效率。
* 出现故障的网格节点可能会降低您监控系统操作的能力。
* 如果存在严格的 ILM 规则，则出现故障的网格节点可能会发生原因 a 500 internal server error 。
* 如果未及时恢复网格节点，则恢复时间可能会增加。例如，可能会出现需要在恢复完成之前清除的队列。


对于要恢复的特定网格节点类型，请始终遵循恢复操作步骤 。主管理节点、网关节点、设备节点和存储节点的恢复过程因主管理节点或非主管理节点而异。



== 恢复网格节点的前提条件

恢复网格节点时，系统会假设以下所有条件：

* 已更换并配置发生故障的物理或虚拟硬件。
* 替代设备上的StorageGRID设备安装程序版本与StorageGRID系统的软件版本相匹配，如中所述 https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/verifying-and-upgrading-storagegrid-appliance-installer-version.html["验证并升级 StorageGRID 设备安装程序版本"^]。
* 如果您正在恢复主管理节点以外的网格节点，则正在恢复的网格节点与管理恢复过程的管理节点之间存在连接。
* 如果要恢复设备存储节点，则必须在设备安装期间指定与原始设备相同的存储类型（组合、仅元数据或仅数据）。如果指定不同的存储类型，恢复将失败，并且需要使用指定的正确存储类型重新安装设备。




== 托管多个网格节点的服务器发生故障时的节点恢复顺序

如果托管多个网格节点的服务器发生故障，您可以按任意顺序恢复节点。但是，如果发生故障的服务器托管着主管理节点，并且不存在非主管理节点，则必须先恢复主管理节点。



== 已恢复节点的 IP 地址

请勿尝试使用当前分配给任何其他节点的IP地址恢复节点。部署新节点时，请使用故障节点的当前 IP 地址或未使用的 IP 地址。

如果您使用新 IP 地址部署新节点，然后恢复该节点，则新 IP 地址将继续用于已恢复的节点。如果要还原到原始 IP 地址，请在恢复完成后使用更改 IP 工具。
