---
permalink: primer/what-gateway-node-is.html 
sidebar: sidebar 
keywords: gateway nodes, api gateway 
summary: 网关节点提供一个专用负载平衡接口、S3客户端应用程序可以使用此接口连接到StorageGRID。负载平衡通过在多个存储节点之间分布工作负载、最大限度地提高速度和连接容量。网关节点是可选的。 
---
= 什么是网关节点？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
网关节点提供一个专用负载平衡接口、S3客户端应用程序可以使用此接口连接到StorageGRID。负载平衡通过在多个存储节点之间分布工作负载、最大限度地提高速度和连接容量。网关节点是可选的。

StorageGRID负载平衡器服务在所有管理节点和所有网关节点上提供。它会终止客户端请求，检查请求并与存储节点建立新的安全连接。负载平衡器服务可以无缝地将客户端定向到最佳存储节点、这样、节点故障甚至整个站点的故障都是透明的。

您可以配置一个或多个负载平衡器端点、以定义传入和传出客户端请求访问网关和管理节点上的负载平衡器服务所使用的端口和网络协议(HTTPS或HTTP)。负载平衡器端点还可以定义客户端类型(S3)、绑定模式以及允许或阻止的租户列表(可选)。请参阅。 link:../admin/managing-load-balancing.html["负载平衡注意事项"]

您可以根据需要将多个网关节点和管理节点的网络接口分组为一个高可用性(HA)组。如果HA组中的活动接口发生故障、备份接口可以管理客户端应用程序工作负载。请参阅。 link:../admin/managing-high-availability-groups.html["管理高可用性(HA)组"]



== 网关节点的主要服务

下表显示了网关节点的主服务；但是，此表并未列出所有节点服务。

[cols="1a,2a"]
|===
| 服务 | 关键功能 


 a| 
缓存服务
 a| 
管理对象内容的本地缓存。



 a| 
高可用性
 a| 
管理管理节点和网关节点组的高可用性虚拟 IP 地址。

* 注： * 此服务也可在管理节点上找到。



 a| 
负载平衡器
 a| 
提供从客户端到存储节点的S3流量的第7层负载平衡。这是建议的负载平衡机制。

* 注： * 此服务也可在管理节点上找到。



 a| 
服务器状态监控器（ SSM ）
 a| 
监控操作系统和底层硬件。

|===