---
permalink: primer/what-storage-node-is.html 
sidebar: sidebar 
keywords: StorageGRID, what is a storage node, how many storage nodes 
summary: 存储节点可管理和存储对象数据和元数据。存储节点包括在磁盘上存储、移动、验证和检索对象数据和元数据所需的服务和流程。 
---
= 什么是 StorageGRID 存储节点？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
存储节点可管理和存储对象数据和元数据。存储节点包括在磁盘上存储、移动、验证和检索对象数据和元数据所需的服务和流程。

StorageGRID系统中的每个站点必须至少具有三个存储节点。



== 存储节点的类型

在安装期间、您可以选择要安装的存储节点类型。以下类型可用于基于软件的存储节点和支持此功能的基于设备的存储节点：

* 数据和元数据组合存储节点
* 纯元数据存储节点
* 纯数据存储节点


在以下情况下、您可以选择存储节点类型：

* 首次安装存储节点时
* 在StorageGRID系统扩展期间添加存储节点时




=== 数据和元数据存储节点(组合)

默认情况下、所有新存储节点都将同时存储对象数据和元数据。这种类型的存储节点称为_Combend_存储节点。



=== 纯元数据存储节点

如果网格存储大量小型对象、则将存储节点专用于元数据可能会很有意义。安装专用元数据容量可以在大量小型对象所需的空间与这些对象的元数据所需的空间之间实现更好的平衡。此外、高性能设备上托管的纯元数据存储节点可以提高性能。

纯元数据存储节点具有特定的硬件要求：

* 使用StorageGRID设备时、只能在具有12个1.9 TB或12个3.8 TB驱动器的GF6112设备上配置纯元数据节点。
* 使用基于软件的节点时、纯元数据节点资源必须与现有存储节点资源匹配。例如：
+
** 如果现有StorageGRID站点使用SG6000或SG6100设备、则基于软件的纯元数据节点必须满足以下最低要求：
+
*** 128 GB RAM
*** 8核CPU
*** 用于cassandr数据库的8 TB SSD或等效存储(rangedb/0)


** 如果现有的StorageGRID站点使用具有 24 GB RAM、8 核 CPU 和 3 TB 或 4TB 元数据存储的虚拟存储节点，则基于软件的仅元数据节点应使用类似的资源（24 GB RAM、8 核 CPU 和 4TB 元数据存储（rangedb/0））。


* 添加新的StorageGRID站点时，新站点的总元数据容量至少应与现有站点相匹配。新站点的资源应与现有站点的存储节点相匹配。



NOTE: 虽然纯元数据存储节点包含<<ldr-service,LDR服务>>、并可处理S3客户端请求、但StorageGRID性能可能不会提高。



=== 纯数据存储节点

如果存储节点具有不同的性能特征、则将存储节点专用于数据可能会很有意义。例如、为了可能提高性能、您可以将纯数据、大容量旋转磁盘存储节点与纯元数据高性能存储节点结合使用。

此外，您可以通过从 Cassandra 中删除低 RAM 节点来获得更多元数据容量，这会增加每个节点的元数据容量限制。请参阅link:../admin/managing-object-metadata-storage.html["管理对象元数据存储"] 。

您可以将不包含<<adc-service,ADC 服务>>到仅数据存储节点。请参阅link:../maintain/convert-to-data-only-node.html["将存储节点转换为仅数据节点"] 。



== 每个网格和每个站点所需的存储节点

在选择拓扑中使用的存储节点时，请记住网格或网格中的每个站点必须包含以下内容：

* 每个站点（在单站点或多站点网格中）：三个<<adc-service,模数转换器>>存储节点（可以是组合存储节点和仅元数据存储节点的任意组合）
* 单站点网格：至少两个对象存储节点（可以是任意组合或仅数据）
* 多站点网格：每个站点至少一个对象存储节点（可以是组合的，也可以是仅数据）




== 存储节点的主服务

下表显示了存储节点的主服务；但是，此表并未列出所有节点服务。


NOTE: 某些服务（例如，模块转换服务和 RSM 服务）通常仅存在于每个站点的三个存储节点上。

[cols="1a,3a"]
|===
| 服务 | 关键功能 


 a| 
帐户（访问）
 a| 
管理租户帐户。

仅数据存储节点不提供此服务。



 a| 
[[adc-service]]管理域控制器 (ADC)
 a| 
维护拓扑和网格范围的配置。

仅数据存储节点不提供此服务。

.详细信息
[%collapsible]
====
管理域控制器（ ADC-A ）服务对网格节点及其彼此连接进行身份验证。ADC服务至少托管在一个站点的三个存储节点上。

此 ADA 服务可维护拓扑信息，包括服务的位置和可用性。当网格节点需要来自另一个网格节点的信息或由另一个网格节点执行操作时，它会联系一个模数转换器服务来查找处理其请求的最佳网格节点。此外、ADC服务会保留StorageGRID部署配置包的副本、从而允许任何网格节点检索当前配置信息。

为了便于分布式和孤岛式操作，每个 StorageGRID 服务会将证书，配置包以及有关服务和拓扑的信息与系统中的其他 ADE 服务进行同步。

通常，所有网格节点都会至少与一个 ADC 服务保持连接。这样可以确保网格节点始终访问最新信息。当网格节点连接时、它们会缓存其他网格节点的证书、从而使系统即使在ADC服务不可用的情况下也能继续使用已知的网格节点。新的网格节点只能通过使用模数转换器服务建立连接。

通过每个网格节点的连接，可以使此 ADA 服务收集拓扑信息。此网格节点信息包括 CPU 负载，可用磁盘空间（如果有存储），支持的服务以及网格节点的站点 ID 。其他服务则通过拓扑查询向此类服务请求拓扑信息。对于从 StorageGRID 系统收到的最新信息，此 ADA 服务会对每个查询做出响应。

====


 a| 
Cassandra
 a| 
存储和保护对象元数据。

仅数据存储节点不提供此服务。



 a| 
Cassandra Reaper
 a| 
自动修复对象元数据。

仅数据存储节点不提供此服务。



 a| 
区块
 a| 
管理经过擦除编码的数据和奇偶校验片段。



 a| 
数据移动器（ DMV ）
 a| 
将数据移动到云存储池。



 a| 
分布式数据存储（ DDS ）
 a| 
监控对象元数据存储。

.详细信息
[%collapsible]
====
每个存储节点都包含分布式数据存储(DDS)服务。此服务与cassanda数据库连接、对存储在StorageGRID系统中的对象元数据执行后台任务。

DDS服务会跟踪StorageGRID系统中已插入的对象总数、以及通过每个系统支持的接口(S3)插入的对象总数。

====


 a| 
身份（ idnt ）
 a| 
从 LDAP 和 Active Directory 联合用户身份。

仅数据存储节点不提供此服务。



 a| 
[[LDP-service]]本地分发路由器(LDR)
 a| 
处理对象存储协议请求并管理磁盘上的对象数据。

.详细信息
[%collapsible]
====
每个_Comband_、_data-only _和_metadata-only _存储节点都包含本地分发路由器(LDR)服务。此服务负责处理内容传输功能、包括数据存储、路由和请求处理。LDR服务通过处理数据传输负载和数据流量功能来完成StorageGRID 系统的大部分艰苦工作。

LDR 服务可处理以下任务：

* 查询
* 信息生命周期管理（ ILM ）活动
* 对象删除
* 对象数据存储
* 从其他 LDR 服务（存储节点）传输对象数据
* 数据存储管理
* S3协议接口


LDR服务还会将每个S3对象映射到其唯一UUID。

对象存储:: LDR 服务的底层数据存储分为固定数量的对象存储（也称为存储卷）。每个对象存储都是一个单独的挂载点。
+
--
存储在存储节点中的对象使用从 0000 到 002F 的十六进制数字进行标识，该数字称为卷 ID 。在第一个对象存储（卷 0 ）中预留空间用于 Cassandra 数据库中的对象元数据；该卷上的任何剩余空间用于对象数据。所有其他对象存储仅用于对象数据，其中包括复制的副本和经过纠删编码的片段。

为了确保复制的副本的空间使用量均匀，给定对象的对象数据会根据可用存储空间存储到一个对象存储中。当对象存储填满容量时、其余对象存储将继续存储对象、直到存储节点上没有更多空间为止。

--
元数据保护:: StorageGRID 将对象元数据存储在与 LDR 服务连接的 Cassandra 数据库中。
+
--
为了确保冗余并防止丢失，每个站点维护三个对象元数据副本。此复制不可配置，并且会自动执行。有关详细信息，请参见 link:../admin/managing-object-metadata-storage.html["管理对象元数据存储"]。

--


====


 a| 
复制状态机（ RSM ）
 a| 
确保S3平台服务请求发送到其各自的端点。

仅数据存储节点不提供此服务。



 a| 
服务器状态监控器（ SSM ）
 a| 
监控操作系统和底层硬件。

|===