---
permalink: expand/adding-new-site.html 
sidebar: sidebar 
keywords: expand, expansion, new site, add site, guidelines, StorageGRID 
summary: 您可以通过添加新站点来扩展 StorageGRID 系统。 
---
= StorageGRID添加新站点的指南
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以通过添加新站点来扩展 StorageGRID 系统。



[[guidelines-for-adding-a-site]]
== 添加站点的准则

在添加站点之前，请查看以下要求和限制：

* 每个扩展操作只能添加一个站点。
* 您不能在同一扩展中向现有站点添加网格节点。
* 所有站点必须包含至少三个存储节点。它们可以是组合存储节点和仅元数据存储节点的任意组合。如果有三个以上的存储节点，只要有三个可用的 ADC 服务，它们可以是组合、仅元数据和仅数据存储节点的任意组合。有关详细信息，请参阅 link:../primer/what-storage-node-is.html#required-storage-nodes-per-grid-and-per-site["每个网格和每个站点所需的存储节点"]。
* 添加新站点时，不会自动增加可以存储的对象数。网格的总对象容量取决于每个站点的可用存储量、ILM 策略和元数据容量。
* 在估算新站点的规模时，您必须确保其包含足够的元数据容量。
+
StorageGRID 在每个站点保留所有对象元数据的副本。添加新站点时，请确保其包含足够的元数据容量以存储现有对象元数据，以及足够的元数据容量以支持增长。

+
有关详细信息，请参阅以下内容：

+
** link:../admin/managing-object-metadata-storage.html["管理对象元数据存储"]
** link:../monitor/monitoring-storage-capacity.html#monitor-object-metadata-capacity-for-each-storage-node["监控每个存储节点的对象元数据容量"]


* 您必须考虑站点之间的可用网络带宽以及网络延迟级别。元数据更新会在站点之间持续复制，即使所有对象都仅存储在要载入的站点上也是如此。
+
要避免因延迟而导致性能不佳，请执行以下操作：

+
** 不建议在延迟大于 100 毫秒的站点之间使用纠删码。
** StorageGRID 系统中的站点不应跨越很远的地理距离，例如，跨越多个大陆。


* 由于 StorageGRID 系统在扩展期间仍可正常运行，因此您必须在启动扩展操作步骤 之前查看 ILM 规则。您必须确保在扩展操作步骤 完成之前不会将对象副本存储到新站点。
+
例如，在开始扩展之前，请检查是否有任何规则使用默认存储池（所有存储节点）。如果是这样，请使用现有存储节点创建一个新的存储池，并更新您的 ILM 规则以使用新的存储池。否则，一旦该站点的第一个节点处于活动状态，就会将对象复制到新站点。

+
有关添加新站点时更改 ILM 策略的详细信息，请参见 link:../ilm/example-6-changing-ilm-policy.html["更改ILM策略的示例"]。


