---
permalink: expand/adding-storage-capacity-for-replicated-objects.html 
sidebar: sidebar 
keywords: replication, replicated, copies, capacity, storage nodes, expand, expansion, StorageGRID 
summary: 如果您的部署的信息生命周期管理 \ （ ILM ）策略包含创建对象的复制副本的规则，则必须考虑要添加的存储容量以及要添加新存储卷或存储节点的位置。 
---
= StorageGRID中复制数据的扩展规划
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您的部署的信息生命周期管理（ ILM ）策略包含一条规则，用于创建对象的复制副本，则必须考虑要添加的存储容量以及要添加新存储卷或存储节点的位置。

有关在何处添加额外存储的指导，请查看创建复制副本的 ILM 规则。如果 ILM 规则创建两个或更多对象副本，请计划在创建对象副本的每个位置添加存储。例如、如果您有一个双站点网格、并且有一个ILM规则在每个站点创建一个对象副本、则必须对每个站点执行此操作、link:../expand/adding-storage-volumes-to-storage-nodes.html["添加存储"]才能增加网格的整体对象容量。有关对象复制的信息，请参见link:../ilm/what-replication-is.html["什么是复制"]。

出于性能原因，您应尝试在各个站点之间保持存储容量和计算能力的平衡。因此，在此示例中，您应向每个站点添加相同数量的存储节点或在每个站点添加更多存储卷。

如果您的 ILM 策略更加复杂，其中包括根据存储分段名称等标准将对象放置在不同位置的规则，或者随着时间的推移更改对象位置的规则，则您对扩展所需存储位置的分析将类似，但更为复杂。

绘制整体存储容量的消耗速度图表有助于您了解要在扩展中添加多少存储以及何时需要额外存储空间。您可以使用网格管理器link:../monitor/monitoring-storage-capacity.html["监控存储容量并绘制图表"]。

在规划扩展时间时，请记住考虑采购和安装额外存储可能需要多长时间。为了简化扩展规划，当现有存储节点达到 70% 容量时，请考虑添加存储节点。
