---
sidebar: sidebar 
permalink: expand/copying-audit-logs.html 
keywords: copy audit log, Admin Node expansion, StorageGRID 
summary: 当您通过扩展程序添加新的管理节点时，其 AMS 服务仅记录其加入系统后发生的事件和操作。根据需要，您可以将审计日志从先前安装的管理节点复制到新的扩展管理节点，以便它与StorageGRID系统的其余部分同步。 
---
= 将审计日志复制到StorageGRID中的新管理节点
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
当您通过扩展程序添加新的管理节点时，其 AMS 服务仅记录其加入系统后发生的事件和操作。根据需要，您可以将审计日志从先前安装的管理节点复制到新的扩展管理节点，以便它与StorageGRID系统的其余部分同步。

.开始之前
* 您已完成添加管理节点所需的扩展步骤。
* 您已获得 `Passwords.txt`文件。


.关于此任务
要使历史审核消息在新管理节点上可用，必须手动将审核日志文件从现有管理节点复制到扩展管理节点。

[NOTE]
====
默认情况下，审计信息将发送到 `localaudit`登录每个节点。要使用此过程，您必须将管理节点配置为审计目标，如下所示：

* 您将 *管理节点/本地节点* 配置为日志目标。
* 您已将*管理节点和外部系统日志服务器*配置为日志目标。


参考link:../monitor/configure-audit-messages.html["配置审核消息和外部系统日志服务器"]了解详情。

====
.步骤
. 登录到主管理节点：
+
.. 输入以下命令： `ssh _admin@_primary_Admin_Node_IP_`
.. 输入文件中列出的密码 `Passwords.txt`。
.. 输入以下命令切换到root： `su -`
.. 输入文件中列出的密码 `Passwords.txt`。
+
当您以root用户身份登录时，提示符将从更 `$`改为 `#`。



. 停止AMS服务以防止其创建新文件： `service ams stop`
. 导航到审核导出目录：
+
`cd /var/local/audit/export/`

. 重命名源 `audit.log`文件以确保它不会覆盖您要将其复制到的扩展管理节点上的文件：
+
[listing]
----
ls -l
mv audit.log _new_name_.txt
----
. 将所有审核日志文件复制到扩展管理节点上的目标位置：
+
`scp -p * _IP_address_:/var/local/audit/export/`

. 如果系统提示您输入的密码短语 `/root/.ssh/id_rsa`，请输入文件中列出的主管理节点的SSH访问密码 `Passwords.txt`。
. 还原原始 `audit.log`文件：
+
`mv _new_name_.txt audit.log`

. 启动 AMS 服务：
+
`service ams start`

. 从服务器注销：
+
`exit`

. 登录到扩展管理节点：
+
.. 输入以下命令： `ssh admin@_expansion_Admin_Node_IP_`
.. 输入文件中列出的密码 `Passwords.txt`。
.. 输入以下命令切换到root： `su -`
.. 输入文件中列出的密码 `Passwords.txt`。
+
当您以root用户身份登录时，提示符将从更 `$`改为 `#`。



. 更新审核日志文件的用户和组设置：
+
`cd /var/local/audit/export/`

+
`chown ams-user:bycast *`

. 从服务器注销：
+
`exit`


