---
permalink: expand/rebalancing-erasure-coded-data-after-adding-storage-nodes.html 
sidebar: sidebar 
keywords: erasure coding, EC, rebalancing, site rebalance procedure, StorageGRID 
summary: 添加存储节点后、您可以使用纠删编码重新平衡过程在现有存储节点和新存储节点之间重新分布经过纠删编码的片段。 
---
= 在向StorageGRID系统添加节点后，重新平衡纠删码数据。
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
添加存储节点后、您可以使用纠删编码(EC)重新平衡过程在现有存储节点和新存储节点之间重新分布经过纠删编码的片段。

.开始之前
* 您已完成添加新存储节点的扩展步骤。
* 您已查看link:considerations-for-rebalancing-erasure-coded-data.html["重新平衡经过纠删编码的数据的注意事项"]。
* 您了解复制的对象数据不会被此过程移动，并且 EC 重新平衡过程不会移动复制的数据。但是，在确定将 EC 数据移动到何处时，会考虑复制数据。
* 您已获得 `Passwords.txt`文件。


.此操作步骤 运行时会发生什么情况
启动操作步骤 之前、请注意以下事项：

* 如果一个或多个卷脱机(卸载)或联机(挂载)但处于错误状态、EC重新平衡操作步骤 将不会启动。
* EC 重新平衡操作步骤 会临时预留大量存储。可能会触发存储警报，但会在重新平衡完成后解决。如果没有足够的存储空间用于预留， EC 重新平衡操作步骤 将失败。无论操作步骤 出现故障还是成功， EC 重新平衡操作步骤 完成后都会释放存储预留。
* 如果在EC重新平衡操作步骤正在进行时卷脱机、重新平衡操作步骤将终止。已移动的任何数据片段将保留在其新位置、不会丢失任何数据。
+
您可以在所有卷恢复联机后重新运行操作步骤。

* 运行EC重新平衡过程时、ILM操作和S3客户端操作的性能可能会受到影响。
+

NOTE: 如果要上传对象(或对象部件)的S3 API操作需要24小时以上才能完成、则在EC重新平衡过程中这些操作可能会失败。如果适用的ILM规则在加载时使用平衡放置或严格放置、则长时间放置操作将失败。将报告以下错误： `500 Internal Server Error`。

* *工作完成条件*。当满足以下任一条件时、EC重新平衡过程被视为已完成：
+
** 它无法再移动任何经过了经过数据经过了数据迁移的数据。
** 所有节点中的数据与目标数据分区的偏差均在5%以内。
** 操作步骤已运行30天。




.步骤
. 【 Review object_storage]] 查看计划重新平衡的站点的当前对象存储详细信息。
+
.. 选择*节点*。
.. 选择站点上的第一个存储节点。
.. 选择 * 存储 * 选项卡。
.. 将光标置于"已用存储-对象数据"图表上方、可查看存储节点上当前复制的数据量和经过重复数据操作的数据。
.. 重复上述步骤以查看站点上的其他存储节点。


. 登录到主管理节点：
+
.. 输入以下命令： `ssh admin@_primary_Admin_Node_IP_`
.. 输入文件中列出的密码 `Passwords.txt`。
.. 输入以下命令切换到root： `su -`
.. 输入文件中列出的密码 `Passwords.txt`。
+
当您以root用户身份登录时，提示符将从更 `$`改为 `#`。



. 启动操作步骤 ：
+
`re平衡数据启动--site "_ssite-name_"

+
对于"_site-name_"、指定添加新存储节点的第一个站点。用引号括起来。 `site-name`

+
此时将启动 EC 重新平衡操作步骤 ，并返回作业 ID 。

. 复制作业 ID 。
. [[view-status]]监控EC重新平衡操作步骤的状态。
+
** 要查看单个 EC 重新平衡操作步骤 的状态，请执行以下操作：
+
`rebalance-data status --job-id _job-id_`

+
对于 `_job-id_`，指定在开始过程时返回的ID。

** 要查看当前 EC 重新平衡操作步骤 的状态以及先前完成的任何过程：
+
`rebalance-data status`

+
[NOTE]
====
要获取有关 rebalance-data 命令的帮助，请执行以下操作：

`rebalance-data --help`

====


. 根据返回的状态执行其他步骤：
+
** 如果 `State`为 `In progress`，则EC重新平衡操作仍在运行。您应定期监控操作步骤 ，直到其完成。
+
转到节点页面来评估站点中存储节点的数据分布。

+
EC重新平衡作业被视为已完成、当所有节点中的数据与目标数据分区的偏差在5%以内时、此作业将停止。

** 如果 `State`是 `Success`，则可以选择<<review_object_storage,查看对象存储>>查看站点的更新详细信息。
+
现在，经过纠删编码的数据应在站点的存储节点之间更加平衡。

** 如果 `State`为 `Failure`：
+
... 确认站点上的所有存储节点均已连接到网格。
... 检查并解决可能影响这些存储节点的任何警报。
... 重新启动EC重新平衡操作步骤 ：
+
`rebalance-data start –-job-id _job-id_`

... <<view-status,查看状态>>新程序的执行情况。如果 `State`仍然存在 `Failure`，请联系技术支持。




. 如果 EC 重新平衡操作步骤 生成的负载过多（例如，载入操作受到影响），请暂停操作步骤 。
+
`rebalance-data pause --job-id _job-id_`

. 如果您需要终止 EC 重新平衡操作步骤 （例如，以便执行 StorageGRID 软件升级），请输入以下内容：
+
`rebalance-data terminate --job-id _job-id_`

+

NOTE: 终止EC重新平衡操作步骤后、已移动的所有数据片段仍会保留在其新位置。数据不会移回原始位置。

. 如果要在多个站点上使用纠删编码，请对所有其他受影响站点运行此操作步骤 。

