---
permalink: expand/updating-subnets-for-grid-network.html 
sidebar: sidebar 
keywords: expand, expansion, add subnets, Grid Network, StorageGRID 
summary: 在扩展中添加网格节点或新站点时，您可能需要更新子网或向网格网络添加子网。 
---
= 在StorageGRID中添加或更新网格网络子网以进行扩展
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在扩展中添加网格节点或新站点时，您可能需要更新子网或向网格网络添加子网。

StorageGRID 会维护一个网络子网列表，用于在网格网络（ eth0 ）上的网格节点之间进行通信。这些条目包括 StorageGRID 系统中每个站点用于网格网络的子网，以及通过网格网络网关访问的 NTP ， DNS ， LDAP 或其他外部服务器所使用的任何子网。

.开始之前
* 您已使用登录到网格管理器link:../admin/web-browser-requirements.html["支持的 Web 浏览器"]。
* 您拥有link:../admin/admin-group-permissions.html["维护或root访问权限"]。
* 您具有配置密码短语。
* 您已获得要配置的子网的网络地址，以 CIDR 表示法表示。


.关于此任务
如果任何新节点的子网上有一个以前未使用的网格网络 IP 地址，则必须在开始扩展之前将此新子网添加到网格网络子网列表中。否则，您必须取消扩展，添加新子网并重新启动操作步骤 。

[NOTE]
====
请勿对任何节点的网格网络、管理网络或客户端网络使用包含以下 IPv4 地址的子网：

* 192,168,130,101
* 192,168,131,101
* 192,168,130,102
* 192,168,131,102
* 198.51.100.2
* 198.51.100.4


例如，不要对任何节点的网格网络、管理网络或客户端网络使用以下子网范围：

* 192.168.130.0/24，因为此子网范围包含 IP 地址 192.168.130.101 和 192.168.130.102
* 192.168.131.0/24，因为此子网范围包含 IP 地址 192.168.131.101 和 192.168.131.102
* 198.51.100.0/24，因为此子网范围包含 IP 地址 198.51.100.2 和 198.51.100.4


====
.步骤
. 选择*维护* > *网络* > *电网*。
. 选择*添加其他子网*以使用CIDR表示法添加新子网。
+
例如，输入 `10.96.104.0/22`。

. 输入配置密码短语，然后选择 * 保存 * 。
. 等待更改应用完毕，然后下载新的恢复包。
+
.. 选择*维护* > *系统* > *恢复包*。
.. 输入 * 配置密码短语 * 。
+

CAUTION: 恢复包文件必须是安全的，因为它包含可用于从StorageGRID系统获取数据的加密密钥和密码。它还用于恢复主管理节点。





您指定的子网将自动为 StorageGRID 系统配置。
