---
permalink: expand/vmware-adding-storage-volumes-to-storage-node.html 
sidebar: sidebar 
keywords: expand, expansion, storage node, add storage volumes, VMware, StorageGRID 
summary: 如果存储节点包含的存储卷少于 16 个，则可以使用 VMware vSphere 添加卷来增加其容量。 
---
= 在StorageGRID中向 VMware 存储节点添加存储卷
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果存储节点包含的存储卷少于 16 个，则可以使用 VMware vSphere 添加卷来增加其容量。

.开始之前
* 您可以访问link:../swnodes/index.html["为 VMware 部署安装StorageGRID的说明"]。
* 您已获得 `Passwords.txt`文件。
* 您拥有 link:../admin/admin-group-permissions.html["特定访问权限"]。



CAUTION: 在软件升级、恢复操作步骤 或其他扩展操作步骤 处于活动状态时、请勿尝试向存储节点添加存储卷。

.关于此任务
添加存储卷时，此存储节点将暂时不可用。您应一次在一个存储节点上执行此操作步骤 ，以避免影响面向客户端的网格服务。

.步骤
. 如有必要，请安装新的存储硬件并创建新的 VMware 数据存储库。
. 向虚拟机添加一个或多个硬盘以用作存储（对象存储）。
+
.. 打开 VMware vSphere Client 。
.. 编辑虚拟机设置以添加一个或多个附加硬盘。


+
硬盘通常配置为虚拟机磁盘（ Virtual Machine Disk ， VMDK ）。VMDK更常用且更易于管理、而对于使用较大对象(例如大于100 MB)的工作负载、RDM可能会提供更好的性能。有关向虚拟机添加硬盘的详细信息，请参见 VMware vSphere 文档。

. 使用VMware vSphere Client中的*Restart Guest OS*选项或在与虚拟机的ssh会话中输入以下命令，重新启动虚拟机：``sudo reboot``
+

NOTE: 请勿使用*Power Off*或*Reset *重新启动虚拟机。

. 配置新存储以供存储节点使用：
+
.. 登录到网格节点：
+
... 输入以下命令： `ssh admin@_grid_node_IP_`
... 输入文件中列出的密码 `Passwords.txt`。
... 输入以下命令切换到root： `su -`
... 输入文件中列出的密码 `Passwords.txt`。当您以root用户身份登录时，提示符将从更 `$`改为 `#`。


.. 配置新存储卷：
+
`sudo add_rangedbs.rb`

+
此脚本将查找任何新存储卷并提示您对其进行格式化。

.. 输入 * 。 * 接受格式化。
.. 如果先前已对任何卷进行格式化，请确定是否要重新格式化这些卷。
+
*** 输入 * y * 重新格式化。
*** 输入 * 。 n* 可跳过重新格式化。




+
该 `setup_rangedbs.sh`脚本将自动运行。

. 检查服务是否正确启动：
+
.. 查看服务器上所有服务的状态列表：
+
`sudo storagegrid-status`

+
状态将自动更新。

.. 请等待所有服务均已运行或已验证。
.. 退出状态屏幕：
+
`Ctrl+C`



. 验证存储节点是否联机：
+
.. 使用登录到网格管理器link:../admin/web-browser-requirements.html["支持的 Web 浏览器"]。
.. 选择“*节点*”>“*存储节点*”>“*任务*”。
.. 如果“*存储状态*”下拉列表设置为“只读”或“离线”，请选择“*在线*”。
.. 选择 * 保存 * 。


. 要查看新的对象存储，请选择*存储*。
. 查看*Volumes*表中的详细信息。


.结果
您可以使用存储节点的扩展容量来保存对象数据。
