---
permalink: troubleshoot/searching-for-and-restoring-potentially-lost-objects.html 
sidebar: sidebar 
keywords: how to search lost object, how to restore lost object, how to find lost object 
summary: '可能会找到并还原已触发*对象丢失*警报和旧对象丢失(丢失)警报且您已确定为可能丢失的对象。' 
---
= 搜索并还原可能丢失的对象
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
可能会找到并还原已触发*对象丢失*警报和旧对象丢失(丢失)警报且您已确定为可能丢失的对象。

.开始之前
* 您具有任何丢失的对象的UUID，如中所示link:../troubleshoot/investigating-lost-objects.html["调查丢失的对象"]。
* 您已获得 `Passwords.txt`文件。


.关于此任务
您可以按照此操作步骤 在网格中其他位置查找丢失对象的复制副本。在大多数情况下，找不到丢失的对象。但是，在某些情况下，如果您立即采取措施，则可能能够找到并还原丢失的复制对象。


CAUTION: 请联系技术支持以获得有关此操作步骤 的帮助。

.步骤
. 在管理节点中，搜索审核日志以查找可能的对象位置：
+
.. 登录到网格节点：
+
... 输入以下命令： `ssh admin@grid_node_IP`
... 输入文件中列出的密码 `Passwords.txt`。
... 输入以下命令切换到root： `su -`
... 输入文件中列出的密码 `Passwords.txt`。当您以root用户身份登录时，提示符将从更 `$`改为 `#`。


.. [[substage-1b]]更改为审核日志所在的目录。
+
--
审核日志目录和适用节点取决于您的审核目标设置。

[cols="1a,2a"]
|===
| 选项 | 目标 


 a| 
本地节点(默认)
 a| 
`/var/local/log/localaudit.log`



 a| 
管理节点/本地节点
 a| 
*** 管理节点(主节点和非主节点)： `/var/local/audit/export/audit.log`
*** 所有节点： `/var/local/log/localaudit.log`在此模式下、文件通常为空或缺失。




 a| 
外部系统日志服务器
 a| 
`/var/local/log/localaudit.log`

|===
根据您的审核目标设置、输入： `cd /var/local/log`或 `/var/local/audit/export/`

要了解更多信息，请参阅 link:../monitor/configure-audit-messages.html#select-audit-information-destinations["选择审核信息目标"]。

--
.. 使用grep提取link:../audit/object-ingest-transactions.html["与可能丢失的对象关联的审核消息"]并将其发送到输出文件。输入： `grep uuid-value audit_file_name > output_file_name`
+
例如：

+
[listing]
----
Admin: # grep 926026C4-00A4-449B-AC72-BCCA72DD1311 audit.log > /var/local/tmp/messages_about_lost_object.txt
----
.. 使用 grep 从此输出文件中提取丢失位置（ LLLST ）审核消息。输入： `grep LLST output_file_name`
+
例如：

+
[listing]
----
Admin: # grep LLST /var/local/tmp/messages_about_lost_objects.txt
----
+
LLST审核消息类似于此示例消息。

+
[listing]
----
[AUDT:[NOID(UI32):12448208][CBIL(UI64):0x38186FE53E3C49A5]
[UUID(CSTR):"926026C4-00A4-449B-AC72-BCCA72DD1311"][LTYP(FC32):CLDI]
[PCLD(CSTR):"/var/local/rangedb/1/p/17/11/00rH0%DkRs&LgA#3tN6"]
[TSRC(FC32):SYST][RSLT(FC32):NONE][AVER(UI32):10][ATIM(UI64):1581535134379225]
[ATYP(FC32):LLST][ANID(UI32):12448208][AMID(FC32):CLSM][ATID(UI64):7086871083190743409]]
----
.. 在 LLST 消息中找到 PCLD 字段和 NOID 字段。
+
如果存在，则 PCLD 的值为磁盘上缺少复制对象副本的完整路径。NOID 的值是可能找到对象副本的 LDR 的节点 ID 。

+
如果找到对象位置，您可能能够还原该对象。

.. 找到与此LDR节点ID关联的存储节点。在网格管理器中，选择 * 支持 * > * 工具 * > * 网格拓扑 * 。然后选择 * 。 Data Center_* > * 。 Storage Node_* > * 。
+
LDR服务的节点ID位于节点信息表中。查看每个存储节点的信息，直到找到托管此 LDR 的存储节点为止。



. 确定对象是否位于审核消息中指示的存储节点上：
+
.. 登录到网格节点：
+
... 输入以下命令： `ssh admin@grid_node_IP`
... 输入文件中列出的密码 `Passwords.txt`。
... 输入以下命令切换到root： `su -`
... 输入文件中列出的密码 `Passwords.txt`。
+
当您以root用户身份登录时，提示符将从更 `$`改为 `#`。



.. 确定对象的文件路径是否存在。
+
对于对象的文件路径，请使用 LLST 审核消息中的 PCLD 值。

+
例如，输入：

+
[listing]
----
ls '/var/local/rangedb/1/p/17/11/00rH0%DkRs&LgA%#3tN6'
----
+

NOTE: 在命令中、始终将对象文件路径用单引号引起来以转义任何特殊字符。

+
*** 如果未找到对象路径、则对象将丢失、无法使用此操作步骤 还原。请联系技术支持。
*** 如果找到对象路径、请继续执行下一步。您可以尝试将找到的对象还原回 StorageGRID 。




. 如果找到对象路径、请尝试将此对象还原到StorageGRID ：
+
.. 从同一个存储节点中，更改对象文件的所有权，以便可通过 StorageGRID 进行管理。输入： `chown ldr-user:bycast 'file_path_of_object'`
.. Telnet 到 localhost 1402 以访问 LDR 控制台。输入： `telnet 0 1402`
.. 输入： `cd /proc/STOR`
.. 输入： `Object_Found 'file_path_of_object'`
+
例如，输入：

+
[listing]
----
Object_Found '/var/local/rangedb/1/p/17/11/00rH0%DkRs&LgA%#3tN6'
----
+
发出 `Object_Found`命令会向网格通知对象的位置。它还会触发活动ILM策略、这些策略会根据每个策略中的指定创建额外的副本。

+

NOTE: 如果找到对象的存储节点处于脱机状态、您可以将对象复制到任何处于联机状态的存储节点。将对象放置在联机存储节点的任何 /var/local/rangedb 目录中。然后、使用该对象的文件路径发出 `Object_Found`命令。

+
*** 如果无法还原此对象、则此命令将 `Object_Found`失败。请联系技术支持。
*** 如果对象已成功还原到 StorageGRID ，则会显示一条成功消息。例如：
+
[listing]
----
ade 12448208: /proc/STOR > Object_Found '/var/local/rangedb/1/p/17/11/00rH0%DkRs&LgA%#3tN6'

ade 12448208: /proc/STOR > Object found succeeded.
First packet of file was valid. Extracted key: 38186FE53E3C49A5
Renamed '/var/local/rangedb/1/p/17/11/00rH0%DkRs&LgA%#3tN6' to '/var/local/rangedb/1/p/17/11/00rH0%DkRt78Ila#3udu'
----
+
继续下一步。





. 如果对象已成功还原到StorageGRID、请验证是否已创建新位置：
+
.. 使用登录到网格管理器link:../admin/web-browser-requirements.html["支持的 Web 浏览器"]。
.. 选择 * ILM * > * 对象元数据查找 * 。
.. 输入UUID并选择*查找*。
.. 查看元数据并验证新位置。


. 在管理节点中，搜索此对象的 ORLM 审核消息的审核日志，以确认信息生命周期管理（ ILM ）已根据需要放置副本。
+
.. 登录到网格节点：
+
... 输入以下命令： `ssh admin@grid_node_IP`
... 输入文件中列出的密码 `Passwords.txt`。
... 输入以下命令切换到root： `su -`
... 输入文件中列出的密码 `Passwords.txt`。当您以root用户身份登录时，提示符将从更 `$`改为 `#`。


.. 更改为审核日志所在的目录。请参阅<<substep-1b,子步骤1. b.>>。
.. 使用 grep 将与对象关联的审核消息提取到输出文件中。输入： `grep uuid-value audit_file_name > output_file_name`
+
例如：

+
[listing]
----
Admin: # grep 926026C4-00A4-449B-AC72-BCCA72DD1311 audit.log > /var/local/tmp/messages_about_restored_object.txt
----
.. 使用 grep 从此输出文件中提取对象规则已满足（ ORLM ）审核消息。输入： `grep ORLM output_file_name`
+
例如：

+
[listing]
----
Admin: # grep ORLM /var/local/tmp/messages_about_restored_object.txt
----
+
ORLM审核消息类似于此示例消息。

+
[listing]
----
[AUDT:[CBID(UI64):0x38186FE53E3C49A5][RULE(CSTR):"Make 2 Copies"]
[STAT(FC32):DONE][CSIZ(UI64):0][UUID(CSTR):"926026C4-00A4-449B-AC72-BCCA72DD1311"]
[LOCS(CSTR):"**CLDI 12828634 2148730112**, CLDI 12745543 2147552014"]
[RSLT(FC32):SUCS][AVER(UI32):10][ATYP(FC32):ORLM][ATIM(UI64):1563398230669]
[ATID(UI64):15494889725796157557][ANID(UI32):13100453][AMID(FC32):BCMS]]
----
.. 在审核消息中找到 LOC 字段。
+
如果存在，则在 LOM 中的 CLDI 值为节点 ID 和创建对象副本的卷 ID 。此消息显示已应用 ILM ，并且已在网格中的两个位置创建两个对象副本。



. link:resetting-lost-and-missing-object-counts.html["重置丢失和丢失的对象计数"]在网格管理器中。

