---
permalink: troubleshoot/troubleshooting-lost-and-missing-object-data.html 
sidebar: sidebar 
keywords: how to troubleshoot lost object data, how to troubleshoot missing object data 
summary: 可以出于多种原因检索对象，包括从客户端应用程序读取请求，对复制的对象数据进行后台验证， ILM 重新评估以及在存储节点恢复期间还原对象数据。 
---
= 对丢失和丢失的对象数据进行故障排除
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
可以出于多种原因检索对象，包括从客户端应用程序读取请求，对复制的对象数据进行后台验证， ILM 重新评估以及在存储节点恢复期间还原对象数据。

StorageGRID系统使用对象元数据中的位置信息来确定从哪个位置检索对象。如果在预期位置未找到该对象的副本，系统将尝试从系统的其他位置检索该对象的另一个副本，假设 ILM 策略包含制作该对象的两个或更多个副本的规则。

如果检索成功， StorageGRID系统将替换该对象的丢失副本。否则，将触发*对象可能丢失*警报，如下所示：

* 对于复制的副本、如果无法检索到另一个副本、则会将对象视为丢失、并触发警报。
* 对于经过删除编码的副本、如果无法从预期位置检索副本、则在尝试从其他位置检索副本之前、已检测到损坏的副本(ECO)属性会增加一个。如果未找到其他副本，则会触发警报。


您应该立即调查所有*对象可能丢失*警报，以确定丢失的根本原因，并确定对象是否仍存在于离线或当前不可用的存储节点中。看link:../troubleshoot/investigating-potentially-lost-objects.html["调查可能丢失的物品"] 。丢失物品警报可能会因谨慎而被错误触发。

如果没有副本的对象数据丢失，则没有恢复解决方案。但是，你必须link:../troubleshoot/investigating-potentially-lost-objects.html#reset-lost-obj-count["重置可能丢失的对象计数器"]以防止已知丢失的物品掩盖任何新的丢失物品。
