---
permalink: ilm/advantages-disadvantages-of-ingest-options.html 
sidebar: sidebar 
keywords: ingest options, balance ingest, strict ingest, dual commit ingest 
summary: 了解在载入时保护数据的三个选项中每一个选项（平衡，严格或双提交）的优缺点有助于您确定要为 ILM 规则选择哪个选项。 
---
= 加热选项的优点、缺点和限制
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
了解在载入时保护数据的三个选项（平衡，严格或双重提交）中每一个选项的优缺点有助于您确定要为 ILM 规则选择哪个选项。

有关安装选项的概述，请参见link:data-protection-options-for-ingest.html["加热选项"]。



== 平衡而严格的选项的优势

与在载入期间创建临时副本的双提交相比，这两个同步放置选项具有以下优势：

* * 更好的数据安全性 * ：对象数据会按照 ILM 规则放置说明中的说明立即受到保护，可以对其进行配置，以防止出现多种故障情况，包括多个存储位置发生故障。双提交只能防止丢失一个本地副本。
* * 更高效的网格操作 * ：每个对象仅在载入时进行一次处理。由于 StorageGRID 系统不需要跟踪或删除中间副本，因此处理负载较低，数据库空间占用较少。
* * （平衡）建议 * ：平衡选项可提供最佳 ILM 效率。除非需要严格的加载行为或网格满足使用双重提交的所有标准、否则建议使用均衡选项。
* * （严格）对象位置的确定性 * ： strict 选项可确保根据 ILM 规则中的放置说明立即存储对象。




== 平衡而严格的选项的缺点

与双提交相比，平衡和严格选项存在一些缺点：

* * 客户端载入时间更长 * ：客户端载入延迟可能更长。使用均衡或严格选项时、只有在创建和存储所有经过删除的片段或复制的副本之后、才会向客户端返回"成功地执行"消息。但是，对象数据很可能会更快地到达最终放置位置。
* *(严格)更高的加载失败率*：使用严格选项、只要StorageGRID 无法立即创建ILM规则中指定的所有副本、加载就会失败。如果所需存储位置暂时脱机或网络问题发生原因 在站点之间复制对象时出现延迟，则可能会出现较高的载入失败率。
* 在某些情况下 * （严格） S3 多部分上传放置可能与预期不同 * ：严格地说，您希望对象按照 ILM 规则的说明放置，或者载入操作失败。但是、对于S3多部分上传、载入对象时会针对对象的每个部分评估ILM、多部分上传完成后、会针对整个对象评估ILM。在以下情况下，这可能会导致放置方式与您预期不同：
+
** * 如果在 S3 多部件上传过程中 ILM 发生变化 * ：由于每个部件都是根据在载入部件时处于活动状态的规则放置的，因此在多部件上传完成后，对象的某些部分可能不符合当前的 ILM 要求。在这些情况下，对象的载入不会失败。相反、未正确放置的任何部件将排队等待ILM重新评估、并在稍后移动到正确的位置。
** * 当 ILM 规则按大小筛选时 * ：在评估某个部件的 ILM 时， StorageGRID 会按部件的大小进行筛选，而不是按对象的大小进行筛选。这意味着、对象的某些部分可以存储在不满足对象整体ILM要求的位置。例如，如果规则指定所有 10 GB 或更大的对象都存储在 DC1 中，而所有较小的对象存储在 DC2 中，则在载入时， 10 部分多部分上传的每个 1 GB 部分都存储在 DC2 中。评估对象的 ILM 时，对象的所有部分都会移至 DC1 。


* * （严格）更新对象标记或元数据后，如果无法进行新要求的放置，则载入不会失败 * ：严格地说，您希望按照 ILM 规则的说明放置对象，或者使载入失败。但是，在更新网格中已存储的对象的元数据或标记时，不会重新载入该对象。这意味着、更新触发的任何对象放置更改不会立即生效。如果通过正常后台 ILM 流程重新评估 ILM ，则会进行放置更改。如果无法进行所需的放置更改(例如、由于新需要的位置不可用)、更新后的对象将保留其当前放置位置、直到可以进行放置更改为止。




== 使用平衡和严格选项对对象放置的限制

对于具有以下任何放置说明的ILM规则、不能使用"平衡"或"严格"选项：

* 第 0 天放置在云存储池中。
* 规则将用户定义的创建时间作为其参考时间时放置在云存储池中。


之所以存在这些限制、是因为StorageGRID无法同步向云存储池创建副本、而用户定义的创建时间可以解析为当前时间。



== ILM规则和一致性如何相互作用以影响数据保护

ILM规则和一致性选择都会影响对象的保护方式。这些设置可以进行交互。

例如、为ILM规则选择的加载行为会影响对象副本的初始放置、而存储对象时使用的一致性会影响对象元数据的初始放置。由于StorageGRID需要同时访问对象的数据和元数据才能满足客户端请求、因此为一致性和载入行为选择匹配的保护级别可以提供更好的初始数据保护、并提高系统响应的可预测性。

下面简要总结了StorageGRID中提供的一致性值：

* *all*：所有节点都会立即接收对象元数据、否则请求将失败。
* *STRONG-GLOBAL*：对象元数据立即分发到所有站点。保证所有站点中所有客户端请求的写入后读一致性。
* *strong-sit*：对象元数据会立即分发到站点上的其他节点。保证站点内所有客户端请求的写入后读一致性。
* *read-after-new-write*：为新对象提供写入后读取一致性，并最终为对象更新提供一致性。提供高可用性和数据保护保证。建议用于大多数情况。
* *可用*：为新对象和对象更新提供最终一致性。对于S3存储分段、请仅在需要时使用(例如、对于包含很少读取的日志值的存储分段、或者对于不存在的密钥执行HEAD或GET操作)。S3 FabricPool 存储分段不支持。



NOTE: 在选择一致性值之前，link:../s3/consistency-controls.html["阅读完整的一致性问题描述"]。在更改默认值之前，您应了解其优势和限制。



== 示例：如何交互一致性和ILM规则

假设您有一个双站点网格、该网格具有以下ILM规则、并且具有以下一致性：

* * ILM 规则 * ：创建两个对象副本，一个在本地站点，一个在远程站点。使用严格的加热行为。
* *一致性*：强全局(对象元数据立即分发到所有站点)。


当客户端将对象存储到网格时， StorageGRID 会创建两个对象副本并将元数据分发到两个站点，然后再向客户端返回成功。

在载入成功消息时，此对象将受到完全保护，不会丢失。例如，如果本地站点在载入后不久丢失，则远程站点上仍存在对象数据和对象元数据的副本。此对象完全可检索。

如果您改用相同的ILM规则和强站点一致性、则在将对象数据复制到远程站点之后、在远程站点分发对象元数据之前、客户端可能会收到一条成功消息。在这种情况下，对象元数据的保护级别与对象数据的保护级别不匹配。如果本地站点在载入后不久丢失，则对象元数据将丢失。无法检索此对象。

一致性和ILM规则之间的相互关系可能很复杂。如果需要帮助、请联系NetApp。

.相关信息
link:example-5-ilm-rules-and-policy-for-strict-ingest-behavior.html["示例 5 ：用于严格载入行为的 ILM 规则和策略"]
