---
permalink: ilm/example-7-compliant-ilm-policy-for-s3-object-lock.html 
sidebar: sidebar 
keywords: ILM policy,S3 Object Lock 
summary: 在定义 ILM 策略以满足启用了 S3 对象锁定的存储分段中对象的对象保护和保留要求时，您可以在此示例中使用 S3 存储分段， ILM 规则和 ILM 策略作为起点。 
---
= 示例 7 ： S3 对象锁定的兼容 ILM 策略
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在定义 ILM 策略以满足启用了 S3 对象锁定的存储分段中对象的对象保护和保留要求时，您可以在此示例中使用 S3 存储分段， ILM 规则和 ILM 策略作为起点。


NOTE: 如果您在先前的 StorageGRID 版本中使用了原有合规性功能，则也可以使用此示例来帮助管理启用了原有合规性功能的任何现有存储分段。


CAUTION: 以下 ILM 规则和策略仅为示例。配置 ILM 规则的方法有多种。在激活新策略之前、请对其进行模拟、以确认其是否按预期工作、以防止内容丢失。

.相关信息
* link:managing-objects-with-s3-object-lock.html["使用 S3 对象锁定管理对象"]
* link:creating-ilm-policy.html["创建ILM策略"]




== S3 对象锁定的分段和对象示例

在此示例中，名为 Bank of ABC 的 S3 租户帐户使用租户管理器创建了一个启用了 S3 对象锁定的存储分段，用于存储重要的银行记录。

[cols="2a,2a"]
|===
| 存储分段定义 | 示例值 


 a| 
租户帐户名称
 a| 
ABC 银行



 a| 
分段名称
 a| 
银行记录



 a| 
存储分段区域
 a| 
us-east-1 （默认）

|===
添加到银行记录分段的每个对象和对象版本将对和 `legal hold`设置使用以下值 `retain-until-date`。

[cols="1a,2a"]
|===
| 为每个对象设置 | 示例值 


 a| 
`retain-until-date`
 a| 
"2030-12-30T23：59：59Z"(2030年12月30日)

每个对象版本都有自己的 `retain-until-date`设置。此设置可以增加，但不能减少。



 a| 
`legal hold`
 a| 
"Off"(关闭)(无效)

在保留期限内，可以随时对任何对象版本进行合法保留或取消合法保留。如果对象处于合法保留状态、则即使已访问、也无法删除该对象 `retain-until-date`。

|===


== 适用于S3对象锁定的ILM规则1示例：具有存储分段匹配的纠删编码配置文件

此示例 ILM 规则仅适用于名为 ABC 银行的 S3 租户帐户。它会匹配存储分段中的任何对象 `bank-records`、然后使用纠删编码将对象存储在三个数据中心站点上、并使用6+3纠删编码配置文件。此规则可满足启用了S3对象锁定的存储分段的要求：使用"数据加载时间"作为参考时间、从第0天到永远在存储节点上保留一个副本。

[cols="1a,2a"]
|===
| 规则定义 | 示例值 


 a| 
规则名称
 a| 
合规规则：银行记录分段中的EC对象- ABC银行



 a| 
租户帐户
 a| 
ABC 银行



 a| 
分段名称
 a| 
`bank-records`



 a| 
高级筛选器
 a| 
对象大小（ MB ）大于 1

*注：*此筛选器可确保擦除编码不会用于1 MB或更小的对象。

|===
[cols="1a,2a"]
|===
| 规则定义 | 示例值 


 a| 
参考时间
 a| 
载入时间



 a| 
放置
 a| 
从 Day 0 存储永久存储



 a| 
纠删编码配置文件
 a| 
* 在三个数据中心站点的存储节点上创建经过擦除编码的副本
* 使用 6+3 纠删编码方案


|===


== 适用于 S3 对象锁定的 ILM 规则 2 示例：不合规规则

此示例 ILM 规则最初会将两个复制的对象副本存储在存储节点上。一年后，它会将一个副本永久存储在云存储池中。由于此规则使用云存储池，因此它不符合要求，并且不会应用于启用了 S3 对象锁定的分段中的对象。

[cols="1a,2a"]
|===
| 规则定义 | 示例值 


 a| 
规则名称
 a| 
不合规规则：使用云存储池



 a| 
租户帐户
 a| 
未指定



 a| 
Bucket Name
 a| 
未指定、但仅适用于未启用S3对象锁定(或原有合规性功能)的分段。



 a| 
高级筛选器
 a| 
未指定

|===
[cols="1a,2a"]
|===
| 规则定义 | 示例值 


 a| 
参考时间
 a| 
载入时间



 a| 
放置
 a| 
* 在第 0 天，在数据中心 1 和数据中心 2 的存储节点上保留两个复制副本 365 天
* 1 年后，将一个复制副本永久保留在云存储池中


|===


== 适用于 S3 对象锁定的 ILM 规则 3 示例：默认规则

此示例 ILM 规则会将对象数据复制到两个数据中心中的存储池。此合规规则是 ILM 策略中的默认规则。它不包括任何筛选器，不使用非当前参考时间，并满足启用了 S3 对象锁定的存储分段的要求：从 0 天到永久，存储节点上保留两个对象副本，并使用 Ingest 作为参考时间。

[cols="1a,2a"]
|===
| 规则定义 | 示例值 


 a| 
规则名称
 a| 
默认合规规则：两个副本两个数据中心



 a| 
租户帐户
 a| 
未指定



 a| 
Bucket Name
 a| 
未指定



 a| 
高级筛选器
 a| 
未指定

|===
[cols="1a,2a"]
|===
| 规则定义 | 示例值 


 a| 
参考时间
 a| 
载入时间



 a| 
放置
 a| 
从 0 天到永久，请保留两个复制副本—一个在数据中心 1 的存储节点上，一个在数据中心 2 的存储节点上。

|===


== S3 对象锁定的兼容 ILM 策略示例

要创建有效保护系统中所有对象的 ILM 策略，包括启用了 S3 对象锁定的分段中的对象，您必须选择满足所有对象存储要求的 ILM 规则。然后、您必须模拟并激活此策略。



=== 向策略中添加规则

在此示例中， ILM 策略包括三个 ILM 规则，其顺序如下：

. 一种使用纠删编码保护启用了 S3 对象锁定的特定分段中大于 1 MB 的对象的合规规则。从 0 天到永久，对象存储在存储节点上。
. 一种不合规的规则，在存储节点上创建两个复制的对象副本一年，然后将一个对象副本永久移动到云存储池。此规则不适用于启用了 S3 对象锁定的存储分段，因为它使用的是云存储池。
. 一种默认合规规则，用于在存储节点上创建从 0 天到永久的两个复制对象副本。




=== 模拟策略

在向策略添加规则、选择默认合规规则并排列其他规则之后、您应通过测试启用了S3对象锁定的存储分段中的对象以及其他存储分段中的对象来模拟策略。例如，在模拟示例策略时，您希望按如下所示评估测试对象：

* 第一个规则仅与 ABC 银行租户的存储分段记录中大于 1 MB 的测试对象匹配。
* 第二个规则将匹配所有其他租户帐户的所有不合规分段中的所有对象。
* 默认规则将与以下对象匹配：
+
** ABC银行租户的存储分段库记录中的对象不超过1 MB。
** 为所有其他租户帐户启用了 S3 对象锁定的任何其他分段中的对象。






=== 激活策略

如果您完全确信新策略会按预期保护对象数据，则可以激活此策略。
