---
permalink: ilm/guidelines-for-creating-storage-pools.html 
sidebar: sidebar 
keywords: storage pool guidelines 
summary: 配置和使用存储池、通过在多个站点之间分布数据来防止数据丢失。复制的副本和经过删除编码的副本需要不同的存储池配置。 
---
= 创建存储池的准则
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
配置和使用存储池、通过在多个站点之间分布数据来防止数据丢失。复制的副本和经过删除编码的副本需要不同的存储池配置。

请参阅。 link:using-multiple-storage-pools-for-cross-site-replication.html["使用复制和纠删编码启用站点丢失保护的示例"]



== 所有存储池的准则

* 尽可能简化存储池配置。请勿创建超出所需数量的存储池。
* 创建具有尽可能多节点的存储池。每个存储池应包含两个或更多节点。如果节点不可用，则节点不足的存储池可以对发生原因 ILM 进行回退。
* 避免创建或使用重叠的存储池（包含一个或多个相同节点）。如果存储池重叠，则可能会在同一节点上保存多个对象数据副本。
* 通常、不要使用所有存储节点存储池(StorageGRID 11.6及更早版本)或所有站点站点。这些项会自动更新、以包括您在扩展中添加的任何新站点、而这可能不是您想要的行为。




== 用于复制副本的存储池准则

* 对于使用的站点丢失保护link:what-replication-is.html["复制"]，请在中指定一个或多个特定于站点的存储池link:create-ilm-rule-define-placements.html["每个ILM规则的放置说明"]。
+
在StorageGRID 安装期间、系统会自动为每个站点创建一个存储池。

+
对每个站点使用存储池可确保复制的对象副本准确放置在所需位置（例如，每个站点上的每个对象一个副本，以实现站点丢失保护）。

* 如果要在扩展中添加站点、请创建一个仅包含新站点的新存储池。然后、link:working-with-ilm-rules-and-ilm-policies.html#edit-an-ilm-rule["更新ILM规则"]控制在新站点上存储哪些对象。
* 如果副本数小于存储池数、则系统会分布这些副本、以平衡各个池之间的磁盘使用量。
* 如果存储池重叠（包含相同的存储节点），则对象的所有副本可能只保存在一个站点上。您必须确保选定存储池不包含相同的存储节点。




== 用于擦除编码副本的存储池准则

* 对于使用的站点丢失保护link:what-erasure-coding-is.html["纠删编码"]，请创建至少包含三个站点的存储池。如果存储池仅包含两个站点、则不能使用该存储池进行纠删编码。对于具有两个站点的存储池，没有可用的纠删编码方案。
* 存储池中包含的存储节点和站点数量决定了哪些link:what-erasure-coding-schemes-are.html["纠删编码方案"]可用。
* 如果可能，存储池中的存储节点数应超过您选择的纠删编码方案所需的最小存储节点数。例如，如果您使用 6+3 纠删编码方案，则必须至少有九个存储节点。但是，建议每个站点至少另外配置一个存储节点。
* 尽可能均匀地在各个站点之间分布存储节点。例如，要支持 6+3 纠删编码方案，请配置一个存储池，使其在三个站点中至少包含三个存储节点。
* 如果吞吐量要求较高、则在站点之间的网络延迟超过100毫秒时、不建议使用包含多个站点的存储池。随着延迟增加， StorageGRID 创建，放置和检索对象片段的速率会因 TCP 网络吞吐量降低而大幅下降。
+
吞吐量的减少会影响对象的最大可实现写入和检索速率(如果选择"均衡"或"严格"作为写入行为)、或者可能导致ILM队列积压(如果选择"双提交"作为写入行为)。请参阅。 link:what-ilm-rule-is.html#ilm-rule-ingest-behavior["ILM规则加热行为"]

+

NOTE: 如果您的网格仅包含一个站点、则系统将阻止您使用纠删编码配置文件中的所有存储节点存储池(StorageGRID 11.5及更早版本)或所有站点站点。此行为可防止在添加第二个站点时配置文件变得无效。


