---
permalink: ilm/lifecycle-of-cloud-storage-pool-object.html 
sidebar: sidebar 
keywords: lifecycle of cloud storage pool object 
summary: 在实施云存储池之前，请查看存储在每种类型的云存储池中的对象的生命周期。 
---
= 云存储池对象的生命周期
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在实施云存储池之前，请查看存储在每种类型的云存储池中的对象的生命周期。



== S3 ：云存储池对象的生命周期

这些步骤介绍了S3云存储池中存储的对象的生命周期阶段。


NOTE: "Glaciere"是指Glacier存储类和Glacier深度归档存储类、但有一个例外：Glacier深度归档存储类不支持加缓还原层。仅支持批量或标准检索。


NOTE: Google Cloud Platform （ GCP ）支持从长期存储中检索对象，而无需执行还原后操作。

. * 存储在 StorageGRID 中的对象 *
+
要开始生命周期，客户端应用程序会将对象存储在 StorageGRID 中。

. * 对象已移至 S3 云存储池 *
+
** 如果对象与使用 S3 云存储池作为其放置位置的 ILM 规则匹配，则 StorageGRID 会将此对象移动到云存储池指定的外部 S3 存储分段。
** 将对象移动到S3云存储池后、客户端应用程序可以使用StorageGRID的S3 GetObject请求检索该对象、除非该对象已转移到Glacier.存储。


. * 已过渡到 Glacier 的对象（无法检索状态） *
+
** 也可以将对象过渡到 Glacier 存储。例如，外部 S3 存储分段可能会使用生命周期配置立即或在一定天数后将对象过渡到 Glacier 存储。
+

NOTE: 如果要过渡对象、则必须为外部S3存储分段创建生命周期配置、并且必须使用实施Glacier"存储类并支持S3 Restore-Object API的存储解决方案。

** 过渡期间、客户端应用程序可以使用S3 HeadObject请求监控对象的状态。


. * 对象已从 Glacier 存储还原 *
+
如果某个对象已转移到Glacier"存储、则客户端应用程序可以对S3 Restore-Object请求执行问题描述操作、以便将可检索副本还原到S3云存储池。此请求指定在云存储池和数据访问层中应使用多少天的副本来执行还原操作（加急，标准或批量）。达到可检索副本的到期日期后，该副本将自动恢复为无法检索的状态。

+

NOTE: 如果StorageGRID中的存储节点上也存在对象的一个或多个副本、则无需发出Restore-Object请求来从Glacier恢复 对象。而是可以使用GetObject请求直接检索本地副本。

. * 已检索对象 *
+
还原对象后、客户端应用程序可以问题描述一个GetObject请求来检索还原的对象。





== Azure ： Cloud Storage Pool 对象的生命周期

这些步骤介绍了存储在Azure云存储池中的对象的生命周期阶段。

. * 存储在 StorageGRID 中的对象 *
+
要开始生命周期，客户端应用程序会将对象存储在 StorageGRID 中。

. * 对象已移至 Azure Cloud Storage Pool*
+
如果对象符合使用Azure云存储池作为放置位置的ILM规则、则StorageGRID会将对象移动到由云存储池指定的外部Azure Blb存储容器。

. * 已过渡到归档层的对象（无法检索状态） *
+
将对象移动到 Azure 云存储池后， StorageGRID 会立即自动将对象过渡到 Azure Blob 存储归档层。

. * 对象已从归档层还原 *
+
如果某个对象已转移到归档层、则客户端应用程序可以对S3 Restore"对象请求执行问题描述操作、以便将可检索副本还原到Azure云存储池。

+
当StorageGRID收到"RestorEObject"时、它会临时将对象过渡到Azure Blb存储冷层。只要达到了RestoreObject请求中的到期日期、StorageGRID就会将对象转换回归档层。

+

NOTE: 如果StorageGRID中的存储节点上也存在对象的一个或多个副本、则无需发出Restore"对象请求、即可从归档访问层还原对象。而是可以使用GetObject请求直接检索本地副本。

. * 已检索对象 *
+
将对象还原到Azure云存储池后、客户端应用程序可以通过问题描述发出GetObject请求来检索还原的对象。



.相关信息
link:../s3/index.html["使用S3 REST API"]
