---
permalink: ilm/managing-objects-with-s3-object-lock.html 
sidebar: sidebar 
keywords: s3 object lock, manage objects with object lock 
summary: 作为网格管理员，您可以为 StorageGRID 系统启用 S3 对象锁定，并实施合规的 ILM 策略，以确保特定 S3 存储分段中的对象在指定时间内不会被删除或覆盖。 
---
= 使用 S3 对象锁定管理对象
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
作为网格管理员、您可以为StorageGRID 系统启用S3对象锁定、并实施合规的ILM策略、以帮助确保特定S3存储分段中的对象在指定时间内不会被删除或覆盖。



== 什么是 S3 对象锁定？

StorageGRID S3 对象锁定功能是一种对象保护解决方案 ，相当于 Amazon Simple Storage Service （ Amazon S3 ）中的 S3 对象锁定。

为StorageGRID系统启用全局S3对象锁定设置后、S3租户帐户可以在启用或不启用S3对象锁定的情况下创建分段。如果存储分段启用了S3对象锁定、则需要执行存储分段版本控制、并会自动启用此功能。

*没有S3对象锁定的存储分段*只能包含没有指定保留设置的对象。任何已加热的对象都不具有保留设置。

*具有S3对象锁定*的存储分段可以包含具有和不具有S3客户端应用程序指定的保留设置的对象。已加热的某些对象将具有保留设置。

*配置了S3对象锁定和默认保留的存储分段*可以上传具有指定保留设置的对象以及没有保留设置的新对象。新对象使用默认设置、因为尚未在对象级别配置保留设置。

配置默认保留后、所有新加的对象都会具有保留设置、这一点很有效。没有对象保留设置的现有对象不受影响。



=== 保留模式

StorageGRID S3对象锁定功能支持两种保留模式、可对对象应用不同级别的保护。这些模式相当于Amazon S3保留模式。

* 在合规模式下：
+
** 在达到保留截止日期之前、无法删除此对象。
** 对象的保留截止日期可以增加、但不能减少。
** 在达到该日期之前、无法删除对象的保留截止日期。


* 在监管模式下：
+
** 具有特殊权限的用户可以在请求中使用旁路标头来修改某些保留设置。
** 这些用户可以在达到保留截止日期之前删除对象版本。
** 这些用户可以增加、减少或删除对象的保留截止日期。






=== 对象版本的保留设置

如果在创建存储分段时启用了S3对象锁定、则用户可以使用S3客户端应用程序为添加到该存储分段的每个对象指定以下保留设置(可选)：

* *保留模式*：合规性或监管。
* *retain至日期*：如果某个对象版本的retain至日期为未来版本，则可以检索该对象，但不能将其删除。
* * 合法保留 * ：对对象版本应用合法保留时，会立即锁定该对象。例如，您可能需要对与调查或法律争议相关的对象进行法律保留。合法保留没有到期日期，但在明确删除之前始终有效。合法保留与保留日期无关。
+

NOTE: 如果某个对象处于合法保留状态、则无论其保留模式如何、任何人都无法删除该对象。

+
有关对象设置的详细信息，请参见link:../s3/use-s3-api-for-s3-object-lock.html["使用S3 REST API配置S3对象锁定"]。





=== 存储分段的默认保留设置

如果在创建存储分段时启用了S3对象锁定、则用户可以选择为此存储分段指定以下默认设置：

* *默认保留模式*：合规或监管。
* *默认保留期限*：添加到此存储分段的新对象版本应保留多长时间、从添加之日开始。


默认分段设置仅适用于没有自己的保留设置的新对象。添加或更改这些默认设置时、现有存储分段对象不会受到影响。

请参阅link:../tenant/creating-s3-bucket.html["创建 S3 存储区。"]和link:../tenant/update-default-retention-settings.html["更新S3对象锁定默认保留"]。



== 比较 S3 对象锁定与原有合规性

S3 对象锁定取代了早期 StorageGRID 版本中提供的合规性功能。由于S3对象锁定功能符合Amazon S3要求、因此会弃用专有的StorageGRID合规性功能、该功能现在称为"原有合规性"。


NOTE: 已弃用全局合规性设置。如果使用早期版本的StorageGRID 启用此设置、则会自动启用S3对象锁定设置。您可以继续使用StorageGRID 管理现有合规存储分段的设置、但不能创建新的合规存储分段。有关详细信息，请参见 https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_manage_legacy_Compliant_buckets_in_StorageGRID_11.5["NetApp 知识库：如何在 StorageGRID 11.5 中管理原有的合规存储分段"^]。

如果您在先前版本的 StorageGRID 中使用了原有的合规性功能，请参见下表，了解它与 StorageGRID 中的 S3 对象锁定功能的比较情况。

[cols="1a,1a,1a"]
|===
|  | S3 对象锁定 | 合规性（原有） 


 a| 
如何全局启用此功能？
 a| 
在网格管理器中，选择 * 配置 * > * 系统 * > * S3 对象锁定 * 。
 a| 
不再支持。



 a| 
如何为存储分段启用此功能？
 a| 
在使用租户管理器，租户管理 API 或 S3 REST API 创建新存储分段时，用户必须启用 S3 对象锁定。
 a| 
不再支持。



 a| 
是否支持存储分版本控制？
 a| 
是。需要分段版本控制，并且在为分段启用 S3 对象锁定时会自动启用分段版本控制。
 a| 
否



 a| 
如何设置对象保留？
 a| 
用户可以为每个对象版本设置保留截止日期、也可以为每个存储分段设置默认保留期限。
 a| 
用户必须为整个存储分段设置一个保留期限。保留期限适用场景 存储分段中的所有对象。



 a| 
是否可以更改保留期限？
 a| 
* 在合规模式下、对象版本的保留截止日期可以增加、但不能减少。
* 在监管模式下、具有特殊权限的用户可以减少甚至删除对象的保留设置。

 a| 
存储分段的保留期限可以延长、但不能缩短。



 a| 
合法保留在何处？
 a| 
用户可以对存储分段中的任何对象版本进行合法保留或取消合法保留。
 a| 
合法保留放置在存储分段上，并影响存储分段中的所有对象。



 a| 
何时可以删除对象？
 a| 
* 在合规模式下、可以在达到保留截止日期后删除对象版本、前提是对象不处于合法保留状态。
* 在监管模式下、具有特殊权限的用户可以在达到保留截止日期之前删除对象、前提是该对象不处于合法保留状态。

 a| 
可以在保留期限到期后删除对象，前提是存储分段未处于合法保留状态。可以自动或手动删除对象。



 a| 
是否支持存储分段生命周期配置？
 a| 
是
 a| 
否

|===