---
permalink: ilm/requirements-for-s3-object-lock.html 
sidebar: sidebar 
keywords: requirements, s3 object lock, compliant ilm rule, compliant ilm policy 
summary: 您必须查看启用全局 S3 对象锁定设置的要求，创建合规 ILM 规则和 ILM 策略的要求以及 StorageGRID 对使用 S3 对象锁定的分段和对象所施加的限制。 
---
= S3 对象锁定的要求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必须查看启用全局 S3 对象锁定设置的要求，创建合规 ILM 规则和 ILM 策略的要求以及 StorageGRID 对使用 S3 对象锁定的分段和对象所施加的限制。



== 使用全局 S3 对象锁定设置的要求

* 您必须先使用网格管理器或网格管理 API 启用全局 S3 对象锁定设置，然后任何 S3 租户才能创建启用了 S3 对象锁定的分段。
* 启用全局 S3 对象锁定设置后，所有 S3 租户帐户都可以在启用了 S3 对象锁定的情况下创建存储分段。
* 启用全局S3对象锁定设置后、无法禁用该设置。
* 除非所有活动ILM策略中的默认规则均为_兼容_(即、默认规则必须符合启用了S3对象锁定的分段的要求)、否则无法启用全局S3对象锁定。
* 启用全局S3对象锁定设置后、您无法创建新的ILM策略或激活现有ILM策略、除非该策略中的默认规则合规。启用全局S3对象锁定设置后、ILM规则和ILM策略页面将指示哪些ILM规则合规。




== 符合 ILM 规则的要求

如果要启用全局S3对象锁定设置、则必须确保所有活动ILM策略中的默认规则合规。合规规则可满足启用了 S3 对象锁定的两个存储分段以及启用了旧合规性的任何现有存储分段的要求：

* 它必须至少创建两个复制的对象副本或一个经过纠删编码的副本。
* 这些副本必须在放置说明中每行的整个持续时间内存在于存储节点上。
* 无法将对象副本保存在云存储池中。
* 至少一行放置指令必须从第0天开始、并使用*内嵌时间*作为参考时间。
* 放置说明中至少有一行必须为"永久"。




== ILM策略的要求

启用全局S3对象锁定设置后、活动和非活动ILM策略可以同时包含合规和不合规规则。

* 活动或非活动ILM策略中的默认规则必须合规。
* 不合规规则仅适用于未启用S3对象锁定或未启用原有合规性功能的分段中的对象。
* 合规规则可以应用于任何存储分段中的对象；不需要为此存储分段启用 S3 对象锁定或原有合规性。


link:example-7-compliant-ilm-policy-for-s3-object-lock.html["S3对象锁定的合规ILM策略示例"]



== 启用了 S3 对象锁定的存储分段的要求

* 如果为 StorageGRID 系统启用了全局 S3 对象锁定设置，则可以使用租户管理器，租户管理 API 或 S3 REST API 创建启用了 S3 对象锁定的分段。
* 如果您计划使用 S3 对象锁定，则必须在创建存储分段时启用 S3 对象锁定。您不能为现有存储分段启用S3对象锁定。
* 为存储分段启用 S3 对象锁定后， StorageGRID 会自动为该存储分段启用版本控制。您不能禁用存储分段的S3对象锁定或暂停版本控制。
* 您也可以使用租户管理器、租户管理API或S3 REST API为每个存储分段指定默认保留模式和保留期限。存储分段的默认保留设置仅适用于添加到存储分段中但没有自己的保留设置的新对象。您可以通过在上传每个对象版本时为其指定保留模式和保留截止日期来覆盖这些默认设置。
* 启用了S3对象锁定的分段支持分段生命周期配置。
* 启用了 S3 对象锁定的存储分段不支持 CloudMirror 复制。




== 启用了 S3 对象锁定的分段中的对象的要求

* 要保护对象版本、您可以为存储分段指定默认保留设置、也可以为每个对象版本指定保留设置。可以使用S3客户端应用程序或S3 REST API指定对象级保留设置。
* 保留设置适用于各个对象版本。对象版本可以同时具有保留截止日期和合法保留设置，但不能具有其他设置，或者两者均不具有。为对象指定保留日期或合法保留设置仅保护请求中指定的版本。您可以创建新版本的对象，而先前版本的对象仍保持锁定状态。




== 启用了 S3 对象锁定的存储分段中的对象生命周期

在启用了S3对象锁定的情况下保存在存储分段中的每个对象都会经历以下阶段：

. * 对象载入 *
+
将对象版本添加到启用了S3对象锁定的存储分段时、将按如下所示应用保留设置：

+
** 如果为对象指定了保留设置、则会应用对象级别设置。系统将忽略任何默认存储分段设置。
** 如果没有为对象指定保留设置、则会应用默认存储分段设置(如果存在)。
** 如果没有为对象或存储分段指定保留设置、则对象不受S3对象锁定保护。


+
如果应用了保留设置、则对象和任何S3用户定义的元数据都会受到保护。

. *对象保留和删除*
+
StorageGRID 会在指定的保留期限内存储每个受保护对象的多个副本。对象副本的确切数量和类型以及存储位置由活动ILM策略中的合规规则决定。是否可以在达到保留截止日期之前删除受保护对象取决于其保留模式。

+
** 如果某个对象处于合法保留状态、则无论其保留模式如何、任何人都无法删除该对象。




.相关信息
* link:../tenant/creating-s3-bucket.html["创建 S3 存储区。"]
* link:../tenant/update-default-retention-settings.html["更新S3对象锁定默认保留"]
* link:../s3/use-s3-api-for-s3-object-lock.html["使用S3 REST API配置S3对象锁定"]
* link:example-7-compliant-ilm-policy-for-s3-object-lock.html["示例 7 ： S3 对象锁定的兼容 ILM 策略"]

