---
permalink: ilm/troubleshooting-cloud-storage-pools.html 
sidebar: sidebar 
keywords: cloud storage pool, troubleshoot 
summary: 使用这些故障排除步骤可帮助解决在创建、编辑或删除云存储池时可能遇到的错误。 
---
= 对云存储池进行故障排除
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用这些故障排除步骤可帮助解决在创建、编辑或删除云存储池时可能遇到的错误。



== 确定是否发生错误

StorageGRID通过读取已知对象对每个云存储池执行简单的运行状况检查 `x-ntap-sgws-cloud-pool-uuid`、以确保可以访问云存储池且该池运行正常。当StorageGRID在端点上遇到错误时、它会每分钟从每个存储节点执行一次运行状况检查。解决错误后、运行状况检查将停止。如果运行状况检查检测到问题、则会在"存储池"页面上的"云存储池"表的"最后一个错误"列中显示一条消息。

此表显示了为每个云存储池检测到的最新错误，并指示错误发生的时间。

此外，如果运行状况检查检测到在过去 5 分钟内发生了一个或多个新的 Cloud Storage Pool 错误，则会触发 * 云存储池连接错误 * 警报。如果您收到有关此警报的电子邮件通知、请转到存储池页面(选择* ILM *>*存储池*)、查看最后一个错误列中的错误消息、并参阅下面的故障排除准则。



== 检查错误是否已解决

解决任何底层问题后，您可以确定错误是否已解决。从云存储池页面中、选择端点、然后选择*清除错误*。确认消息指示 StorageGRID 已清除云存储池的错误。

如果根本问题已解决，则不再显示此错误消息。但是、如果根本问题尚未修复(或者遇到其他错误)、则错误消息将在几分钟内显示在Last error列中。



== 错误：运行状况检查失败。端点出错

在开始对云存储池使用S3存储分段之后、如果为Amazon S3存储分段启用默认保留的S3对象锁定、则可能会遇到此错误。如果Put操作没有包含有效负载校验和值(如)的HTTP标头，则会发生此错误 `Content-MD5`。AWS需要使用此标头值来将操作放入启用了S3对象锁定的分段中。

要更正此问题、请按照中的步骤进行操作link:editing-cloud-storage-pool.html["编辑云存储池"]、而不进行任何更改。此操作将触发对云存储池配置的验证、该配置将自动检测和更新云存储池端点配置上的S3对象锁定标志。



== 错误：此云存储池包含意外内容

尝试创建，编辑或删除云存储池时，可能会遇到此错误。如果存储分段或容器包含标记文件、但该文件的元数据字段不具有预期的UUID、则会发生此错误 `x-ntap-sgws-cloud-pool-uuid`。

通常，只有在创建新的云存储池且另一个 StorageGRID 实例已使用同一个云存储池时，您才会看到此错误。

请尝试以下步骤之一来解决此问题：

* 如果要配置新的云存储池、并且存储分段包含与以下示例类似的文件和其他对象密钥、请创建一个新存储分段并改用此新存储 `x-ntap-sgws-cloud-pool-uuid`分段。
+
附加对象键的示例： `my-bucket.3E64CF2C-B74D-4B7D-AFE7-AD28BC18B2F6.1727326606730410`

* 如果 `x-ntap-sgws-cloud-pool-uuid`文件是存储分段中的唯一对象、请删除此文件。


如果这些步骤不适用于您的情形、请联系支持部门。



== 错误：无法创建或更新云存储池。端点出错

在以下情况下、您可能会遇到此错误：

* 尝试创建或编辑云存储池时。
* 在配置新的云存储池期间选择不受支持的平台、身份验证或协议与S3对象锁定的组合。请参阅。 link:../ilm/considerations-for-cloud-storage-pools.html["云存储池注意事项"]


此错误表示连接或配置问题导致StorageGRID无法写入云存储池。

要更正问题描述 ，请查看来自端点的错误消息。

* 如果错误消息包含 `Get _url_: EOF`，请检查用于云存储池的服务端点是否不对需要HTTPS的容器或分段使用HTTP。
* 如果错误消息包含 `Get _url_: net/http: request canceled while waiting for connection`，请验证网络配置是否允许存储节点访问用于云存储池的服务端点。
* 如果此错误是由于不受支持的平台、身份验证或协议导致的、请使用S3对象锁定更改为受支持的配置、然后再次尝试保存新的云存储池。
* 对于所有其他端点错误消息，请尝试以下一项或多项操作：
+
** 创建一个与您为云存储池输入的名称相同的外部容器或存储分段，然后再次尝试保存新的云存储池。
** 更正为云存储池指定的容器或存储分段名称，然后重新尝试保存新的云存储池。






== 错误：无法解析 CA 证书

在尝试创建或编辑云存储池时，您可能会遇到此错误。如果 StorageGRID 无法解析您在配置云存储池时输入的证书，则会发生此错误。

要更正问题描述 ，请检查您提供的 CA 证书是否存在问题。



== 错误：未找到具有此 ID 的云存储池

尝试编辑或删除云存储池时，可能会遇到此错误。如果端点返回 404 响应，则会发生此错误，这可能表示以下任一项：

* 用于云存储池的凭据没有此存储分段的读取权限。
* 用于云存储池的存储分段不包括 `x-ntap-sgws-cloud-pool-uuid`标记文件。


尝试以下一个或多个步骤以更正问题描述 ：

* 检查与配置的访问密钥关联的用户是否具有所需权限。
* 使用具有所需权限的凭据编辑云存储池。
* 如果权限正确，请联系支持部门。




== 错误：无法检查云存储池的内容。端点出错

在尝试删除云存储池时，您可能会遇到此错误。此错误表示某种类型的连接或配置问题描述 正在阻止 StorageGRID 读取云存储池存储分段的内容。

要更正问题描述 ，请查看来自端点的错误消息。



== 错误：对象已放置在此存储分段中

在尝试删除云存储池时，您可能会遇到此错误。如果云存储池包含通过ILM移动到该存储池的数据、在配置云存储池之前存储分段中的数据或在创建云存储池之后由其他源放置在分段中的数据、则不能删除该数据。

尝试以下一个或多个步骤以更正问题描述 ：

* 按照"云存储池对象的生命周期"中有关将对象移回StorageGRID的说明进行操作。
* 如果您确定其余对象未被 ILM 放置在云存储池中，请手动从存储分段中删除这些对象。
+

NOTE: 切勿手动删除云存储池中可能已由 ILM 放置的对象。如果稍后尝试从 StorageGRID 访问手动删除的对象，则找不到已删除的对象。





== 错误：代理尝试访问云存储池时遇到外部错误

如果您在存储节点与用于云存储池的外部S3端点之间配置了非透明存储代理、则可能会遇到此错误。如果外部代理服务器无法访问云存储池端点、则会发生此错误。例如， DNS 服务器可能无法解析主机名，或者可能存在外部网络问题描述 。

尝试以下一个或多个步骤以更正问题描述 ：

* 检查云存储池（ * ILM * > * 存储池 * ）的设置。
* 检查存储代理服务器的网络配置。




== 错误：X.509证书已超出有效期

在尝试删除云存储池时，您可能会遇到此错误。如果身份验证需要X.509证书来确保正确的外部云存储池已通过验证、并且在删除云存储池配置之前外部池为空、则会发生此错误。

请尝试以下步骤以更正问题描述 ：

* 更新为向云存储池进行身份验证而配置的证书。
* 确保已解决此云存储池上的任何证书到期警报。


.相关信息
link:lifecycle-of-cloud-storage-pool-object.html["云存储池对象的生命周期"]
