---
permalink: ilm/when-to-use-cloud-storage-pools.html 
sidebar: sidebar 
keywords: use cloud storage pool, benefits of cloud storage pools 
summary: 使用云存储池、您可以将数据备份或分层到外部位置。此外、您还可以将数据备份或分层到多个云。 
---
= 何时使用云存储池
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用云存储池、您可以将数据备份或分层到外部位置。此外、您还可以将数据备份或分层到多个云。



== 将StorageGRID 数据备份到外部位置

您可以使用云存储池将 StorageGRID 对象备份到外部位置。

如果无法访问 StorageGRID 中的副本，则可以使用云存储池中的对象数据来处理客户端请求。但是、要访问云存储池中的备份对象副本、您可能需要问题描述S3 RestoreObject请求。

云存储池中的对象数据也可用于恢复因存储卷或存储节点故障而从 StorageGRID 丢失的数据。如果某个对象的唯一剩余副本位于云存储池中，则 StorageGRID 会临时还原该对象，并在已恢复的存储节点上创建一个新副本。

要实施备份解决方案 ，请执行以下操作：

. 创建一个云存储池。
. 配置一个 ILM 规则，以便在存储节点上同时存储对象副本（以复制或擦除编码的副本的形式），并在云存储池中存储单个对象副本。
. 将规则添加到 ILM 策略中。然后，模拟并激活策略。




== 将数据从StorageGRID 分层到外部位置

您可以使用云存储池将对象存储在 StorageGRID 系统之外。例如，假设您需要保留大量对象，但您希望很少访问这些对象（如果有）。您可以使用云存储池将对象分层以降低存储成本并释放 StorageGRID 中的空间。

要实施分层解决方案 ，请执行以下操作：

. 创建一个云存储池。
. 配置一个 ILM 规则，以便将很少使用的对象从存储节点移动到云存储池。
. 将规则添加到 ILM 策略中。然后，模拟并激活策略。




== 维护多个云端点

如果要将对象数据分层或备份到多个云、您可以配置多个Cloud Storage Pool端点。您可以通过 ILM 规则中的筛选器指定存储在每个云存储池中的对象。例如、您可能希望存储Amazon S3 Glacier"中某些租户或分段的对象以及Azure Blb存储中其他租户或分段的对象。或者，您可能希望在 Amazon S3 Glacier 和 Azure Blob 存储之间移动数据。


NOTE: 使用多个云存储池端点时、请记住、一个对象一次只能存储在一个云存储池中。

实施多个云端点：

. 最多创建 10 个云存储池。
. 配置 ILM 规则，以便在每个云存储池中的适当时间存储相应的对象数据。例如、将存储分段A中的对象存储在云存储池A中、将存储分段B中的对象存储在云存储池B中。或者、将对象存储在云存储池A中一段时间、然后将其移动到云存储池B
. 将规则添加到 ILM 策略中。然后，模拟并激活策略。

