---
permalink: release-notes/whats-new.html 
sidebar: sidebar 
keywords: what is new in StorageGRID 12.1 
summary: 此版本的 StorageGRID 引入了以下功能和功能更改。 
---
= StorageGRID 12.1 中的新增功能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 12.1 引入了以下功能和功能更改。

有关最新 StorageGRID 12.1 版本中的修复问题和已知问题的详细信息，请参见 https://library.netapp.com/ecm/ecm_download_file/ECMLP3373065["StorageGRID 12.1 发行说明"^]。您必须使用您的 NetApp 帐户登录或创建帐户才能访问发行说明。



[[capacity]]
== 容量



[[ec-rebalance-now-uses-free-space]]
=== EC 再平衡现在使用可用空间

EC再平衡现在使用可用空间而不是已用空间。请参阅 link:../expand/considerations-for-rebalancing-erasure-coded-data.html#what-is-ec-rebalancing["了解StorageGRID扩展后的 EC 重新平衡"]。



[[metadata-allowed-space]]
=== 元数据允许的空间

现在可以将允许的最大元数据值从 3.96 TB 增加到 7.92 TB。请参阅link:../admin/managing-object-metadata-storage.html#allowed-metadata-space["允许的元数据空间"]。



[[control-access]]
== 控制访问



[[sso-using-oidc]]
=== 使用 OIDC 的 SSO

您现在可以 link:../admin/learn-about-setting-up-sso-oidc.html["使用 OpenID Connect (OIDC) 在 StorageGRID 中设置单点登录 (SSO)"]。



[[federation]]
== 联邦



[[global-namespace]]
=== 全局命名空间

您可以设置全局命名空间以允许租户跨多个 StorageGRID 系统访问存储桶。请参阅link:../admin/learn-about-global-namespace.html["了解全局命名空间"]。



[[manageability]]
== 易管理性



[[auto-move-adc-service]]
=== 自动移动 ADC 服务

link:../maintain/understanding-adc-service-quorum.html["当需要满足 ADC 仲裁要求时"]，当您link:../maintain/convert-to-data-only-node.html["将存储节点转换为仅数据节点"]或link:../maintain/considerations-for-decommissioning-storage-nodes.html["停用存储节点"]时，ADC 服务将自动移动。



[[primary-admin-node-recovery]]
=== 主管理节点恢复

您可以从非主管理节点恢复任何节点。请参阅link:../maintain/recovering-from-primary-admin-node-failures.html["从主管理节点故障中恢复"]。



[[s3]]
== S3



[[enable-s3-object-lock-on-existing-buckets]]
=== 在现有存储桶上启用 S3 对象锁定

启用现有存储桶的允许 S3 对象锁定设置后，S3 租户帐户现在可以为现有存储桶启用 S3 对象锁定。S3 租户帐户为现有存储桶启用 S3 对象锁定后，无法禁用它。



[[replication-allowed-for-s3-object-lock-enabled-buckets]]
=== 允许为启用了 S3 对象锁的存储桶进行复制

现在，您可以使用 CloudMirror 在启用了 S3 对象锁定的存储桶中复制对象。请参阅 link:../tenant/considerations-for-platform-services.html["了解平台服务"]。



[[enable-cross-grid-replication-for-non-empty-buckets]]
=== 为非空存储桶启用跨网格复制

现在，您可以为不为空的存储桶启用跨网格复制。请参见link:../admin/grid-federation-what-is-cross-grid-replication.html#requirements-for-cross-grid-replication["跨网格复制的要求"]。



[[s3-batch-operations-fpvr-only]]
=== S3 批量操作（仅限 FPVR）

您可以使用 S3 批处理操作来复制您计划为跨网格复制配置的启用版本控制的存储桶中的现有对象。

此功能需要 StorageGRID 12.1 的 FPVR 批准。要使用此功能，请联系您的客户代表。



[[non-functional-s3-rest-api-headers]]
=== 非功能性 S3 REST API 标头

 `If-Match` 和  `If-None-Match` 标头已被接受，但对于 S3 REST API link:../s3/put-object.html["PutObject"]、link:../s3/complete-multipart-upload.html["CompleteMultipartUpload"]、link:../s3/put-object-copy.html["CopyObject"] 和 link:../s3/operations-on-objects.html["DeleteObject"] 无效。

有关详细信息，请参阅 link:../release-notes/changes-to-s3-rest-api.html["对 StorageGRID S3 REST API 支持的更改"]。



[[support-for-pre-calculated-checksum-values]]
=== 支持预先计算的校验和值

S3 REST SPI 现在支持预先计算的校验和值和 `x-amz-checksum-type`请求标头。请参阅link:../s3/index.html#updates-to-rest-api-support["REST API 支持更新"]。



[[security]]
== 安全性



[[multi-admin-verification]]
=== 多管理员验证

多管理员验证(MAV)有助于防止对 StorageGRID 系统进行意外或未经授权的更改。请参阅 link:../admin/about-multi-admin-verify.html["了解 StorageGRID 多管理员验证"]。



[[security-policy-updates-for-fips]]
=== FIPS 的安全策略更新

已更新 FIPS 严格策略条件。请参阅 link:../admin/manage-tls-ssh-policy.html#select-a-security-policy["在管理 TLS 和 SSH 策略中选择安全策略"]。



[[tenants]]
== 租户



[[account-sync]]
=== 帐户同步

_account clone_ 功能现在是指特定租户帐户信息的一次性克隆。

_Account sync_ 是一项新功能，允许您在一个或多个网格联合连接中在 StorageGRID 系统之间自动且连续地复制租户帐户、租户组、租户用户和 S3 访问密钥。请参阅 link:../admin/grid-federation-what-is-account-sync.html["了解 StorageGRID 中的帐户同步"]。



[[kafka-endpoints-and-mtls-authentication]]
=== Kafka 端点和 mTLS 身份验证

Kafka 端点现在支持相互传输层安全性 (mTLS)。请参阅link:../tenant/configuring-platform-services-endpoints.html["配置平台服务端点"]。



[[maximum-number-of-buckets]]
=== 最大桶数

StorageGRID 系统现在支持每个 S3 租户帐户最多 20,000 个存储桶。



[[upgrade]]
== 升级



[[time-to-enable-features-is-increased]]
=== 启用功能的时间增加了

在 StorageGRID 升级到版本 12.1 期间，启用功能的时间从不到五分钟增加到一小时。请参阅 link:../upgrade/estimating-time-to-complete-upgrade.html#estimate-time-to-upgrade["估计完成 StorageGRID 升级的时间"]。



[[user-interface]]
== 用户接口



[[bmc-settings-page]]
=== BMC 设置页面

新的 BMC 设置选项卡已添加到 Grid Manager 中的节点页面，以允许重置 BMC 密码并更改 BMC LAN IP 设置。请参阅 link:../harden/hardening-guidelines-for-storagegrid-nodes.html["更改设备 BMC 密码"] 和 link:../maintain/changing-nodes-network-configuration.html#change-appliance-node-bmc-lan-ip-settings["更改设备节点 BMC LAN IP 设置"]。还添加了新的 API 端点以支持这些功能。请参阅 link:../release-notes/changes-to-grid-management-api.html["用于更改 BMC 密码和 LAN IP 设置的新端点"]。



[[email-notifications]]
=== 电子邮件通知

网格管理器现在有一个通用电子邮件页面，用于配置和管理警报、AutoSupport 和多管理员验证 (MAV) 的电子邮件通知。请参阅 link:../monitor/configure-email-server.html["配置电子邮件服务器"]。



[[link-cost-page-update]]
=== 链路成本页面更新

StorageGRID 12.1 提供了更详细的链路成本信息和设置。请参阅 link:../admin/manage-link-costs.html["管理链路成本"]。



[[usb-port-control]]
=== USB 端口控制

您可以通过 Grid Manager 启用或禁用 USB 端口。请参阅link:../harden/hardening-guidelines-for-storagegrid-nodes.html#control-remote-access-through-usb-ports["通过 USB 端口控制远程访问"]。
