---
permalink: fabricpool/other-best-practices-for-storagegrid-and-fabricpool.html 
sidebar: sidebar 
keywords: fabricPool, best practices, audit log, encryption, compressions, tiering, ontap, consistency 
summary: 在配置StorageGRID 系统以与FabricPool 结合使用时、您可能需要更改其他StorageGRID 选项。在更改全局设置之前、请考虑此更改会对其他S3应用程序产生何种影响。 
---
= StorageGRID 和 FabricPool 的其他最佳实践
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在配置StorageGRID 系统以与FabricPool 结合使用时、您可能需要更改其他StorageGRID 选项。在更改全局设置之前、请考虑此更改会对其他S3应用程序产生何种影响。



== 审核消息和日志目标

FabricPool 工作负载的读取操作率通常较高、从而可能会生成大量审核消息。

* 如果您不需要FabricPool 或任何其他S3应用程序的客户端读取操作记录，可选择进入*configuration*>*Monitoring*>*Audit and syslog server*。将“*客户端读取”设置更改为“*错误”，以减少审核日志中记录的审核消息数。有关详细信息、请参见。 link:../monitor/configure-audit-messages.html["配置审核消息和日志目标"]
* 如果您的网格很大、可以使用多种类型的S3应用程序、也可以保留所有审核数据、配置外部系统日志服务器并远程保存审核信息。使用外部服务器可以最大限度地降低审核消息日志记录对性能的影响、而不会降低审核数据的完整性。有关详细信息、请参见。 link:../monitor/considerations-for-external-syslog-server.html["外部系统日志服务器的注意事项"]




== 对象加密

配置StorageGRID时、如果其他StorageGRID客户端需要数据加密、您可以选择启用link:../admin/changing-network-options-object-encryption.html["用于存储对象加密的全局选项"]。从 FabricPool 分层到 StorageGRID 的数据已加密，因此不需要启用 StorageGRID 设置。客户端加密密钥归 ONTAP 所有。



== 对象压缩

配置StorageGRID时，请勿启用link:../admin/configuring-stored-object-compression.html["用于压缩存储对象的全局选项"]。已对从 FabricPool 分层到 StorageGRID 的数据进行压缩。使用StorageGRID 选项不会进一步减小对象的大小。



== 存储分段一致性

对于FabricPool存储分段、建议的存储分段一致性为*新写入后读取*、这是新存储分段的默认一致性。请勿编辑FabricPool存储分段以使用*可用*或*强站点*。



== FabricPool 分层

如果StorageGRID 节点使用从NetApp ONTAP 系统分配的存储、请确认此卷未启用FabricPool 分层策略。例如，如果 StorageGRID 节点正在 VMware 主机上运行，请确保为 StorageGRID 节点的数据存储库提供支持的卷未启用 FabricPool 分层策略。对 StorageGRID 节点使用的卷禁用 FabricPool 分层可简化故障排除和存储操作。


CAUTION: 切勿使用 FabricPool 将与 StorageGRID 相关的任何数据分层回 StorageGRID 本身。将 StorageGRID 数据分层回 StorageGRID 会增加故障排除和操作复杂性。
